/**
  * The source code in this file is the property of
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/4669_T01271350/4669/transactive/app/radio/RadioTetraAgent/src/Radio.cpp $
  * @author:  Ripple
  * @version: $Revision: #5 $
  *
  * Last modification: $DateTime: 2009/09/23 13:09:47 $
  * Last modified by:  $Author: builder $
  *
  */
///////////////////////////////////////////////////////////
//
//  Radio.cpp
//  Implementation of the Class Radio
//  Generated by Enterprise Architect
//  Created on:      29-Oct-2003 16:10:10
//  Original author: Andy Parker
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "core/types/src/ta_types.h"
#include "core/utilities/src/TAAssert.h"
#include "core/utilities/src/ILogType.h"
#include "core/utilities/src/DebugUtil.h" 
#include "core/utilities/src/RunParams.h"
#include "core/exceptions/src/DataException.h"
#include "core/exceptions/src/DatabaseException.h"
#include "core/message/types/RadioAlarms_MessageTypes.h"

#include "Radio.h"
#include "RadioHelper.h"
#include "RadioSession.h"
#include "RadioTcpServer.h"
#include "IRadioCallback.h"
#include "RadioTaskFactory.h"
#include "RadioSessionHelper.h"
#include "RadioSessionException.h"
#include "RadioTransactionManager.h"
#include "IRadioDirectoryCallback.h"
#include "RadioCorbaTypeConverter.h"
#include "RadioBackgroundProcessor.h"
#include "RadioAgentConstants.h"
#include "RadioConnectionManager.h"
#include "RadioStatusSummary.h"
#include "RadioDirectoryServant.h"

#include "core/data_access_interface/src/IProfile.h"
#include "core/data_access_interface/src/ProfileAccessFactory.h"
#include "core/data_access_interface/radio/src/RASpeedDialSet.h"
#include "app/radio/RadioTetraAgent/src/RadioStateUpdateBroadcaster.h"
#include "core/exceptions/src/DataException.h"
#include "core/threads/src/WorkItemQueueProcessor.h"
using namespace TA_Base_Core;
using namespace TA_IRS_App;


Radio::Radio(RadioServerLinkStatusUpdateThread* linkStatusThread,IRadioCallback& callback/*, TA_Base_Bus::ItaScada& scada*/) 
      : m_ISCSRadioSession(0),
		m_Occ2RadioSession(0),
        m_callback(callback),
        m_directoryCallback(0),
        m_backgroundProcessor(0),
        m_active(false),
        m_inFallback(false),
        m_fallbackReplacementString(""),
        m_serverLinkStatusThread(linkStatusThread),
		m_defaultVolume(RadioAgentConstants::DEFAULT_AUDIO_VOLUME)
		
{
	FUNCTION_ENTRY("Constructor");

    m_backgroundProcessor = new RadioBackgroundProcessor(this);

    m_radioCircuitModeManager = new RadioCircuitModeManager(*this);
    m_radioCircuitModeManager->start();

	m_backgroudQueueProcessor = new TA_Base_Core::WorkItemQueueProcessor();
	FUNCTION_EXIT;
}


Radio::~Radio()
{
	FUNCTION_ENTRY("Destructor");
	m_backgroudQueueProcessor->terminateAndWait();
    m_radioCircuitModeManager->terminateAndWait();
    delete m_radioCircuitModeManager;
    delete m_backgroundProcessor;
	delete m_backgroudQueueProcessor;

	FUNCTION_EXIT;
}

void Radio::setEntity(TA_Base_Core::IEntityData& entityData)
{
	RadioTcpServerArray::const_iterator it;
	for (it = m_radioTcpServers.begin();
		 it != m_radioTcpServers.end();
		 it ++)
	{
		(*it)->setEntity(entityData);
	}
}

IRadioCallback& Radio::getRadioCallback()
{
    return this->m_callback;
}

void Radio::start()
{
	FUNCTION_ENTRY("start");
    for ( RadioTcpServerArray::iterator iter = m_radioTcpServers.begin() ;
          iter != m_radioTcpServers.end() ;
          iter++)
    {
        (*iter)->start();
    }

	// Start Thread
	m_backgroudQueueProcessor->start();
    FUNCTION_EXIT;
}

void Radio::setOcc2RadioSession(RadioSession& session)
{
	FUNCTION_ENTRY("setOcc2RadioSession");
	TA_ASSERT(m_Occ2RadioSession==NULL,"Occ2 radio session already defined.");
	m_Occ2RadioSession = &session;
	FUNCTION_EXIT;
}

void Radio::setParameters( const std::string & primaryAddresses,
                           const std::string & secondaryAddresses,
						    ta_uint32  defaultVolume,
                           unsigned char serialiseTransactionLevel,
                           unsigned long radioTransactionTimeout,
                            ta_uint32  xonXoffTimeout,
                            ta_uint32  circuitDataFramesPerPacket )
{
	LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugDebug, 
            "Using radio hosts primary <%s>, secondary <%s>",
            primaryAddresses.c_str(), secondaryAddresses.c_str() );

    std::vector<std::string> primaryHosts;
    std::vector<std::string> secondaryHosts;

	m_defaultVolume = defaultVolume;

    RadioHelper::tokenise(primaryAddresses.c_str(), primaryHosts, ",");
    RadioHelper::tokenise(secondaryAddresses.c_str(), secondaryHosts, ",");

    // even up the secondary addresses, by adding nullstrings until there are
    // as many secondary as primary.  If there are more secondary than primary
    // they will be ignored subsequently...
    while ( secondaryHosts.size() < primaryHosts.size() )
    {
        secondaryHosts.push_back("");
    }

    //
    // delete/remove/deallocate all the current tcp servers
    for ( RadioTcpServerArray::iterator iter = m_radioTcpServers.begin() ;
          iter != m_radioTcpServers.end() ;
          iter++)
    {
        delete (*iter);
    }

    // use an integer index rather than iterator, as we need to use both 
    // primary and secondary vectors, plus the tcpserver array simultaneously
    // Note that we only set the servers until the end of the primaryAddresses
    // list, so extra secondary servers are ignored.
    // TODO: fix so that primaryaddresses.size() is correct
    for( size_t i=0 ; i< secondaryHosts.size() ; i++ )
    {
        RadioTcpServer * newRadioTcpServer = new RadioTcpServer( m_callback,
                                                                 i,
                                                                 *this,
                                                                 //m_scada,
                                                                 primaryHosts[i],
                                                                 secondaryHosts[i],
                                                                 serialiseTransactionLevel,
																 radioTransactionTimeout);
        m_radioTcpServers.push_back(newRadioTcpServer);
    }

    m_radioCircuitModeManager->setParameters( xonXoffTimeout, circuitDataFramesPerPacket );
}

void Radio::updateControlConnectionState(EControlConnectionStatus controlConnectionStatus,  ta_uint32  TcpServerIndex)
{
	m_radioTcpServers[TcpServerIndex]->updateControlConnectionState( controlConnectionStatus );
}

/**
* Used by the ISCS Radio session to advise Radio of the special session (used for trainborne comms)
* @param    session
*/
void Radio::setISCSRadioSession(RadioSession& session)
{
	FUNCTION_ENTRY("setISCSRadioSession");
	TA_ASSERT(m_ISCSRadioSession==NULL,"ISCS radio session already defined.");
	m_ISCSRadioSession = &session;
	FUNCTION_EXIT;
}


void Radio::setToControlMode(void)
{
	FUNCTION_ENTRY("setToControlMode");
	LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugInfo, 
		 "Setting radio to control mode");
	m_active = true;
    for ( RadioTcpServerArray::iterator iter = m_radioTcpServers.begin() ;
          iter != m_radioTcpServers.end() ;
          iter++)
    {
        (*iter)->setToControlMode();
    }
	FUNCTION_EXIT;
}

void Radio::setToMonitorMode(void)
{
	FUNCTION_ENTRY("setToMonitorMode");
	LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugInfo, 
		 "Setting radio to monitor mode");
	m_active = false;
    for ( RadioTcpServerArray::iterator iter = m_radioTcpServers.begin() ;
          iter != m_radioTcpServers.end() ;
          iter++)
    {
        (*iter)->setToMonitorMode();
    }
	FUNCTION_EXIT
}

bool Radio::getIsActive(void)
{
	return m_active;
}

void Radio::onTerminate(bool peerAvailable)
{
    FUNCTION_ENTRY("onTerminate");
    for ( RadioTcpServerArray::iterator iter = m_radioTcpServers.begin() ;
          iter != m_radioTcpServers.end() ;
          iter++)
    {
        (*iter)->onTerminate(peerAvailable);
    }
    FUNCTION_EXIT;
}


/**
* This function returns the session reference for this session.  It is used to identify calls that belong to this session
*/
SessionReference Radio::getISCSRadioSessionRef()
{
	FUNCTION_ENTRY("getISCSRadioSessionRef");
	FUNCTION_EXIT;
	return m_ISCSRadioSession->getValidSessionRef();
}


/**
* This method sends a method request to the radio system and waits for a reply (event).  
* It will be used by the RadioSession to perform its operations.
* @param    Method
*/
TA_IRS_App::RadioEvent* Radio::sendMethod(RadioMethod& method)
{
	FUNCTION_ENTRY("sendMethod");
	
	FUNCTION_EXIT;
	return m_ISCSRadioSession->getTcpServer().sendMethod(method);
	
}	

TA_IRS_App::RadioEvent* Radio::sendMethod(RadioMethod& method, const RadioDirectorySynchronisation & radiodirsync)
{
	FUNCTION_ENTRY("sendMethod");
	FUNCTION_EXIT;
	return getOcc2RadioSession().getTcpServer().sendMethod(method);
}

std::vector<RadioEvent*> Radio::sendMethodMultipleResponse(RadioMethod& method)
{
	FUNCTION_ENTRY("sendMethodMultipleResponse");
	FUNCTION_EXIT;
	return m_ISCSRadioSession->getTcpServer().sendMethodMultipleResponse(method);
}


void Radio::getCallList(ConsoleID consoleId, CallList& callList) 
{
	FUNCTION_ENTRY("getCallList");

	TA_Base_Core::ThreadGuard  guard(m_callStackLock);	

	// Reset the list
	callList.clear();

    ConsoleToSessionServerMap::iterator fndC2ss = m_consoleSessionServers.find(consoleId);
	if(fndC2ss == m_consoleSessionServers.end())
	{
		FUNCTION_EXIT;
		return;
	}

	ServerIndex srvIdx = fndC2ss->second.second;
	for ( RadioTcpServerArray::iterator iter = m_radioTcpServers.begin() ;
		  iter != m_radioTcpServers.end() ;
		  iter++)
	{
		if((*iter)->getServerIndex() == srvIdx)
		{
			(*iter)->getCallList(callList);
			FUNCTION_EXIT;
			return;
		}

	}

	FUNCTION_EXIT;
}


// TD12462 In fallback, cannot send SDS to train if audio already established
void Radio::getTsiCallList(const std::string & tsi, bool audioOnly, CallList & callList)
{
	FUNCTION_ENTRY("getTsiCallList");

	TA_Base_Core::ThreadGuard  guard(m_callStackLock);	

	// Reset the list
	callList.clear();

    for ( RadioTcpServerArray::iterator iter = m_radioTcpServers.begin() ;
          iter != m_radioTcpServers.end() ;
          iter++)
    {
        (*iter)->getTsiCallList(tsi, audioOnly, callList);
    }

	FUNCTION_EXIT;
}


bool Radio::getCallDetails(CallID callId, ConsoleID consoleId, CallDetailsType& details)
{
	FUNCTION_ENTRY("getCallDetails");
	
    // TODO: fix this MEGA-HACKA-KLUDGEROONI by adding console and session
    // stuff into the idl
    ConsoleToSessionServerMap::iterator fndC2ss = m_consoleSessionServers.find(consoleId);
	if(fndC2ss == m_consoleSessionServers.end())
	{
        LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugDebug, "Console ID=%lu NOT found", consoleId);
        std::ostringstream oss;
        oss << "Consoles available:";
        for ( ConsoleToSessionServerMap::iterator iter = m_consoleSessionServers.begin() ; iter != m_consoleSessionServers.end() ; iter++ )
        {
             ta_uint32  iterConsoleId = (*iter).first;
            oss << " " << iterConsoleId;
        }
        LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugDebug, oss.str().c_str() );

		FUNCTION_EXIT;
		return false;
	}

	ServerIndex srvIdx = fndC2ss->second.second;
    try
    {
        RadioTcpServer * tcpServer = m_radioTcpServers[srvIdx];
        bool success = tcpServer->getCallDetails(callId, details);
        FUNCTION_EXIT;
        return success;
    }
    catch (...)
    {
        LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugError, "Invalid RadioTcpServer requested: %d", srvIdx );
    }


	FUNCTION_EXIT;
	return false;
}

// RvH 20050115 Radio Pre-iFAT
bool Radio::getCallDetailsPartial(CallID callId, ConsoleID consoleId, CallDetailsType& details)
{
	FUNCTION_ENTRY("getCallDetailsPartial");
	
    ConsoleToSessionServerMap::iterator fndC2ss = m_consoleSessionServers.find(consoleId);
	if(fndC2ss == m_consoleSessionServers.end())
	{
        LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugDebug, "Console ID=%lu NOT found", consoleId);
        std::ostringstream oss;
        oss << "Consoles available:";
        for ( ConsoleToSessionServerMap::iterator iter = m_consoleSessionServers.begin() ; iter != m_consoleSessionServers.end() ; iter++ )
        {
             ta_uint32  iterConsoleId = (*iter).first;
            oss << " " << iterConsoleId;
        }
        LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugDebug, oss.str().c_str() );

		FUNCTION_EXIT;
		return false;
	}

	ServerIndex srvIdx = fndC2ss->second.second;
    try
    {
        RadioTcpServer * tcpServer = m_radioTcpServers[srvIdx];
        bool success = tcpServer->getCallDetailsPartial(callId, details);
        FUNCTION_EXIT;
        return success;
    }
    catch (...)
    {
        LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugError, "Invalid RadioTcpServer requested: %d", srvIdx );
    }

	FUNCTION_EXIT;
	return false;
}


void Radio::addCallDriverRequest(unsigned char trainID,const char* trainTSI)
{
	FUNCTION_ENTRY("addCallDriverRequest");
	TA_IRS_App::CallDetailsType   callDetails;

	callDetails.callID         = trainID;
	callDetails.sessionRef     = m_ISCSRadioSession->getValidSessionRef();
	callDetails.callStatus     = TA_IRS_App::Ringing;
	callDetails.callCategory   = TA_IRS_App::CallDriver;
	callDetails.callType       = TA_IRS_App::SingleCall;
	callDetails.callSource     = TA_IRS_App::IncomingCall;
    callDetails.time           = 0;
	callDetails.callTime       = "";
	callDetails.callerName     = trainTSI;
	callDetails.callerTSI      = trainTSI;
	callDetails.callerLocation = "";
	callDetails.calledName     = "";
	callDetails.calledTSI      = "";
	callDetails.calledLocation = "";
    callDetails.isEmergency    = false;
	//TD 10234
    callDetails.isInvisibleToGUIApps = false;

	m_ISCSRadioSession->getTcpServer().addCallToCallStack(callDetails);
}

void Radio::removeCallDriverRequest(unsigned char trainID)
{

	FUNCTION_ENTRY("removeCallDriverRequest");
    // WAS:
	// removeCallFromCallStack(trainID,true);
    for (   RadioTcpServerArray::iterator iter=m_radioTcpServers.begin() ;
            iter != m_radioTcpServers.end() ;
            iter++
        )
    {
        if ((*iter)->removeCallFromCallStack(trainID, true))
        {
            return;
        }
    }

	FUNCTION_EXIT;			
}




/**
* sends an SDS message to the train identified in the message.  
* It will then create a message for the radio to send an SDS with the train message embedded. 
* The ISCS radio session will be used. This will then be transmitted through the TCP/IP link
*/
void Radio::sendTrainCommand(const char* trainITSI,std::vector<unsigned char> message)
{
	FUNCTION_ENTRY("sendTrainCommand");

	TA_ASSERT(m_ISCSRadioSession!=NULL,"No ISCS radio session defined to send train command");
	
	std::string status;
	m_ISCSRadioSession->sendTextDataMessage(trainITSI, message, TA_IRS_App::Individual, status);

	FUNCTION_EXIT;
}

bool Radio::sendSDSTLMessage(const char* trainITSI, const TA_IRS_App::MessageListType& messages, std::string &status)
{
	FUNCTION_ENTRY("sendSDSTLMessage");

	TA_ASSERT(m_ISCSRadioSession!=NULL,"No ISCS radio session defined to send train command");

	FUNCTION_EXIT;
	//session is not needed here so make it NULL
	return m_ISCSRadioSession->sendTextMessage(trainITSI, messages, Individual, "", status);
}

bool Radio::sendUserDefinedSDSMessage(const char* trainITSI, const TA_IRS_App::MessageListType& messages, std::string &status)
{
	FUNCTION_ENTRY("sendUserDefinedSDSMessage");
	TA_ASSERT(m_ISCSRadioSession!=NULL,"No ISCS radio session defined to send train command");


	FUNCTION_EXIT;
	//session is not needed here so make it NULL
	return m_ISCSRadioSession->sendUserDefinedSDS(trainITSI, messages, "", status);
}


RadioReference Radio::setupDataCall(const std::string& destinationTsi, const std::string& destIPAddress)
{
    FUNCTION_ENTRY("setupDataCall");

	TA_ASSERT(m_ISCSRadioSession!=NULL,"No ISCS radio session defined to send train circuitData");
	return m_ISCSRadioSession->setupDataCall(destinationTsi, destIPAddress);

	FUNCTION_EXIT
}


void Radio::sendCircuitDataFrame( RadioReference callReference,
                                  const RadioCircuitTransfer::Data& frame )
{
    FUNCTION_ENTRY("sendCircuitDataFrame");

	TA_ASSERT(m_ISCSRadioSession!=NULL,"No ISCS radio session defined to send train circuitData");
	m_ISCSRadioSession->sendCircuitDataFrame( callReference, frame );

	FUNCTION_EXIT
}


void Radio::endDataCall( RadioReference callReference )
{
    FUNCTION_ENTRY("endDataCall");

	TA_ASSERT(m_ISCSRadioSession!=NULL,"No ISCS radio session defined to send train circuitData");
	m_ISCSRadioSession->endDataCall( callReference );

	FUNCTION_EXIT
}


void Radio::clearDataCallReference( RadioReference callReference )
{
    FUNCTION_ENTRY("clearDataCallReference");

	TA_ASSERT(m_ISCSRadioSession!=NULL,"No ISCS radio session defined to send train circuitData");
	m_ISCSRadioSession->clearDataCallReference( callReference );

	FUNCTION_EXIT
}






/**
* Sent when the hardware is acknowledging a circuit mode data transfer packet.
* This will be recorded in the RadioCircuitModeManager and another packet sent
* for that call.
*/
void Radio::onIncomingCircuitData(const TA_IRS_App::IncomingCircuitDataEventReader& eventReader)
{
	FUNCTION_ENTRY("onIncomingCircuitData");

    std::vector<unsigned char> data;
    eventReader.getData( data );

    RadioCircuitTransfer::EXStatus status = RadioCircuitTransfer::XON;

    for( unsigned int i = data.size();
         i > 0;
         i-- )
    {
        if( data[i-1] == 0x11 )  // XOFF is ^Q
        {
            status = RadioCircuitTransfer::XON;
            break;
        }
        else if( data[i-1] == 0x13 ) // XON is ^S
        {
            status = RadioCircuitTransfer::XOFF;
            break;
        }
    }  

    m_radioCircuitModeManager->processIncomingCircuitModeData(
        eventReader.getCallReference(),
        status );

	FUNCTION_EXIT;
}


void Radio::onCircuitDataCapacity(const TA_IRS_App::CircuitDataCapacityEventReader& eventReader)
{
	FUNCTION_ENTRY("onCircuitDataCapacity");

    LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugInfo, "Reference: %d", eventReader.getCallReference() );

    m_radioCircuitModeManager->processIncomingCircuitModeDataCapacity(
        eventReader.getCallReference(), eventReader.getFreeBytes() );

	FUNCTION_EXIT;
}


RadioCircuitModeManager* Radio::getRadioCircuitModeManager()
{
	return m_radioCircuitModeManager;
}


/**
* This method will handle changes to radio fall back mode.  Some functions will
* become unavailable therefore applications must be notified.  An alarm should
* be raised/closed to alert the operator.
*/
void Radio::onRadioFallback(bool isFallback, EFallbackReason fallbackReason)
{
	FUNCTION_ENTRY("onRadioFallback");

    LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugInfo, 
         "Received Notification of RadioFallback [%s] (Currently %s)", (isFallback)?"Fallback":"Normal", (m_inFallback)?"Fallback":"Normal");

    // only trigger activities if we haven't already
    if ( m_inFallback != isFallback )
    {
        m_inFallback = isFallback;

		setDpServerFallback(m_inFallback);

		if (m_inFallback) // TD9023
		{
			TA_Base_Core::DescriptionParameters descriptionParameters;
			m_callback.submitAlarm(TA_Base_Core::RadioAlarms::RadioFallbackModeAlarm,descriptionParameters);
		}
		else // add closeAlarm() in IRadioCallback
		{
			m_callback.closeAlarm(TA_Base_Core::RadioAlarms::RadioFallbackModeAlarm);	
		}

        // If we came here via a systemError, we're supposed to detach and
        // re-login with fallback state
        if (fallbackReason==fbUnsolicited)
        {
            // reset the connection entering or leaving fallback

            LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugInfo, 
                 "Unsolicited Notification of RadioFallback. Resetting connection");
            //
            // TODO: find out if we should terminate on-going calls that
            // haven't been terminated automatically by the RCS
            resetConnection();
        }
    }
    
    if (fallbackReason==fbSessionLogin)
    {
        // this tells the TrainAgent
        m_callback.onRadioFallback(isFallback);

        // Can't think of anything else that needs doing here that hasn't
        // already been done in the RadioSession class.
        // Do we need to alert session-aware entities
        // (CallBanner, RadioManager, RadioMonitor) ?
        LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugInfo, 
            "SessionLogin Notification of RadioFallback (no additional action taken)");
    }

	FUNCTION_EXIT;
}


void Radio::addBackgroundTask(RadioTaskPtr task)
{
    m_backgroundProcessor->addTask(task);
}

void Radio::addQueuedBackgroundTask(RadioTaskPtr task)
{
	m_backgroudQueueProcessor->insert(task);
}

void Radio::setDirectoryCallback(IRadioDirectoryCallback * directoryCallback)
{
    if (m_directoryCallback != 0)
    {
        LOG( SourceInfo, TA_Base_Core::DebugUtil::GenericLog, TA_Base_Core::DebugUtil::DebugInfo, 
             "Overwriting previously registered Directory Callback");
    }

    m_directoryCallback = directoryCallback;
}


void Radio::applyFullState(const RadioType& state)
{
	{
		TA_Base_Core::ThreadGuard guard(m_callStackLock);

		RadioTcpServerArray::const_iterator it;

		for ( it = m_radioTcpServers.begin(); it != m_radioTcpServers.end(); it ++ )
		{
			RadioType::const_iterator itr = state.find( (*it)->getServerIndex() );

			if ( itr != state.end() )
			{
				LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugInfo, "Radio::applyFullState on TcpServer %d", (*it)->getServerIndex() );
				(*it)->applyFullState( itr->second );
			}
		}
	}
}

void Radio::clearFullState()
{
    {
        TA_Base_Core::ThreadGuard guard(m_callStackLock);
        
		RadioTcpServerArray::const_iterator it;

		for (   it = m_radioTcpServers.begin();
				it != m_radioTcpServers.end();
				it++)
		{
			(*it)->clearFullState();
		}
    }
}

void Radio::getFullState(RadioType& state)
{
	FUNCTION_ENTRY("getFullState");

    {
        
        RadioTcpServerArray::const_iterator it;
        // get all the calls from the stack
        state.clear();

		for ( it = m_radioTcpServers.begin(); it != m_radioTcpServers.end(); it ++ )
		{
			TcpServerType serverType;
			(*it)->getFullState( serverType );
			state.insert( std::pair< ServerIndex, TcpServerType >( (*it)->getServerIndex(), serverType ) );
		}

    }

	//get Full state of the Subscriber Monitor Manager
#if defined MONITOR_STATEUPDATE_BROKEN_BY_TD17613
    // TODO: move to RadioTcpServer, use m_subscriberMonitor
    //m_radioMonitorManager->getFullState(state.radioMonitorManager);
#endif // #if defined MONITOR_STATEUPDATE_BROKEN_BY_TD17613
	//get Full state of the Authorisation Manager
	// TODO: broken by TD15273
    // m_radioAuthorisationManager->getFullState(state.radioAuthorisationManager);



	FUNCTION_EXIT;
}

void Radio::updateCallInRadioCallStack(const CallDetailsType& callDetails)
{
    // find the appropriate RadioTcpServer to delegate to
    ConsoleToSessionServerMap::iterator fndC2ss = m_consoleSessionServers.find(callDetails.consoleID);
	if(fndC2ss == m_consoleSessionServers.end())
	{
		return;
	}

	ServerIndex srvIdx = fndC2ss->second.second;
	for ( RadioTcpServerArray::iterator iter = m_radioTcpServers.begin() ;
		  iter != m_radioTcpServers.end() ;
		  iter++)
	{
		if((*iter)->getServerIndex() == srvIdx)
		{
			(*iter)->updateCallInRadioCallStack(callDetails);
			return;
		}
	}

}

//
// state synchronisation 
// TODO: rename this to indicate its state-sync-ness
void Radio::removeCallFromRadioCallStack(CallID callID,  ta_uint32  consoleID)
{
    // find the appropriate RadioTcpServer to delegate to
    ConsoleToSessionServerMap::iterator fndC2ss = m_consoleSessionServers.find(consoleID);
	if(fndC2ss == m_consoleSessionServers.end())
	{
		return;
	}

	ServerIndex srvIdx = fndC2ss->second.second;
	for ( RadioTcpServerArray::iterator iter = m_radioTcpServers.begin() ;
		  iter != m_radioTcpServers.end() ;
		  iter++)
	{
		if((*iter)->getServerIndex() == srvIdx)
		{
			(*iter)->removeCallFromRadioCallStack(callID);
			return;
		}
	}
}

bool Radio::inFallback() const
{
    return m_inFallback;
}


void Radio::resetConnection()
{

    // delegate to individual tcpservers. Since this only happens at station
    // BaseStations, this is unlikely to affect more than one tcpserver, but
    // that's over-engineering for you.
    for ( RadioTcpServerArray::iterator iter = m_radioTcpServers.begin() ;
          iter != m_radioTcpServers.end() ;
          iter++)
    {
        (*iter)->resetConnection();
    }


}

std::string Radio::getFallbackReplacementString()
{
    // first time, get the string.
    if ( m_fallbackReplacementString.empty() )
    {
        // retrieve from runtime parameters if possible
        m_fallbackReplacementString = TA_Base_Core::RunParams::getInstance().get("FallbackReplacementString");

        // otherwise, a default is imperative
        if ( m_fallbackReplacementString.empty() )
        {
            m_fallbackReplacementString = "(F)";
        }
    }

    return m_fallbackReplacementString;
}


void Radio::updateRadioMonitoredCallProgression( ta_uint32  monitorReference)
{
#if defined MONITOR_STATEUPDATE
	addMonitor(monitorReference);
//	subscriberActivity();
#endif
}


void Radio::removeMonitoredSubscriberDetails( ta_uint32  monitoredReference, ta_int32 serverIndex)
{
//	m_subscriberMonitor->removeMonitor(monitoredReference);
	RadioTcpServerArray::const_iterator it;
	for (   it = m_radioTcpServers.begin();
			it != m_radioTcpServers.end();
			it++)
	{
		if(serverIndex == (*it)->getServerIndex() )
		{
			(*it)->removeMonitoredSubscriberDetails(monitoredReference);
			break;
		}
	}

}
			
void Radio::updateAudioEntryInSessionMap(SessionID sessionReference, 
								  AudioReference audioReference,
								  const AudioEntryType& audioEntry)
{	


	FUNCTION_ENTRY("updateAudioEntryInSessionMap");

	RadioTcpServerArray::const_iterator it;
	for (   it = m_radioTcpServers.begin();
			it != m_radioTcpServers.end();
			it++)
	{
		LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugInfo, "Radio::updateAudioEntryInSessionMap on TcpServer %d", (*it)->getServerIndex() );
		(*it)->updateAudioEntryInSessionMap(sessionReference, 
  										    audioReference,
											audioEntry);
	}

	FUNCTION_EXIT;
}

void Radio::updateRadioResourceManagerVars(SessionID sessionReference, CallReference callReference,
										   int currentVolume, ta_int32 serverIndex)
{	
	FUNCTION_ENTRY("updateRadioResourceManagerVars");

	RadioTcpServerArray::const_iterator it;
	for (   it = m_radioTcpServers.begin();
			it != m_radioTcpServers.end();
			it++)
	{
		if(serverIndex == (*it)->getServerIndex())
		{
			(*it)->updateRadioResourceManagerVars(sessionReference, callReference, currentVolume);
			break;
		}
	}

	FUNCTION_EXIT;
}

void Radio::updateAuthorisationRequest(const AuthorisationRequestType& authorisationRequest, ta_int32 serverIndex)
{ 
	FUNCTION_ENTRY("updateAuthorisationRequest");

	//this->m_radioAuthorisationManager->updateAuthorisationRequest(authorisationRequest);

	RadioTcpServerArray::const_iterator it;
	for (   it = m_radioTcpServers.begin();
			it != m_radioTcpServers.end();
			it++)
	{
		if(serverIndex == (*it)->getServerIndex() )
		{
			(*it)->updateAuthorisationRequest(authorisationRequest);
			break;
		}
	}

	FUNCTION_EXIT;
}
	
	
void Radio::removeAuthorisationRequest(CallID callID, ta_int32 serverIndex)
{
	FUNCTION_ENTRY("removeAuthorisationRequest");

	//this->m_radioAuthorisationManager->removeAuthorisationRequest(callID);

	RadioTcpServerArray::const_iterator it;
	for (   it = m_radioTcpServers.begin();
			it != m_radioTcpServers.end();
			it++)
	{
		if(serverIndex == (*it)->getServerIndex() )
		{
			(*it)->removeAuthorisationRequest(callID);
			break;
		}
	}


	FUNCTION_EXIT;

}


void Radio::addSessionServerConsole(SessionReference sessionRef, ServerIndex svrIdx, ConsoleID consoleID)
{
    TA_Base_Core::ThreadGuard sscMapGuard(m_sscMapLock);

    SessionServerIndex ssi(sessionRef,svrIdx);

    // check if the ssi is in the map yet

    // otherwise just add the blessed thing
    m_consoleSessionServers[consoleID] = ssi;
}

void Radio::onConnectionFailed(ServerIndex svrIdx)
{
	FUNCTION_ENTRY("onConnectionFailed");

    // each server raises the alarm via the IRadioCallback
    
	//setDpServerLostConnection(svrIdx, true);
    //
    // notify the directory callback but only if the connection that has
    // failed is that of the ISCS RadioSession.
    if (m_directoryCallback != 0)
    {
        if (m_ISCSRadioSession->getTcpServer().getServerIndex() == svrIdx)
        {
            m_directoryCallback->onConnectionLost();
        }
    }

	FUNCTION_EXIT;
}

void Radio::onSwitchConnection(ServerIndex svrIdx)
{
	FUNCTION_ENTRY("onSwitchConnection");

    if (m_directoryCallback != 0)
    {
        if (m_ISCSRadioSession->getTcpServer().getServerIndex() == svrIdx)
        {
            m_directoryCallback->onSwitchConnection();
        }
    }

	FUNCTION_EXIT;
}

void Radio::onConnectionResumed(ServerIndex svrIdx)
{
	FUNCTION_ENTRY("onConnectionResumed");

	//setDpServerLostConnection(svrIdx, false);

    if (m_ISCSRadioSession != 0)
    {
        if (m_ISCSRadioSession->getTcpServer().getServerIndex() == svrIdx)
        {
            if (m_directoryCallback != 0)
            {
                LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugTrace, 
                        "Notifying Directory Callback of connection restored (server index %lu)", svrIdx);
                m_directoryCallback->onConnectionEstablish();
            }
        }
    }

	FUNCTION_EXIT;
}



RadioTcpServer * Radio::getAudioLinkServer(unsigned int audioLinkServerId)
{
    // if the requested server id is out of range, we just return null and
    // expect the client function to deal with that consequence
    if (m_radioTcpServers.size()>=(audioLinkServerId+1))
    {
        return m_radioTcpServers[audioLinkServerId];
    }

    return 0;
}

void Radio::removeSessionFromAudioMap(SessionID sessionReference, ta_int32 serverIndex)
{
	RadioTcpServerArray::const_iterator it;
	for (   it = m_radioTcpServers.begin();
			it != m_radioTcpServers.end();
			it++)
	{
		if(serverIndex == (*it)->getServerIndex() )
		{
			(*it)->removeSessionFromAudioMap(sessionReference);
			break;
		}
	}
}
TA_Base_Bus::IRadioCorbaDef::SpeedDialList* Radio::getSpeedDialSet(const std::string& setName)
{
	FUNCTION_ENTRY("getSpeedDialSet");
	// Get the speed dial list from the database
	std::vector<TA_Base_Core::IRASpeedDialButton*> dialList = 
		TA_Base_Core::RASpeedDialButtonAccessFactory::getInstance().getSpeedDialSetByName(setName);
	
	// Create the speed dial list for returning.
	TA_Base_Bus::IRadioCorbaDef::SpeedDialList* c_dialList = 
		new TA_Base_Bus::IRadioCorbaDef::SpeedDialList();
	
	// Set it's length (it's a CORBA sequence, and as such needs its length specifed, because
	// sequences don't automatically increase in size)
	c_dialList->length(dialList.size());
	
	// Now put the data from the IRASubscribers into the SubscriberDetails objects in the CORBA sequence
	for (unsigned int i = 0;i < dialList.size();i++)
	{
		(*c_dialList)[i].label    = dialList[i]->getButtonLabel().c_str();
		(*c_dialList)[i].TSI      = dialList[i]->getButtonTSI().c_str();
		(*c_dialList)[i].position = static_cast<unsigned char>(dialList[i]->getButtonPosition());
		
		// And delete the database member while we're here
		delete dialList[i];
		dialList[i] = NULL;
	}
	
	FUNCTION_EXIT;
	return c_dialList;
}

void Radio::updateSpeedDialSet(const TA_Base_Bus::IRadioCorbaDef::SpeedDialSet& setDetails, const std::string& sessionID)
{
	FUNCTION_ENTRY("updateSpeedDialSet");
	// 1. Attempt to retrieve existing record (we don't pass setID through Corba)
	 ta_uint32  setKey = ULONG_MAX;
	try
	{        
		RASpeedDialSet findSet(std::string(setDetails.setName));
		findSet.getSetName();
		setKey = findSet.getKey();
	}
	catch(DataException& ex)
	{
		if (ex.getFailType() != DataException::NO_VALUE)
		{
			throw TA_Base_Bus::IRadioCorbaDef::invalidSpeedDialSetException();
		}
	}
	
	// By here, we should either have setKey == ULONG_MAX to indicate new record
	// or, setKey == valid key in database. Note: zero is invalid !!!
	TA_ASSERT(0 != setKey,"Key was 0");
	
	// 2. Update the record in database (method decides whether to update or insert)
	RASpeedDialSet mySet(
		setKey, 
		setDetails.isSystem,
		setDetails.operatorID, 
		setDetails.profileID, 
		std::string(setDetails.setName),
		true // new record flag
		);
	mySet.applyChanges(); 
	mySet.getSetName(); // trigger reload
	
	FUNCTION_EXIT;
}


void Radio::updateSpeedDial(const std::string& setName, const TA_Base_Bus::IRadioCorbaDef::SpeedDialEntry& newEntry, const std::string& sessionID)
{
     FUNCTION_ENTRY("updateSpeedDial");

      // Determine the key of the set in which this button is located. The set must exist before a button can be added to it.
         ta_uint32  setKey = ULONG_MAX;
		//libo
		char sProfileID[9] = {0};
		std::string   setNameTemp=setName;
		if(setName == "User")
		{
			TA_Base_Bus::AuthenticationLibrary authLibrary;
			TA_Base_Bus::SessionInfo sessionInfo = authLibrary.getSessionInfo(sessionID,sessionID);
			int nProfileId = sessionInfo.ProfileId[0];
			sprintf( sProfileID, "_%d", nProfileId );
			setNameTemp +=  sProfileID;
		}
		//libo
        try
        {        
            RASpeedDialSet findSet(setNameTemp);
            findSet.getSetName();
            setKey = findSet.getKey();
        }
        catch(DataException&)
        {
            IRASpeedDialSet* dialSet = RASpeedDialSet::createNewSetByName(setNameTemp);
            dialSet->setSystem(false);
            // TODO: Don't leave this as a constant...
            if (setName == "User")
            {
                try
                {
                    TA_Base_Bus::AuthenticationLibrary authLibrary;

                    TA_Base_Bus::SessionInfo sessionInfo = authLibrary.getSessionInfo(sessionID,sessionID);
                    dialSet->setProfileId(sessionInfo.ProfileId[0]);
                }
                catch(...)
                {
                    throw TA_Base_Bus::IRadioCorbaDef::invalidSpeedDialSetException();
                }                
            }
            dynamic_cast<RASpeedDialSet*>(dialSet)->applyChanges();

            setKey = dialSet->getKey();

            delete dialSet;
            dialSet = NULL;
        }
        if (ULONG_MAX == setKey)
        {
            throw TA_Base_Bus::IRadioCorbaDef::invalidSpeedDialSetException();
        }

        // 2. Now find out if this button already exists. To do that, iterate through the list of all speed dial buttons.
        std::vector<TA_Base_Core::IRASpeedDialButton*> dialList = 
            TA_Base_Core::RASpeedDialButtonAccessFactory::getInstance().getSpeedDialSetByName(setNameTemp);
        std::vector<TA_Base_Core::IRASpeedDialButton*>::iterator i = std::find_if(dialList.begin(), dialList.end(),
            RASpeedDialButton::compareByButtonPosition(newEntry.position));

        try
        {
            // If the button currently exists...
            if (dialList.end() != i) 
            {
                // 3. If newEntry.label blank, delete this record
                if (strlen(newEntry.label)<1)
                {
                    TA_Base_Core::RASpeedDialButtonAccessFactory::getInstance().deleteSpeedDialButton(*i);
                }
                else
                {
                    // And if not, update the button details
					TA_Base_Core::RASpeedDialButton* speedDialButton = reinterpret_cast<TA_Base_Core::RASpeedDialButton*>(*i);
					TA_ASSERT(speedDialButton!=NULL,"Cannot access implementation of speed dial");
                    speedDialButton->setButtonLabel(std::string(newEntry.label));
                    speedDialButton->setButtonTSI(std::string(newEntry.TSI));
					speedDialButton->applyChanges();
                }
            }
            else
            {
                // It's a new button.
                 ta_uint32  buttonID = ULONG_MAX;

                // create the button object, and apply changes
                RASpeedDialButton myButton(
                    buttonID, 
                    setKey,
                    newEntry.position, 
                    std::string(newEntry.label), 
                    std::string(newEntry.TSI),
                    true // new record flag
                    );
                myButton.applyChanges(); 
                myButton.getButtonLabel(); // trigger reload
            }
        }
        catch(...)
        {
            // Only catching here to clean up - dont' actually care what type of exception it is.
            for (unsigned int i = 0;i < dialList.size();i++)
            {
                delete dialList[i];
                dialList[i] = NULL;
            }
            // Rethrow
            throw;
        }

        // If no exception, still need to clean up...
        for (i = dialList.begin();i != dialList.end();i++)
        {
            delete (*i);
            (*i) = NULL;
        }


        FUNCTION_EXIT;
}

std::string Radio::getUserSetName(const std::string& sessionID)
{
	FUNCTION_ENTRY("getUserSetName");
	
	try
	{
		TA_Base_Bus::AuthenticationLibrary authLibrary;
		
		TA_Base_Bus::SessionInfo sessionInfo = authLibrary.getSessionInfo(sessionID,sessionID);
		
		IRASpeedDialSet* set = TA_Base_Core::RASpeedDialSetAccessFactory::getInstance().getRASpeedDialSetByProfile(sessionInfo.ProfileId[0]);
		
		return set->getSetName();
	}
	catch(...)
	{
		return "";
	}
}


//************************************
// IRadioDirectory Interface Methods *
//************************************

    TA_Base_Bus::IRadioCorbaDef::SubscriberList* Radio::getGroupSubscribers()
    {
        FUNCTION_ENTRY("getGroupSubscribers");
        // Get the subscribers list from the database
        std::vector<TA_Base_Core::IRASubscribers*> groups = 
            TA_Base_Core::RAGroupMembersAccessFactory::getInstance().getGroupSubscribers();

        // Create the subscriber list for returning.
        TA_Base_Bus::IRadioCorbaDef::SubscriberList* groupSubscribers = 
            new TA_Base_Bus::IRadioCorbaDef::SubscriberList();

        // Set it's length (it's a CORBA sequence, and as such needs its length specifed, because
        // sequences don't automatically increase in size)
        groupSubscribers->length(groups.size());

        // Now put the data from the IRASubscribers into the SubscriberDetails objects in the CORBA sequence
        for (unsigned int i = 0;i < groups.size();i++)
        {
            (*groupSubscribers)[i].TSI = groups[i]->getTSI().c_str();
            (*groupSubscribers)[i].subscriberName = groups[i]->getSubscriberName().c_str();
            (*groupSubscribers)[i].locationName = groups[i]->getLocation().c_str();
            (*groupSubscribers)[i].locationKey = groups[i]->getLocationKey();
            (*groupSubscribers)[i].type = TA_Base_Bus::IRadioCorbaDef::GROUP_SUBSCRIBER;

            // And delete the database member while we're here
            delete groups[i];
            groups[i] = NULL;
        }

        FUNCTION_EXIT;
        return groupSubscribers;
    }

    TA_Base_Bus::IRadioCorbaDef::SubscriberList* Radio::getPatchSubscribers()
    {
        FUNCTION_ENTRY("getPatchSubscribers");
        // Get the subscribers list from the database
        std::vector<TA_Base_Core::IRASubscribers*> patches = 
            TA_Base_Core::RAPatchMembersAccessFactory::getInstance().getPatchSubscribers();

        // Create the subscriber list for returning.
        TA_Base_Bus::IRadioCorbaDef::SubscriberList* patchSubscribers = 
            new TA_Base_Bus::IRadioCorbaDef::SubscriberList();

        // Set it's length (it's a CORBA sequence, and as such needs its length specifed, because
        // sequences don't automatically increase in size)
        patchSubscribers->length(patches.size());

        // Now put the data from the IRASubscribers into the SubscriberDetails objects in the CORBA sequence
        for (unsigned int i = 0;i < patches.size();i++)
        {
            (*patchSubscribers)[i].TSI = patches[i]->getTSI().c_str();
            (*patchSubscribers)[i].subscriberName = patches[i]->getSubscriberName().c_str();
            (*patchSubscribers)[i].locationName = patches[i]->getLocation().c_str();
            (*patchSubscribers)[i].locationKey = patches[i]->getLocationKey();
            (*patchSubscribers)[i].type = TA_Base_Bus::IRadioCorbaDef::PATCH_SUBSCRIBER;

            // And delete the database member while we're here
            delete patches[i];
            patches[i] = NULL;
        }

        FUNCTION_EXIT;
        return patchSubscribers;
    }

    TA_Base_Bus::IRadioCorbaDef::SubscriberList* Radio::getIndividualSubscribers()
    {
        FUNCTION_ENTRY("getIndividualSubscribers");
        // Get the subscribers list from the database
        std::vector<TA_Base_Core::IRASubscribers*> individuals = 
            TA_Base_Core::RASubscribersAccessFactory::getInstance().getIndividualSubscribers();

        // Create the subscriber list for returning.
        TA_Base_Bus::IRadioCorbaDef::SubscriberList* individualSubscribers = 
            new TA_Base_Bus::IRadioCorbaDef::SubscriberList();

        // Set it's length (it's a CORBA sequence, and as such needs its length specifed, because
        // sequences don't automatically increase in size)
        individualSubscribers->length(individuals.size());

        // Now put the data from the IRASubscribers into the SubscriberDetails objects in the CORBA sequence
        for (unsigned int i = 0;i < individuals.size();i++)
        {
            (*individualSubscribers)[i].TSI = individuals[i]->getTSI().c_str();
            (*individualSubscribers)[i].subscriberName = individuals[i]->getSubscriberName().c_str();
            (*individualSubscribers)[i].locationName = individuals[i]->getLocation().c_str();
            (*individualSubscribers)[i].locationKey = individuals[i]->getLocationKey();
            (*individualSubscribers)[i].type = TA_Base_Bus::IRadioCorbaDef::INDIVIDUAL_SUBSCRIBER;

            // And delete the database member while we're here
            delete individuals[i];
            individuals[i] = NULL;
        }

        FUNCTION_EXIT;
        return individualSubscribers;
    }

    TA_Base_Bus::IRadioCorbaDef::SubscriberDetails* Radio::getSubscriberDetails(const std::string& TSI)
    {
        FUNCTION_ENTRY("getSubscriberDetails");
        // Get the subscribers details from the database
        TA_Base_Core::IRASubscribers* subscriber = 
            TA_Base_Core::RASubscribersAccessFactory::getInstance().getSubscriberDetails(TSI);

        // Create the subscriber list for returning.
        TA_Base_Bus::IRadioCorbaDef::SubscriberDetails* subscriberDetails = 
            new TA_Base_Bus::IRadioCorbaDef::SubscriberDetails();

        subscriberDetails->TSI = CORBA::string_dup(subscriber->getTSI().c_str());
        subscriberDetails->subscriberName = CORBA::string_dup(subscriber->getSubscriberName().c_str());
        subscriberDetails->locationName = CORBA::string_dup(subscriber->getLocation().c_str());
        subscriberDetails->locationKey = subscriber->getLocationKey();
		subscriberDetails->ownerTSI = CORBA::string_dup("");
        IRASubscribers::SubscriberType type = subscriber->getSubscriberType();

        switch(type)
        {
        case IRASubscribers::DISPATCHER:
            {
				subscriberDetails->type = TA_Base_Bus::IRadioCorbaDef::INDIVIDUAL_SUBSCRIBER;
                break;
            }
        case IRASubscribers::GROUP:
            {
                subscriberDetails->type = TA_Base_Bus::IRadioCorbaDef::GROUP_SUBSCRIBER;
                break;
            }
        case IRASubscribers::MOBILE:
            {
				subscriberDetails->type = TA_Base_Bus::IRadioCorbaDef::INDIVIDUAL_SUBSCRIBER;
                break;
            }
        case IRASubscribers::PATCH_GROUP:
            {
                subscriberDetails->type = TA_Base_Bus::IRadioCorbaDef::PATCH_SUBSCRIBER;
                break;
            }
        case IRASubscribers::INDIVIDUAL:
            {
                subscriberDetails->type = TA_Base_Bus::IRadioCorbaDef::INDIVIDUAL_SUBSCRIBER;
                break;
            }
		default:
		{
			subscriberDetails->type = TA_Base_Bus::IRadioCorbaDef::INDIVIDUAL_SUBSCRIBER;
			break;
		}
        }

        // And delete the database member while we're here
        delete subscriber;
        subscriber = NULL;

        FUNCTION_EXIT;
        return subscriberDetails;
    }

    TA_Base_Bus::IRadioCorbaDef::SubscriberList* Radio::getGroupMembers(const std::string& TSI)
    {
        FUNCTION_ENTRY("getGroupMembers");
        // Get the subscribers list from the database
        TA_Base_Core::RAGroupMembersAccessFactory::GroupMembersType groupMembers = 
            TA_Base_Core::RAGroupMembersAccessFactory::getInstance().getGroupMembers(TSI);

        // Create the subscriber list for returning.
        TA_Base_Bus::IRadioCorbaDef::SubscriberList* groupMembersList = 
            new TA_Base_Bus::IRadioCorbaDef::SubscriberList();

        // Set it's length (it's a CORBA sequence, and as such needs its length specifed, because
        // sequences don't automatically increase in size)
        groupMembersList->length(groupMembers.second.size());

        // Now put the data from the IRASubscribers into the SubscriberDetails objects in the CORBA sequence
        for (unsigned int i = 0;i < groupMembers.second.size();i++)
        {
            (*groupMembersList)[i].TSI = groupMembers.second[i]->getTSI().c_str();
            (*groupMembersList)[i].subscriberName = groupMembers.second[i]->getSubscriberName().c_str();
            (*groupMembersList)[i].locationName = groupMembers.second[i]->getLocation().c_str();
            (*groupMembersList)[i].locationKey = groupMembers.second[i]->getLocationKey();
            (*groupMembersList)[i].type = TA_Base_Bus::IRadioCorbaDef::INDIVIDUAL_SUBSCRIBER;

            // And delete the database member while we're here
            delete groupMembers.second[i];
            groupMembers.second[i] = NULL;
        }

        FUNCTION_EXIT;
        return groupMembersList;
    }

    TA_Base_Bus::IRadioCorbaDef::SubscriberList* Radio::getPatchMembers(const std::string& TSI)
    {
        FUNCTION_ENTRY("getPatchMembers");
        // Get the subscribers list from the database
        TA_Base_Core::RAPatchMembersAccessFactory::PatchMembersType patchMembers = 
            TA_Base_Core::RAPatchMembersAccessFactory::getInstance().getPatchMembers(TSI);

        // Create the subscriber list for returning.
        TA_Base_Bus::IRadioCorbaDef::SubscriberList* patchMembersList = 
            new TA_Base_Bus::IRadioCorbaDef::SubscriberList();

        // Set it's length (it's a CORBA sequence, and as such needs its length specifed, because
        // sequences don't automatically increase in size)
        patchMembersList->length(patchMembers.second.size());

        // Now put the data from the IRASubscribers into the SubscriberDetails objects in the CORBA sequence
        for (unsigned int i = 0;i < patchMembers.second.size();i++)
        {
            (*patchMembersList)[i].TSI = patchMembers.second[i]->getTSI().c_str();
            (*patchMembersList)[i].subscriberName = patchMembers.second[i]->getSubscriberName().c_str();
            (*patchMembersList)[i].locationName = patchMembers.second[i]->getLocation().c_str();
            (*patchMembersList)[i].locationKey = patchMembers.second[i]->getLocationKey();
            (*patchMembersList)[i].type = TA_Base_Bus::IRadioCorbaDef::GROUP_SUBSCRIBER;

            // And delete the database member while we're here
            delete patchMembers.second[i];
            patchMembers.second[i] = NULL;
        }

        FUNCTION_EXIT;
        return patchMembersList;
    }

    TA_Base_Bus::IRadioCorbaDef::SubscriberList* Radio::searchSubscriber(const std::string& searchText)
    {
        FUNCTION_ENTRY("searchSubscriber");
        // Get the subscribers list from the database
        std::vector<TA_Base_Core::IRASubscribers*> subscribers = 
            TA_Base_Core::RASubscribersAccessFactory::getInstance().searchSubscribers(searchText);

		LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugDebug, "[search]: Search subscribers return %d match records.",subscribers.size());

        // Create the subscriber list for returning.
        TA_Base_Bus::IRadioCorbaDef::SubscriberList* subscriberList = 
            new TA_Base_Bus::IRadioCorbaDef::SubscriberList();

        // Set it's length (it's a CORBA sequence, and as such needs its length specifed, because
        // sequences don't automatically increase in size)
        subscriberList->length(subscribers.size());

        // Now put the data from the IRASubscribers into the SubscriberDetails objects in the CORBA sequence
        for (unsigned int i = 0;i < subscribers.size();i++)
        {
			LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugDebug, 
						"[search]:search subscribers: TSI[%d] = %s,\
						subscribername[%d]=%s,location[%d]=%s.",i,subscribers[i]->getTSI().c_str(),i,subscribers[i]->getSubscriberName().c_str(),i,subscribers[i]->getLocation().c_str());

            (*subscriberList)[i].TSI = CORBA::string_dup(subscribers[i]->getTSI().c_str());
            (*subscriberList)[i].subscriberName = CORBA::string_dup(subscribers[i]->getSubscriberName().c_str());
            (*subscriberList)[i].locationName = CORBA::string_dup(subscribers[i]->getLocation().c_str());
            (*subscriberList)[i].locationKey = subscribers[i]->getLocationKey();
            IRASubscribers::SubscriberType type = subscribers[i]->getSubscriberType();

            switch(type)
            {
            case IRASubscribers::DISPATCHER:
                {
					(*subscriberList)[i].type = TA_Base_Bus::IRadioCorbaDef::INDIVIDUAL_SUBSCRIBER;
                    break;
                }
            case IRASubscribers::GROUP:
                {
                    (*subscriberList)[i].type = TA_Base_Bus::IRadioCorbaDef::GROUP_SUBSCRIBER;
                    break;
                }
            case IRASubscribers::MOBILE:
                {
					(*subscriberList)[i].type = TA_Base_Bus::IRadioCorbaDef::INDIVIDUAL_SUBSCRIBER;
                    break;
                }
            case IRASubscribers::PATCH_GROUP:
                {
                    (*subscriberList)[i].type = TA_Base_Bus::IRadioCorbaDef::PATCH_SUBSCRIBER;
                    break;
                }
            case IRASubscribers::INDIVIDUAL:
                {
                    (*subscriberList)[i].type = TA_Base_Bus::IRadioCorbaDef::INDIVIDUAL_SUBSCRIBER;
                    break;
                }
			default:
			{
				(*subscriberList)[i].type = TA_Base_Bus::IRadioCorbaDef::INDIVIDUAL_SUBSCRIBER;
				break;
			}
            }

            // And delete the database member while we're here
            delete subscribers[i];
            subscribers[i] = NULL;
        }

        FUNCTION_EXIT;
        return subscriberList;
    }

	TA_Base_Bus::IRadioCorbaDef::SubscriberList* Radio::getAllSubscribers()
	{
		FUNCTION_ENTRY("getAllSubscribers()");

		// Get the subscribers list from the database
		std::vector<TA_Base_Core::IRASubscribers*> subscribers =
			TA_Base_Core::RASubscribersAccessFactory::getInstance().getAllSubscribers();

		// Create the subscriber list for returning.
		TA_Base_Bus::IRadioCorbaDef::SubscriberList* subscribersList =
			new TA_Base_Bus::IRadioCorbaDef::SubscriberList();

		// Set it's length (it's a CORBA sequence, and as such needs its length specifed, because
		// sequences don't automatically increase in size)
		subscribersList->length(subscribers.size());

		// Now put the data from the IRASubscribers into the SubscriberDetails objects in the CORBA sequence
		for (unsigned int i = 0; i < subscribers.size(); i++)
		{
			(*subscribersList)[i].TSI = subscribers[i]->getTSI().c_str();
			(*subscribersList)[i].subscriberName = subscribers[i]->getSubscriberName().c_str();
			(*subscribersList)[i].locationName = subscribers[i]->getLocation().c_str();
			(*subscribersList)[i].locationKey = subscribers[i]->getLocationKey();
			(*subscribersList)[i].ownerTSI = subscribers[i]->getOwner().c_str();

			IRASubscribers::SubscriberType type = subscribers[i]->getSubscriberType();

			switch (type)
			{
			case IRASubscribers::DISPATCHER:
			{
				(*subscribersList)[i].type = TA_Base_Bus::IRadioCorbaDef::DISPATCHER_SUBSCRIBER;
				break;
			}
			case IRASubscribers::GROUP:
			{
				(*subscribersList)[i].type = TA_Base_Bus::IRadioCorbaDef::GROUP_SUBSCRIBER;
				break;
			}
			case IRASubscribers::MOBILE:
			{
				(*subscribersList)[i].type = TA_Base_Bus::IRadioCorbaDef::MOBILE_SUBSCRIBER;
				break;
			}
			case IRASubscribers::PATCH_GROUP:
			{
				(*subscribersList)[i].type = TA_Base_Bus::IRadioCorbaDef::PATCH_SUBSCRIBER;
				break;
			}
			case IRASubscribers::INDIVIDUAL:
			{
				(*subscribersList)[i].type = TA_Base_Bus::IRadioCorbaDef::INDIVIDUAL_SUBSCRIBER;
				break;
			}
			default:
				(*subscribersList)[i].type = TA_Base_Bus::IRadioCorbaDef::INDIVIDUAL_SUBSCRIBER;
				break;
			}
			//LOG_GENERIC(SourceInfo, TA_Base_Core::DebugUtil::DebugInfo, "getAllSubscribers: corba=%s, interface=%s", (*subscribersList)[i].type, subscribers[i]->getSubscriberType());
			// And delete the database member while we're here
			delete subscribers[i];
			subscribers[i] = NULL;
		}

		FUNCTION_EXIT;
		return subscribersList;
	}

	TA_Base_Bus::IRadioCorbaDef::GroupList* Radio::getAllGroups()
	{
		FUNCTION_ENTRY("getAllGroups()");

		// Get the subscribers list from the database
		std::vector<TA_Base_Core::IRAGroupMembers*> groups =
			TA_Base_Core::RAGroupMembersAccessFactory::getInstance().getAllGroups();

		// Create the subscriber list for returning.
		TA_Base_Bus::IRadioCorbaDef::GroupList* groupList =
			new TA_Base_Bus::IRadioCorbaDef::GroupList();

		// Set it's length (it's a CORBA sequence, and as such needs its length specifed, because
		// sequences don't automatically increase in size)
		groupList->length(groups.size());

		// Now put the data from the IRASubscribers into the SubscriberDetails objects in the CORBA sequence
		for (unsigned int i = 0; i < groups.size(); i++)
		{
			(*groupList)[i].groupTSI = groups[i]->getGroupTSI().c_str();
			(*groupList)[i].memberTSI = groups[i]->getMemberTSI().c_str();

			
			// And delete the database member while we're here
			delete groups[i];
			groups[i] = NULL;
		}

		FUNCTION_EXIT;
		return groupList;
	}

	TA_Base_Bus::IRadioCorbaDef::PatchList* Radio::getAllPatches()
	{
		FUNCTION_ENTRY("getAllPatches()");

		// Get the subscribers list from the database
		std::vector<TA_Base_Core::IRAPatchMembers*> patches =
			TA_Base_Core::RAPatchMembersAccessFactory::getInstance().getAllPatches();

		// Create the subscriber list for returning.
		TA_Base_Bus::IRadioCorbaDef::PatchList* patchList =
			new TA_Base_Bus::IRadioCorbaDef::PatchList();

		// Set it's length (it's a CORBA sequence, and as such needs its length specifed, because
		// sequences don't automatically increase in size)
		patchList->length(patches.size());

		// Now put the data from the IRASubscribers into the SubscriberDetails objects in the CORBA sequence
		for (unsigned int i = 0; i < patches.size(); i++)
		{
			(*patchList)[i].patchTSI = patches[i]->getPatchTSI().c_str();
			(*patchList)[i].groupTSI = patches[i]->getGroupTSI().c_str();


			// And delete the database member while we're here
			delete patches[i];
			patches[i] = NULL;
		}

		FUNCTION_EXIT;
		return patchList;
	}

	TA_Base_Core::IRASubscribers::SubscriberType Radio::getSubscriberType(TA_Base_Bus::IRadioCorbaDef::SubscriberType type) const
	{
		FUNCTION_ENTRY("getSubscriberType");

		TA_Base_Core::IRASubscribers::SubscriberType subscriberType = TA_Base_Core::IRASubscribers::INVALID;

		switch (type)
		{
		case TA_Base_Bus::IRadioCorbaDef::SubscriberType::INDIVIDUAL_SUBSCRIBER:
		{
			subscriberType = TA_Base_Core::IRASubscribers::INDIVIDUAL;
			break;
		}
		case TA_Base_Bus::IRadioCorbaDef::SubscriberType::GROUP_SUBSCRIBER:
		{
			subscriberType = TA_Base_Core::IRASubscribers::GROUP;
			break;
		}
		case TA_Base_Bus::IRadioCorbaDef::SubscriberType::MOBILE_SUBSCRIBER:
		{
			subscriberType = TA_Base_Core::IRASubscribers::MOBILE;
			break;
		}
		case TA_Base_Bus::IRadioCorbaDef::SubscriberType::PATCH_SUBSCRIBER:
		{
			subscriberType = TA_Base_Core::IRASubscribers::PATCH_GROUP;
			break;
		}
		case TA_Base_Bus::IRadioCorbaDef::SubscriberType::DISPATCHER_SUBSCRIBER:
		{
			subscriberType = TA_Base_Core::IRASubscribers::DISPATCHER;
			break;
		}
		}

		FUNCTION_EXIT;
		return subscriberType;
	}

	void Radio::setAllSubscribers(const TA_Base_Bus::IRadioCorbaDef::SubscriberList& list)
	{
		FUNCTION_ENTRY("setAllSubscribers");

		try
		{
			// Clear all subscriber data
			TA_Base_Core::RASubscribersAccessFactory::getInstance().deleteAllSubscribers();

			// Create the subscribers object...
			IRASubscribers* subscriber;


			for (unsigned int i = 0; i < list.length(); i++)
			{
				TA_Base_Core::IRASubscribers::SubscriberType subscriberType = getSubscriberType(list[i].type);
				if (subscriberType == TA_Base_Core::IRASubscribers::INVALID)
				{
					LOG_GENERIC(SourceInfo, TA_Base_Core::DebugUtil::DebugError, "Invalid subscriber type, not applying changes to subscriber");
				}
				else
				{
					subscriber = new TA_Base_Core::RASubscribers(list[i].TSI.in(),
						list[i].subscriberName.in(),
						subscriberType,
						list[i].locationName.in(),
						list[i].locationKey,
						true,
						list[i].ownerTSI.in());

					// Now that we have the subscriber, simply apply the changes 
					subscriber->applyChanges();

					delete subscriber;
					subscriber = NULL;
				}

			}
		}
		catch (...)
		{

		}
			

		FUNCTION_EXIT;
	}

	void Radio::setAllGroups(const TA_Base_Bus::IRadioCorbaDef::GroupList& list)
	{
		FUNCTION_ENTRY("setAllGroups");

		try
		{
			// Clear all group member data
			TA_Base_Core::RAGroupMembersAccessFactory::getInstance().deleteAllGroups();

			////Create the group object
			//IRASubscribers* groupSubTSI;
			//IRASubscribers* memberSubTSI;


			for (unsigned int i = 0; i < list.length(); i++)
			{
				//groupSubTSI->setTSI(list[i].groupTSI.in());
				//groupSubTSI->setSubscriberType(IRASubscribers::SubscriberType::GROUP);

				//memberSubTSI->setTSI(list[i].memberTSI.in());
				//memberSubTSI->setSubscriberType(IRASubscribers::SubscriberType::PATCH_GROUP);

				TA_Base_Core::RAGroupMembersAccessFactory::getInstance().insertGroup(list[i].groupTSI.in(), list[i].memberTSI.in());
			}
		}
		catch (...)
		{

		}

		FUNCTION_EXIT;
	}

	void Radio::setAllPatches(const TA_Base_Bus::IRadioCorbaDef::PatchList& list)
	{
		FUNCTION_ENTRY("setAllPatches");

		try
		{
			// Clear all patch group data
			TA_Base_Core::RAPatchMembersAccessFactory::getInstance().deleteAllPatch();

			for (unsigned int i = 0; i < list.length(); i++)
			{
				//groupSubTSI->setTSI(list[i].groupTSI.in());
				//groupSubTSI->setSubscriberType(IRASubscribers::SubscriberType::GROUP);

				//memberSubTSI->setTSI(list[i].memberTSI.in());
				//memberSubTSI->setSubscriberType(IRASubscribers::SubscriberType::PATCH_GROUP);

				TA_Base_Core::RAPatchMembersAccessFactory::getInstance().addGroupToPatch(list[i].patchTSI.in(), list[i].groupTSI.in());
			}
		}
		catch (...)
		{

		}

		FUNCTION_EXIT;
	}

	void Radio::setAllSDS(const TA_Base_Bus::IRadioCorbaDef::PredefinedSDSMessageList& list)
	{
		FUNCTION_ENTRY("setAllSDS");

		try
		{
			// Clear all Predefined SDS messages data
			TA_Base_Core::RAPredefinedSDSMessageAccessFactory::getInstance().deleteAllMessages();

			for (unsigned int i = 0; i < list.length(); i++)
			{
				//message->setShortName(list[i].shortName.in());
				//message->setMessage(list[i].message.in());
				TA_Base_Core::RAPredefinedSDSMessageAccessFactory::getInstance().insertSDSMessage(list[i].shortName.in(), list[i].message.in());

			}				
		}
		catch (...)
		{

		}

		FUNCTION_EXIT;
	}

	TA_Base_Bus::IRadioCorbaDef::SelectedCallList* Radio::getList(const char* mft)
	{
		FUNCTION_ENTRY("getList");
		// Get the selected calls list from the database
		std::vector<TA_Base_Core::IRASelectedCall*> call =
			TA_Base_Core::RASelectedCallAccessFactory::getInstance().getList(mft);

		// Create the selected call list for returning.
		TA_Base_Bus::IRadioCorbaDef::SelectedCallList* callList =
			new TA_Base_Bus::IRadioCorbaDef::SelectedCallList();

		// Set it's length (it's a CORBA sequence, and as such needs its length specifed, because
		// sequences don't automatically increase in size)
		callList->length(call.size());

		// Now put the data from the IRASubscribers into the SubscriberDetails struct in the CORBA sequence
		for (unsigned int i = 0; i < call.size(); i++)
		{
			(*callList)[i].tetraID = call[i]->getTetraid().c_str();
			(*callList)[i].callID = call[i]->getID().c_str();
			(*callList)[i].locationName = call[i]->getLocation().c_str();

			// And delete the database member while we're here
			delete call[i];
			call[i] = NULL;
		}
		FUNCTION_EXIT;
		return callList;
	}

	void Radio::addTetraid(const char* mft, const char* tsiNumber, const char* callId, const char* location)
	{
		FUNCTION_ENTRY("addTetraid");

		TA_Base_Core::RASelectedCallAccessFactory::getInstance().addTetraid(mft, tsiNumber, callId, location);

		FUNCTION_EXIT;
	}


	TA_Base_Bus::IRadioCorbaDef::CallStackHistoryList* Radio::getCSHList(const char* profile, ta_uint32 locationKey, bool readWrite)
	{
		FUNCTION_ENTRY("getCSHList");
		// Get the selected calls list from the database
		std::vector<TA_Base_Core::IRACallStackHistory*> callStack =
			TA_Base_Core::RACallStackHistoryAccessFactory::getInstance().getList(profile, locationKey, readWrite);

		// Create the selected call list for returning.
		TA_Base_Bus::IRadioCorbaDef::CallStackHistoryList* callStackList =
			new TA_Base_Bus::IRadioCorbaDef::CallStackHistoryList();

		// Set it's length (it's a CORBA sequence, and as such needs its length specifed, because
		// sequences don't automatically increase in size)
		callStackList->length(callStack.size());

		// Now put the data from the IRACallStackHistory into the CallStackHistory struct in the CORBA sequence
		for (unsigned int i = 0; i < callStack.size(); i++)
		{
			(*callStackList)[i].profile = callStack[i]->getProfileName().c_str();
			(*callStackList)[i].locationKey = callStack[i]->getLocationKey();
			(*callStackList)[i].identifier = callStack[i]->getIdentifier().c_str();
			(*callStackList)[i].location = callStack[i]->getLocation().c_str();
			(*callStackList)[i].timestamp = callStack[i]->getTimestamp();
			(*callStackList)[i].isEmergency = callStack[i]->isCallEmergency();
			(*callStackList)[i].tsi = callStack[i]->getTSI().c_str();

			IRACallStackHistory::CallType type = callStack[i]->getCallType();

			switch (type)
			{
			case IRACallStackHistory::CALL_INVALID:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::CALL_INVALID;
				break;
			}
			case IRACallStackHistory::VOICE:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::VOICE;
				break;
			}
			case IRACallStackHistory::CONFERENCE:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::CONFERENCE;
				break;
			}
			case IRACallStackHistory::TEXT:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::TEXT;
				break;
			}
			case IRACallStackHistory::GROUP_ACK:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::GROUP_ACK;
				break;
			}
			case IRACallStackHistory::GROUP_UNACK:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::GROUP_UNACK;
				break;
			}
			case IRACallStackHistory::GROUP_BROADCAST:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::GROUP_BROADCAST;
					break;
				}
				case IRACallStackHistory::MISSED:
				{
					(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::MISSED;
					break;
				}
				case IRACallStackHistory::FAILED:
				{
					(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::FAILED;
					break;
				}
				case IRACallStackHistory::ENDED:
				{
					(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::ENDED;
					break;
				}
			}

			IRACallStackHistory::OriginType otype = callStack[i]->getOrigin();

			switch (otype)
			{
			case IRACallStackHistory::ORIGIN_INVALID:
			{
				(*callStackList)[i].originType = TA_Base_Bus::IRadioCorbaDef::ORIGIN_INVALID;
				break;
			}
			case IRACallStackHistory::INBOUND:
			{
				(*callStackList)[i].originType = TA_Base_Bus::IRadioCorbaDef::INBOUND;
				break;
			}
			case IRACallStackHistory::OUTBOUND:
			{
				(*callStackList)[i].originType = TA_Base_Bus::IRadioCorbaDef::OUTBOUND;
				break;
			}
			}

			// And delete the database member while we're here
			delete callStack[i];
			callStack[i] = NULL;
		}

		FUNCTION_EXIT;
		return callStackList;
	}

	TA_Base_Bus::IRadioCorbaDef::CallStackHistoryList* Radio::getCSHListByType(const char* profile, ta_uint32 locationKey, TA_Base_Bus::IRadioCorbaDef::EStackCallType callType, bool readWrite)
	{
		FUNCTION_ENTRY("getCSHList");

		IRACallStackHistory::CallType queryCalltype;
		switch (callType)
		{
		case CALL_INVALID:
			queryCalltype = IRACallStackHistory::CALL_INVALID;
			break;
		case VOICE:
			queryCalltype = IRACallStackHistory::VOICE;
			break;  
		case CONFERENCE:
			queryCalltype = IRACallStackHistory::CONFERENCE;
			break; 
		case TEXT:		
			queryCalltype = IRACallStackHistory::TEXT;
			break; 
		case GROUP_ACK:
			queryCalltype = IRACallStackHistory::GROUP_ACK;
			break;
		case GROUP_UNACK:
			queryCalltype = IRACallStackHistory::GROUP_UNACK;
			break;
		case GROUP_BROADCAST:
			queryCalltype = IRACallStackHistory::GROUP_BROADCAST;
			break;
		case MISSED:
			queryCalltype = IRACallStackHistory::MISSED;
			break;	
		case FAILED:
			queryCalltype = IRACallStackHistory::FAILED;
			break;
		case ENDED:
			queryCalltype = IRACallStackHistory::ENDED;
			break;
		}

		// Get the selected calls list from the database
		std::vector<TA_Base_Core::IRACallStackHistory*> callStack =
			TA_Base_Core::RACallStackHistoryAccessFactory::getInstance().getListByType(profile, locationKey, queryCalltype, readWrite);

		// Create the selected call list for returning.
		TA_Base_Bus::IRadioCorbaDef::CallStackHistoryList* callStackList =
			new TA_Base_Bus::IRadioCorbaDef::CallStackHistoryList();

		// Set it's length (it's a CORBA sequence, and as such needs its length specifed, because
		// sequences don't automatically increase in size)
		callStackList->length(callStack.size());

		// Now put the data from the IRACallStackHistory into the CallStackHistory struct in the CORBA sequence
		for (unsigned int i = 0; i < callStack.size(); i++)
		{
			(*callStackList)[i].profile = callStack[i]->getProfileName().c_str();
			(*callStackList)[i].locationKey = callStack[i]->getLocationKey();
			(*callStackList)[i].identifier = callStack[i]->getIdentifier().c_str();
			(*callStackList)[i].location = callStack[i]->getLocation().c_str();
			(*callStackList)[i].timestamp = callStack[i]->getTimestamp();
			(*callStackList)[i].isEmergency = callStack[i]->isCallEmergency();
			(*callStackList)[i].tsi = callStack[i]->getTSI().c_str();

			IRACallStackHistory::CallType type = callStack[i]->getCallType();

			switch (type)
			{
			case IRACallStackHistory::CALL_INVALID:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::CALL_INVALID;
				break;
			}
			case IRACallStackHistory::VOICE:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::VOICE;
				break;
			}
			case IRACallStackHistory::CONFERENCE:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::CONFERENCE;
				break;
			}
			case IRACallStackHistory::TEXT:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::TEXT;
				break;
			}
			case IRACallStackHistory::GROUP_ACK:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::GROUP_ACK;
				break;
			}
			case IRACallStackHistory::GROUP_UNACK:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::GROUP_UNACK;
				break;
			}
			case IRACallStackHistory::GROUP_BROADCAST:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::GROUP_BROADCAST;
				break;
			}
			case IRACallStackHistory::MISSED:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::MISSED;
				break;
			}
			case IRACallStackHistory::FAILED:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::FAILED;
				break;
			}
			case IRACallStackHistory::ENDED:
			{
				(*callStackList)[i].callType = TA_Base_Bus::IRadioCorbaDef::ENDED;
				break;
			}
			}

			IRACallStackHistory::OriginType otype = callStack[i]->getOrigin();

			switch (otype)
			{
			case IRACallStackHistory::ORIGIN_INVALID:
			{
				(*callStackList)[i].originType = TA_Base_Bus::IRadioCorbaDef::ORIGIN_INVALID;
				break;
			}
			case IRACallStackHistory::INBOUND:
			{
				(*callStackList)[i].originType = TA_Base_Bus::IRadioCorbaDef::INBOUND;
				break;
			}
			case IRACallStackHistory::OUTBOUND:
			{
				(*callStackList)[i].originType = TA_Base_Bus::IRadioCorbaDef::OUTBOUND;
				break;
			}
			}

			// And delete the database member while we're here
			delete callStack[i];
			callStack[i] = NULL;
		}

		FUNCTION_EXIT;
		return callStackList;
	}

	void Radio::retrieveCallStackHistory()
	{
		FUNCTION_ENTRY("retrieveCallStackHistory");
		// Get the selected calls list from the database
		std::vector<TA_Base_Core::IRACallStackHistory*> callStack =
			TA_Base_Core::RACallStackHistoryAccessFactory::getInstance().getFullList();

		RadioUpdateCallStackHistory message;
		message.isRetrieved = true;

		for (unsigned int i = 0; i < callStack.size(); i++)
		{
			message.callStackHistoryList[i].profile = callStack[i]->getProfileName().c_str();
			message.callStackHistoryList[i].locationKey = callStack[i]->getLocationKey();
			message.callStackHistoryList[i].identifier = callStack[i]->getIdentifier().c_str();
			message.callStackHistoryList[i].location = callStack[i]->getLocation().c_str();
			message.callStackHistoryList[i].timestamp = callStack[i]->getTimestamp();

			IRACallStackHistory::CallType type = callStack[i]->getCallType();

			switch (type)
			{
			case IRACallStackHistory::CALL_INVALID:
			{
				message.callStackHistoryList[i].callType = EStackCallType::CALL_INVALID;
				break;
			}
			case IRACallStackHistory::VOICE:
			{
				message.callStackHistoryList[i].callType = EStackCallType::VOICE;
				break;
			}
			case IRACallStackHistory::CONFERENCE:
			{
				message.callStackHistoryList[i].callType = EStackCallType::CONFERENCE;
				break;
			}
			case IRACallStackHistory::TEXT:
			{
				message.callStackHistoryList[i].callType = EStackCallType::TEXT;
				break;
			}
			case IRACallStackHistory::GROUP_ACK:
			{
				message.callStackHistoryList[i].callType = EStackCallType::GROUP_ACK;
				break;
			}
			case IRACallStackHistory::GROUP_UNACK:
			{
				message.callStackHistoryList[i].callType = EStackCallType::GROUP_UNACK;
				break;
			}
			case IRACallStackHistory::GROUP_BROADCAST:
			{
				message.callStackHistoryList[i].callType = EStackCallType::GROUP_BROADCAST;
				break;
			}
			case IRACallStackHistory::MISSED:
			{
				message.callStackHistoryList[i].callType = EStackCallType::MISSED;
				break;
			}
			case IRACallStackHistory::FAILED:
			{
				message.callStackHistoryList[i].callType = EStackCallType::FAILED;
				break;
			}
			case IRACallStackHistory::ENDED:
			{
				message.callStackHistoryList[i].callType = EStackCallType::ENDED;
				break;
			}
			}

			IRACallStackHistory::OriginType otype = callStack[i]->getOrigin();

			switch (otype)
			{
			case IRACallStackHistory::ORIGIN_INVALID:
			{
				message.callStackHistoryList[i].originType = EOriginType::ORIGIN_INVALID;
				break;
			}
			case IRACallStackHistory::INBOUND:
			{
				message.callStackHistoryList[i].originType = EOriginType::INBOUND;
				break;
			}
			case IRACallStackHistory::OUTBOUND:
			{
				message.callStackHistoryList[i].originType = EOriginType::OUTBOUND;
				break;
			}
			}

		}

		RadioStateUpdateBroadcaster::getInstance()->sendRadioUpdateCallStackHistory(message);
		FUNCTION_EXIT;

	}

	void Radio::clearCallStackHistory()
	{
		FUNCTION_ENTRY("clearCallStackHistory");

		TA_Base_Core::RACallStackHistoryAccessFactory::getInstance().clearRecords();

		FUNCTION_EXIT;
	}

	void Radio::addCallStackEntry(const char* profile, ta_uint32 locationKey, ta_uint32 timestamp, TA_Base_Bus::IRadioCorbaDef::EOriginType originType, TA_Base_Bus::IRadioCorbaDef::EStackCallType callType, const char* identifier, const char* location, bool isEmergency, const char* tsi)
	{
		FUNCTION_ENTRY("addCallStackEntry");

		EStackCallType scType;
		EOriginType oriType;
		TA_Base_Core::IRACallStackHistory::OriginType oType;

		switch (originType)
		{
		case TA_Base_Bus::IRadioCorbaDef::ORIGIN_INVALID:
		{
			oType = TA_Base_Core::IRACallStackHistory::ORIGIN_INVALID;
			oriType = EOriginType::ORIGIN_INVALID;
			break;
		}
		case TA_Base_Bus::IRadioCorbaDef::INBOUND:
		{
			oType = TA_Base_Core::IRACallStackHistory::INBOUND;
			oriType = EOriginType::INBOUND;
			break;
		}
		case TA_Base_Bus::IRadioCorbaDef::OUTBOUND:
		{
			oType = TA_Base_Core::IRACallStackHistory::OUTBOUND;
			oriType = EOriginType::OUTBOUND;
			break;
		}
		}

		TA_Base_Core::IRACallStackHistory::CallType cType;

		switch (callType)
		{
		case TA_Base_Bus::IRadioCorbaDef::CALL_INVALID:
		{
			cType = TA_Base_Core::IRACallStackHistory::CALL_INVALID;
			scType = EStackCallType::CALL_INVALID;
			break;
		}
		case TA_Base_Bus::IRadioCorbaDef::VOICE:
		{
			cType = TA_Base_Core::IRACallStackHistory::VOICE;
			scType = EStackCallType::VOICE;
			break;
		}
		case TA_Base_Bus::IRadioCorbaDef::CONFERENCE:
		{
			cType = TA_Base_Core::IRACallStackHistory::CONFERENCE;
			scType = EStackCallType::CONFERENCE;
			break;
		}
		case TA_Base_Bus::IRadioCorbaDef::TEXT:
		{
			cType = TA_Base_Core::IRACallStackHistory::TEXT;
			scType = EStackCallType::TEXT;
			break;
		}
		case TA_Base_Bus::IRadioCorbaDef::GROUP_ACK:
		{
			cType = TA_Base_Core::IRACallStackHistory::GROUP_ACK;
			scType = EStackCallType::GROUP_ACK;
			break;
		}
		case TA_Base_Bus::IRadioCorbaDef::GROUP_UNACK:
		{
			cType = TA_Base_Core::IRACallStackHistory::GROUP_UNACK;
			scType = EStackCallType::GROUP_UNACK;
			break;
		}
		case TA_Base_Bus::IRadioCorbaDef::GROUP_BROADCAST:
		{
			cType = TA_Base_Core::IRACallStackHistory::GROUP_BROADCAST;
			scType = EStackCallType::GROUP_BROADCAST;
			break;
		}
		case TA_Base_Bus::IRadioCorbaDef::MISSED:
		{
			cType = TA_Base_Core::IRACallStackHistory::MISSED;
			scType = EStackCallType::MISSED;
			break;
		}
		case TA_Base_Bus::IRadioCorbaDef::FAILED:
		{
			cType = TA_Base_Core::IRACallStackHistory::FAILED;
			scType = EStackCallType::FAILED;
			break;
		}
		case TA_Base_Bus::IRadioCorbaDef::ENDED:
		{
			cType = TA_Base_Core::IRACallStackHistory::ENDED;
			scType = EStackCallType::ENDED;
			break;
		}
	
		}
		

		TA_Base_Core::RACallStackHistoryAccessFactory::getInstance().addCallStackEntry(profile, locationKey, timestamp, oType, cType, identifier, location, isEmergency, tsi);

		if (m_active)
		{
			RadioAddCallStackEntry message;
			message.profile = profile;
			message.locationKey = locationKey;
			message.timestamp = timestamp;
			message.originType = oriType;
			message.callType = scType;
			message.identifier = identifier;
			message.location = location;
			message.isEmergency = isEmergency;
			message.tsi = tsi;

			// Send Comms Message
			m_callback.sendCommsMgsNewCallStack(profile, locationKey, timestamp, originType, callType, identifier, location, isEmergency, tsi);

			// Broadcast State Update to Peer RadioTetraAgent
			RadioStateUpdateBroadcaster::getInstance()->sendRadioAddCallStackEntry(message);
			LOG_GENERIC(SourceInfo, TA_Base_Core::DebugUtil::DebugInfo,
				"sendRadioAddCallStackEntry");
		}
		FUNCTION_EXIT;
	}

	void Radio::removeCallStackEntry(ta_uint32 timestamp, const char* tsi)
	{
		FUNCTION_ENTRY("removeCallStackEntry");
		TA_Base_Core::RACallStackHistoryAccessFactory::getInstance().deleteCallStackEntry(timestamp, tsi);

		if (m_active)
		{
			// Send comms message
			m_callback.sendCommsMgsDeleteCallStack(timestamp, tsi);

			// Broadcast State Update to Peer RadioTetraAgent
			RadioDeleteCallStackEntry message;
			message.timestamp = timestamp;
			message.tsi = tsi;

			RadioStateUpdateBroadcaster::getInstance()->sendRadioDeleteCallStackEntry(message);
			LOG_GENERIC(SourceInfo, TA_Base_Core::DebugUtil::DebugInfo,
				"sendRadioDeleteCallStackEntry");
		}

		FUNCTION_EXIT;
	}

	TA_Base_Bus::IRadioCorbaDef::RadioStatusSummary* Radio::getRadioStatusSummary()
	{
		FUNCTION_ENTRY("getRadioStatusSummary");

		auto instance = RadioStatusSummary::getInstance();
		return instance->getRadioStatusSummary();

		FUNCTION_EXIT;
	}

	char* Radio::getOwnerFromPatchMember(const char* TSI)
	{
		FUNCTION_ENTRY("getOwnerFromPatchMember");
		return CORBA::string_dup(TA_Base_Core::RAPatchMembersAccessFactory::getInstance().getOwnerFromPatchMember(TSI).c_str());

		FUNCTION_EXIT;
	}

	bool Radio::getGroupIdsFromSubId(const TA_Base_Bus::IRadioCorbaDef::strList& list, const char* patchrasubs)
	{
		FUNCTION_ENTRY("getOwnerFromPatchMember");
		std::vector<std::string> strList;
		for (unsigned int i = 0; i < list.length(); i++)
		{
			strList.push_back(CORBA::string_dup(list[i]));
		}

		return TA_Base_Core::RAPatchMembersAccessFactory::getInstance().getGroupIdsFromSubId(strList, patchrasubs);

		FUNCTION_EXIT;

	}

	bool Radio::getSubNamesFromSubId(const TA_Base_Bus::IRadioCorbaDef::strList& list, const char* TSI)
	{
		FUNCTION_ENTRY("getSubNamesFromSubId");
		std::vector<std::string> strList;
		for (unsigned int i = 0; i < list.length(); i++)
		{
			strList.push_back(CORBA::string_dup(list[i]));
		}

		return TA_Base_Core::RAPatchMembersAccessFactory::getInstance().getSubNamesFromSubId(strList, TSI);

		FUNCTION_EXIT;
	}

	void Radio::addGroupToPatch(const char* patchSubTsi, const char* groupSubTsi)
	{
		FUNCTION_ENTRY("addGroupToPatch");
		TA_Base_Core::RAPatchMembersAccessFactory::getInstance().addGroupToPatch(patchSubTsi, groupSubTsi);

		FUNCTION_EXIT;
	}

	void Radio::deletePatch(const char* TSI)
	{
		FUNCTION_ENTRY("deletePatch");
		TA_Base_Core::RASubscribersAccessFactory::getInstance().deletePatch(TSI);

		FUNCTION_EXIT;
	}

	bool Radio::groupPatchInsertDb(const char* displayName, const char* profileName, const char* timestamp)
	{
		FUNCTION_ENTRY("groupPatchInsertDb");
		return TA_Base_Core::RASubscribersAccessFactory::getInstance().groupPatchInsertDb(displayName, profileName, timestamp);


		FUNCTION_EXIT;
	}

	char* Radio::getOwnerITSI(const char* patchname)
	{
		FUNCTION_ENTRY("getOwnerITSI");
		return CORBA::string_dup(TA_Base_Core::RASubscribersAccessFactory::getInstance().getOwnerITSI(patchname).c_str());

		FUNCTION_EXIT;
	}

void Radio::setDpServerFallback(bool isFallback)
{
	m_serverLinkStatusThread->setLinkStatus(RadioServerLinkStatusUpdateThread::ServerFallback, isFallback);
}

void Radio::setDpServerLostConnection(int serverIndex, bool isLost)
{
	switch(serverIndex)
	{
	case 0:
		m_serverLinkStatusThread->setLinkStatus( RadioServerLinkStatusUpdateThread::Server0Down, isLost );
		break;
	case 1:
		m_serverLinkStatusThread->setLinkStatus( RadioServerLinkStatusUpdateThread::Server1Down, isLost );
		break;
	default:
		LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugWarn, "Invalid TcpServer index , value = %d", serverIndex);
		break;
	}
}

char* Radio::getMessage(const char* shortName)
{
	FUNCTION_ENTRY("getMessage");
	return CORBA::string_dup(TA_Base_Core::RAPredefinedSDSMessageAccessFactory::getInstance().getMessage(shortName).c_str());

	FUNCTION_EXIT;
}

TA_Base_Bus::IRadioCorbaDef::PredefinedSDSMessage* Radio::getByShortName(const char* shortName)
{
	FUNCTION_ENTRY("getByShortName");
	// Get the SDS based on shortName from the database
	TA_Base_Core::IRAPredefinedSDSMessage* sdsMessage =
		TA_Base_Core::RAPredefinedSDSMessageAccessFactory::getInstance().getByShortName(shortName);

	// Create the selected call list for returning.
	TA_Base_Bus::IRadioCorbaDef::PredefinedSDSMessage* corbaSDSmessage =
		new TA_Base_Bus::IRadioCorbaDef::PredefinedSDSMessage();

	LOG_GENERIC(SourceInfo, TA_Base_Core::DebugUtil::DebugInfo,
		"getByShortName - short name : %s + message : %s", sdsMessage->getShortName(), sdsMessage->getMessage());
	if (sdsMessage->getShortName().size() == 1)
	{
		corbaSDSmessage->shortName = CORBA::string_dup(sdsMessage->getShortName().c_str());
		corbaSDSmessage->message = CORBA::string_dup(sdsMessage->getMessage().c_str());
	}
	else
	{
		LOG_GENERIC(SourceInfo, TA_Base_Core::DebugUtil::DebugInfo,
			"getByShortName - no message found with the short name : %s", shortName);

	}

	delete sdsMessage;
	sdsMessage = NULL;

	FUNCTION_EXIT;
	return corbaSDSmessage;
}

TA_Base_Bus::IRadioCorbaDef::PredefinedSDSMessageList* Radio::getSDSList(bool readWrite)
{
	FUNCTION_ENTRY("getSDSList");
	// Get the full SDS message list from the database
	std::vector<TA_Base_Core::IRAPredefinedSDSMessage*> sdsList = TA_Base_Core::RAPredefinedSDSMessageAccessFactory::getInstance().getList(false);

	// Create the selected call list for returning.
	TA_Base_Bus::IRadioCorbaDef::PredefinedSDSMessageList* corbaSDSlist =
		new TA_Base_Bus::IRadioCorbaDef::PredefinedSDSMessageList();

	// Set it's length (it's a CORBA sequence, and as such needs its length specifed, because
	// sequences don't automatically increase in size)
	corbaSDSlist->length(sdsList.size());

	// Now put the data from the IRAPredefinedSDSMessage into the PredefinedSDSMessage struct in the CORBA sequence
	for (unsigned int i = 0; i < sdsList.size(); i++)
	{
		(*corbaSDSlist)[i].shortName = sdsList[i]->getShortName().c_str();
		(*corbaSDSlist)[i].message = sdsList[i]->getMessage().c_str();

		

		// And delete the database member while we're here
		delete sdsList[i];
		sdsList[i] = NULL;
	}
	FUNCTION_EXIT;
	return corbaSDSlist;
}

void Radio::deleteMessage(const char* shortName)
{
	FUNCTION_ENTRY("deleteMessage");
	//TA_Base_Core::IRAPredefinedSDSMessage* sdsMessage;

	//sdsMessage->setShortName(std::string(message.shortName));
	//sdsMessage->setMessage(std::string(message.message));

	TA_Base_Core::RAPredefinedSDSMessageAccessFactory::getInstance().deleteByShortName(shortName);

	FUNCTION_EXIT;
}

void Radio::createMessage(const char* shortName, const char* message, bool isNew)
{
	FUNCTION_ENTRY("createMessage");

	try
	{
		//TA_Base_Core::RAPredefinedSDSMessage sdsMessage(shortName, message, true);
		//sdsMessage.applyChanges();

		TA_Base_Core::RAPredefinedSDSMessageAccessFactory::getInstance().insertSDSMessage(shortName, message);
	}
	catch (...)
	{
		LOG_GENERIC(SourceInfo, TA_Base_Core::DebugUtil::DebugError,
			"createMessage - failed  to create Predefined SDS message");

	}

	FUNCTION_EXIT;
}

void Radio::updateMessage(const char* shortName, const char* message)
{
	FUNCTION_ENTRY("updateMessage");

	try
	{
		TA_Base_Core::RAPredefinedSDSMessageAccessFactory::getInstance().updateMessage(shortName, message);
	}
	catch (...)
	{
		LOG_GENERIC(SourceInfo, TA_Base_Core::DebugUtil::DebugError,
			"updateMessage - failed  to create Predefined SDS message");

	}

	FUNCTION_EXIT;
}

void Radio::insertDBPatchGroup(const char* patchName, const char* ownerTSI, const  std::vector<std::string>& patchMemberTSIs)
{
	FUNCTION_ENTRY("insertDBPatchGroup");
	// This group hasn't been deleted, so either create it or load it
	std::string firstTSI = patchMemberTSIs[0];
	std::string patchTsi = firstTSI;

	if (firstTSI.find('-') != std::string::npos)
		patchTsi = firstTSI.substr(0, firstTSI.find_first_of('-'));


	IRASubscribers* group = NULL;
	bool created = false;

	try
	{
		group = TA_Base_Core::RASubscribersAccessFactory::getInstance().getSubscriberDetails(patchTsi);
	}
	catch (TA_Base_Core::DataException & de)
	{
		LOG_GENERIC(SourceInfo, DebugUtil::DebugError,
			"Caught DataException, msg:\"%s\", data:\"%s\"",
			de.what(), de.getWhichData().c_str());
		LOG_EXCEPTION_CATCH(SourceInfo, "DataException", "Caught exception while attempting to load subscriber. This could simply be because the subscriber does not exist yet, or it could be another error");
		// If there was an error loading the item from the database, then try to create one instead
		try
		{
			// Need to work out the location key for the group
			ta_uint32 locationKey = 1; // Todo: Need to get the actual location key
			std::string locationName = "OCC"; // Todo: Need to get the actual location name
			group = new TA_Base_Core::RASubscribers(patchTsi,
				patchName,
				TA_Base_Core::IRASubscribers::PATCH_GROUP,
				locationName,
				locationKey,
				true,
				ownerTSI);

			// And save the group to the database
			group->applyChanges();

			created = true;
		}
		catch (...)
		{
			// If this fails - well, that's bad. Give up on this group and continue to the next one
			LOG_GENERIC(SourceInfo, DebugUtil::DebugError,
				"Non-recoverable error while attempting to create group with TSI: %s",
				patchTsi);
		}
	}
	catch (...)
	{
		// Otherwise this group is a lost cause
		LOG_GENERIC(SourceInfo, DebugUtil::DebugError,
			"Miscellaneous exception while attempting to load group with TSI: %s",
			patchTsi.c_str());
	}


	insertDBPatchGroupMembers(group, patchMemberTSIs);

	// update the GUI
	if (m_active && NULL != group)
	{
		if (created)
		{
			RadioDirectoryServant::notifySubscriberChange(group, IRadioDirectoryCallback::NEW_SUBSCRIBER);
		}
		else
		{
			RadioDirectoryServant::notifySubscriberChange(group, IRadioDirectoryCallback::UPDATE_SUBSCRIBER);
		}

		// Broadcast State Update to Peer RadioTetraAgent
		SubscriberStateUpdate message;
		message.notifyType = NEW_SUBSCRIBER;
		message.details.TSI = group->getTSI();
		message.details.subscriberName = group->getSubscriberName();
		message.details.locationName = group->getLocation();
		message.details.locationKey = group->getLocationKey();
		message.details.ownerTSI = group->getOwner();
		message.details.type = TA_IRS_App::PATCH_SUBSCRIBER;

		for (int idx = 0; idx < patchMemberTSIs.size(); idx++)
		{
			GroupDetails newGrp;
			newGrp.groupTSI = group->getTSI();
			newGrp.memberTSI = patchMemberTSIs[idx];
			message.groupList.push_back(newGrp);
		}

		RadioStateUpdateBroadcaster::getInstance()->sendRadioSubscriberUpdate(message);
		LOG_GENERIC(SourceInfo, TA_Base_Core::DebugUtil::DebugInfo,
			"sendRadioDeleteCallStackEntry");

		delete group;
		group = NULL;
	}

	FUNCTION_EXIT;
}

void Radio::insertDBDynaGroup(const char* dgnaTSI, const char* dgnaName, const  std::vector<std::string>& destTSIs, const char * sessionId)
{
	FUNCTION_ENTRY("insertDBDynaGroup");
	// This group hasn't been deleted, so either create it or load it
	IRASubscribers* group = NULL;
	bool created = false;

	try
	{
		group = TA_Base_Core::RASubscribersAccessFactory::getInstance().getSubscriberDetails(dgnaTSI);
	}
	catch (TA_Base_Core::DataException & de)
	{
		LOG_GENERIC(SourceInfo, DebugUtil::DebugError,
			"Caught DataException, msg:\"%s\", data:\"%s\"",
			de.what(), de.getWhichData().c_str());
		LOG_EXCEPTION_CATCH(SourceInfo, "DataException", "Caught exception while attempting to load subscriber. This could simply be because the subscriber does not exist yet, or it could be another error");
		// If there was an error loading the item from the database, then try to create one instead
		try
		{
			std::string owner;
			// Get the session information
			
			TA_Base_Bus::AuthenticationLibrary  authLib(true);
			TA_Base_Bus::SessionInfo sessionInfo = authLib.getSessionInfo(sessionId, sessionId);
			TA_Base_Core::IProfile* pProfile = TA_Base_Core::ProfileAccessFactory::getInstance().getProfile(sessionInfo.ProfileId[0]);
			if (0 != pProfile)
			{
				owner = pProfile->getName();
				delete pProfile;
			}

			// Need to work out the location key for the group
			ta_uint32 locationKey = 1; // Todo: Need to get the actual location key
			std::string locationName = "OCC"; // Todo: Need to get the actual location name
			group = new TA_Base_Core::RASubscribers(dgnaTSI,
				dgnaName,
				TA_Base_Core::IRASubscribers::GROUP,
				locationName,
				locationKey,
				true,
				owner);

			// And save the group to the database
			group->applyChanges();

			created = true;
		}
		catch (...)
		{
			// If this fails - well, that's bad. Give up on this group and continue to the next one
			LOG_GENERIC(SourceInfo, DebugUtil::DebugError,
				"Non-recoverable error while attempting to create group with TSI: %s",
				dgnaTSI);
		}
	}
	catch (...)
	{
		// Otherwise this group is a lost cause
		LOG_GENERIC(SourceInfo, DebugUtil::DebugError,
			"Miscellaneous exception while attempting to load group with TSI: %s",
			dgnaTSI);
	}

	insertDBDynaGroupMembers(group, destTSIs);

	// update the GUI
	if (m_active && NULL != group)
	{
		if (created)
		{			
			RadioDirectoryServant::notifySubscriberChange(group, IRadioDirectoryCallback::NEW_SUBSCRIBER);
		}
		else
		{
			RadioDirectoryServant::notifySubscriberChange(group, IRadioDirectoryCallback::UPDATE_SUBSCRIBER);
		}
		
		// Broadcast State Update to Peer RadioTetraAgent
		SubscriberStateUpdate message;
		message.notifyType = NEW_SUBSCRIBER;
		message.details.TSI = group->getTSI();
		message.details.subscriberName = group->getSubscriberName();
		message.details.locationName = group->getLocation();
		message.details.locationKey = group->getLocationKey();
		message.details.ownerTSI = group->getOwner();	
		message.details.type = TA_IRS_App::GROUP_SUBSCRIBER;

		for (int idx = 0; idx < destTSIs.size(); idx++)
		{
			GroupDetails newGrp;
			newGrp.groupTSI = group->getTSI();
			newGrp.memberTSI = destTSIs[idx];
			message.groupList.push_back(newGrp);
		}

		RadioStateUpdateBroadcaster::getInstance()->sendRadioSubscriberUpdate(message);
		LOG_GENERIC(SourceInfo, TA_Base_Core::DebugUtil::DebugInfo,
			"sendRadioDeleteCallStackEntry");

		delete group;
		group = NULL;
	}

	FUNCTION_EXIT;
}

void Radio::insertDBDynaGroupMembers(IRASubscribers* group, const  std::vector<std::string>& destTSIs)
{
	FUNCTION_ENTRY("insertDBDynaGroupMembers");

	// remove all group members
	TA_Base_Core::RASubscribersAccessFactory::getInstance().dropGroup(group->getTSI());

	std::string memberTSI;
	std::stringstream memberStr;
	for (int idx = 0; idx < destTSIs.size(); idx++)
	{
		memberTSI = destTSIs[idx];
		try
		{
			IRASubscribers* subscriber = TA_Base_Core::RASubscribersAccessFactory::getInstance().
				getSubscriberDetails(memberTSI);

			if (subscriber != 0)
			{	
				TA_Base_Core::RAGroupMembersAccessFactory::getInstance().addMemberToGroup(*group, *subscriber);
				memberStr << memberTSI << ", ";
				delete subscriber;
				subscriber = NULL;
			}
		}
		catch (...)
		{
			LOG_GENERIC(SourceInfo, DebugUtil::DebugError,
				"Error while adding member with TSI = %s to group with TSI = %s. This could simply be because the subscriber was already deleted, or it could be another problem.",
				memberTSI.c_str(), group->getTSI().c_str());
		}
	}
	
	LOG_GENERIC(SourceInfo, DebugUtil::DebugDebug,
		"Members of group: %s are: %s",
		group->getTSI(false).c_str(), memberStr.str().c_str());

	FUNCTION_EXIT;
}


void Radio::deleteDBDynaGroup(const char* dgnaTSI)
{
	FUNCTION_ENTRY("deleteDBDynaGroup");

	IRASubscribers* group = NULL;
	bool created = false;

	try
	{
		group = TA_Base_Core::RASubscribersAccessFactory::getInstance().getSubscriberDetails(dgnaTSI);

		// remove all group members
		TA_Base_Core::RASubscribersAccessFactory::getInstance().dropGroup(dgnaTSI);

		// remove the group
		TA_Base_Core::RASubscribersAccessFactory::getInstance().deleteGroup(dgnaTSI);
	}
	catch (...)
	{
		// Otherwise this group is a lost cause
		LOG_GENERIC(SourceInfo, DebugUtil::DebugError,
			"Unknown exception while attempting to load group with TSI: %s",
			dgnaTSI);
	}

	if (m_active && 0 != group)
	{
		RadioDirectoryServant::notifySubscriberChange(group, IRadioDirectoryCallback::DELETE_SUBSCRIBER);

		// Broadcast State Update to Peer RadioTetraAgent
		SubscriberStateUpdate message;
		message.notifyType = DELETE_SUBSCRIBER;
		message.details.TSI = group->getTSI();
		message.details.subscriberName = group->getSubscriberName();
		message.details.locationName = group->getLocation();
		message.details.locationKey = group->getLocationKey();
		message.details.ownerTSI = group->getOwner();
		message.details.type = TA_IRS_App::GROUP_SUBSCRIBER;

		RadioStateUpdateBroadcaster::getInstance()->sendRadioSubscriberUpdate(message);
		LOG_GENERIC(SourceInfo, TA_Base_Core::DebugUtil::DebugInfo,
			"deleteDBDynaGroup");
	}
	
	FUNCTION_EXIT;
}

void Radio::addSubscriber(const SubscriberDetails& subscriber, const GroupList& groupList)
{
	FUNCTION_ENTRY("addSubscriber");

	try
	{
		std::vector<std::string> destTSIs;
		for (int idx = 0; idx < groupList.size(); idx++)
		{
			destTSIs.push_back(groupList[idx].memberTSI);
		}

		TA_Base_Core::IRASubscribers* newSub = _addNewSubscriber(
			subscriber.TSI,
			subscriber.subscriberName,
			subscriber.type,
			subscriber.locationName,
			subscriber.locationKey,
			subscriber.ownerTSI
		);

		if (0 != newSub)
		{
			if (subscriber.type == GROUP_SUBSCRIBER)
			{
				insertDBDynaGroupMembers(newSub, destTSIs);
			}
			else if (subscriber.type == PATCH_SUBSCRIBER)
			{
				insertDBPatchGroupMembers(newSub, destTSIs);
			}
		}
	}
	catch (...)
	{
		// Otherwise this group is a lost cause
		LOG_GENERIC(SourceInfo, DebugUtil::DebugError,
			"Unknown exception while attempting to load group with TSI: %s",
			subscriber.TSI.c_str());
	}

	FUNCTION_EXIT;
}

TA_Base_Core::IRASubscribers* Radio::_addNewSubscriber(const std::string& tsi,
	const std::string& subsName,
	SubscriberType subsType,
	const std::string& location,
	ta_uint32 locationKey,
	const std::string& owner)
{
	FUNCTION_ENTRY("_addNewSubscriber");

	IRASubscribers* newSubscriber = NULL;
	try
	{
		newSubscriber = TA_Base_Core::RASubscribersAccessFactory::getInstance().getSubscriberDetails(tsi);
	}
	catch (TA_Base_Core::DataException & de)
	{
		LOG_GENERIC(SourceInfo, DebugUtil::DebugError,
			"Caught DataException, msg:\"%s\", data:\"%s\"",
			de.what(), de.getWhichData().c_str());
		LOG_EXCEPTION_CATCH(SourceInfo, "DataException", "Caught exception while attempting to load subscriber. This could simply be because the subscriber does not exist yet, or it could be another error");
		// If there was an error loading the item from the database, then try to create one instead
		try
		{

			TA_Base_Core::IRASubscribers::SubscriberType type = TA_Base_Core::IRASubscribers::SubscriberType::INVALID;
			switch (subsType)
			{
			case INDIVIDUAL_SUBSCRIBER:
				type = TA_Base_Core::IRASubscribers::SubscriberType::INDIVIDUAL;
				break;
			case GROUP_SUBSCRIBER:
				type = TA_Base_Core::IRASubscribers::SubscriberType::GROUP;
				break;
			case PATCH_SUBSCRIBER:
				type = TA_Base_Core::IRASubscribers::SubscriberType::PATCH_GROUP;
				break;
			case DISPATCHER_SUBSCRIBER:
				type = TA_Base_Core::IRASubscribers::SubscriberType::DISPATCHER;
				break;
			case MOBILE_SUBSCRIBER:
				type = TA_Base_Core::IRASubscribers::SubscriberType::MOBILE;
				break;
			}

			// Need to work out the location key for the group
			newSubscriber = new TA_Base_Core::RASubscribers(tsi,
				subsName,
				type,
				location,
				locationKey,
				true,
				owner);

			// And save the group to the database
			newSubscriber->applyChanges();

		}
		catch (...)
		{
			// If this fails - well, that's bad. Give up on this group and continue to the next one
			LOG_GENERIC(SourceInfo, DebugUtil::DebugError,
				"Non-recoverable error while attempting to create with TSI: %s",
				tsi.c_str());
		}
	}
	catch (...)
	{
		// Otherwise this group is a lost cause
		LOG_GENERIC(SourceInfo, DebugUtil::DebugError,
			"Miscellaneous exception while attempting to load  with TSI: %s",
			tsi.c_str());
	}

	FUNCTION_EXIT;
	return newSubscriber;
}

void Radio::updateSubscriber(const SubscriberDetails& subscriber, const GroupList& groupList)
{
	FUNCTION_ENTRY("updateSubscriber");

	FUNCTION_EXIT;
}

void Radio::deleteSubscriber(const SubscriberDetails& subscriber, const GroupList& groupList)
{
	FUNCTION_ENTRY("deleteSubscriber");
	try
	{
		TA_Base_Core::IRASubscribers* subs = TA_Base_Core::RASubscribersAccessFactory::getInstance().getSubscriberDetails(subscriber.TSI);
		if (0 != subs)
		{
			TA_Base_Core::RASubscribersAccessFactory::getInstance().deleteSubscriber(subs);
		}	
		else
			LOG1(SourceInfo, DebugUtil::DebugError, "Unable to find subscriber with TSI = %s from database.", subscriber.TSI.c_str());
	}
	catch (...)
	{	
		LOG_GENERIC(SourceInfo, DebugUtil::DebugError,
			"Miscellaneous exception while attempting to load  with TSI: %s",
			subscriber.TSI.c_str());
	}
	FUNCTION_EXIT;
}

void Radio::insertDBPatchGroupMembers(IRASubscribers* group, const  std::vector<std::string>& destTSIs)
{
	FUNCTION_ENTRY("insertDBPatchGroupMembers");
	// remove all group members
	TA_Base_Core::RASubscribersAccessFactory::getInstance().dropPatchMembers(group->getTSI());

	std::string memberTSI;
	std::stringstream memberStr;
	for (int idx = 0; idx < destTSIs.size(); idx++)
	{
		memberTSI = destTSIs[idx];
		try
		{
			IRASubscribers* subscriber = TA_Base_Core::RASubscribersAccessFactory::getInstance().
				getSubscriberDetails(memberTSI);

			if (subscriber != 0)
			{
				TA_Base_Core::RAPatchMembersAccessFactory::getInstance().addGroupToPatch(*group, *subscriber);
				memberStr << memberTSI << ", ";
				delete subscriber;
				subscriber = NULL;
			}
		}
		catch (...)
		{
			LOG_GENERIC(SourceInfo, DebugUtil::DebugError,
				"Error while adding member with TSI = %s to group with TSI = %s. This could simply be because the subscriber was already deleted, or it could be another problem.",
				memberTSI.c_str(), group->getTSI().c_str());
		}
	}

	LOG_GENERIC(SourceInfo, DebugUtil::DebugDebug,
		"Members of group: %s are: %s",
		group->getTSI(false).c_str(), memberStr.str().c_str());

	FUNCTION_EXIT;
}
