/**
  * The source code in this file is the property of
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/4669_T01271350/4669/transactive/app/radio/RadioTetraAgent/src/RadioSession.h $
  * @author:  Ripple
  * @version: $Revision: #4 $
  *
  * Last modification: $DateTime: 2009/09/23 13:09:47 $
  * Last modified by:  $Author: builder $
  *
  */
///////////////////////////////////////////////////////////
//
//  RadioSession.h
//  Implementation of the Class RadioSession
//  Generated by Enterprise Architect
//  Created on:      30-Oct-2003 08:20:31
//  Original author: Andy Parker
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(RadioSession_B832D217_3758_4203_AB7C_56A473240AAF__INCLUDED_)
#define RadioSession_B832D217_3758_4203_AB7C_56A473240AAF__INCLUDED_

#include "core/types/src/ta_types.h"
#include <string>
#include <vector>

#include "core/synchronisation/src/Condition.h"
#include "core/data_access_interface/radio/src/IRACallStackHistory.h"
#include "bus/radio/RadioAgentCorbaDef_4669/idl/src/IRadioSessionCorbaDef.h"
#include "bus/radio/RadioAgentCorbaDef_4669/idl/src/IRadioCorbaDef.h"
#include "app/radio/RadioTetraAgent/src/RadioCircuitModeManager.h"
#include "app/radio/RadioTetraAgent/src/RadioTypes.h"
#include "app/radio/RadioTetraAgent/RadioProtocolLibrary/src/RadioProtocolLibrary.h"
#include "app/radio/RadioTetraAgent/src/RadioFallbackException.h"
/**
* This class manages a single radio session.
* @author Andy Parker
* @version 1.0
* @generator Enterprise Architect
* @created 30-Oct-2003 08:20:31
*/
namespace TA_Base_Core
{
    class RadioGlobalEntityData;
}
// namespace TA_Base_Bus
// {
//     class ItaScada;
// }

namespace TA_IRS_Bus
{
    class MultiPageSdsUtils;
}

namespace TA_IRS_App
{
	class Radio;
	struct CallForwardingDetails;
	class RadioEvent;
	class RadioMethod;
    class RadioTcpServer;
    struct RadioSessionType;
	class IRadioSessionServant;
	class RadioMethodNewReference;
	class RadioSessionInitialisationThread;
	
	enum DetachExecutionStatus
	{
		DetachOngoing,
		DetachIdle
	};

	class RadioSession
	{

	public:
		//RadioSession(std::string entityName,IRadioSessionServant& radioSessionServant,Radio& radio,unsigned int audioLink,std::string autoLoginName); TD14696
        RadioSession(   std::string entityName,
                        IRadioSessionServant & radioSessionServant,
                        RadioTcpServer & radio,
                        unsigned int audioLink,
                        std::string autoLoginName,
						std::string ipAddressGWLD,
                        TA_IRS_Bus::MultiPageSdsUtils& sdsUtils,
                        TA_IRS_App::ConsoleID consoleID,
						ta_uint32 switchUserWaitPeriod,
                        TA_Base_Core::RadioGlobalEntityData& globalEntityData,
                        //TA_Base_Bus::ItaScada& itaScada,
						bool isSDSSession,
						bool isDirSyncSession);

		virtual ~RadioSession();

		/// enumeration representing the various states that a Session will
        /// transition through
		enum SessionState
        {
            SessionUnassigned,
			SessionAssigned,
			SessionInitialised,
			SessionLoggedIn
        };

	public:
		/*To store session profile name*/
		void setSessionProfileName(std::string sessionProfile);
		/*To get session profile name*/
		std::string getSessionProfileName();

        /* Starts and stops the radio session */
        void start();
        void stop();
        /**
         * Returns the identifier for this session
         */
        std::string getSessionEntityName();

        /**
         * Returns the key for this session
         */
        ta_uint32 getSessionEntityKey();

		/**
		* This will call the AttachSession and Initialise functions to setup the
        * session with the radio
		*/
		void initialiseSession();

        /**
         * Log in the user of the session
         * Sets the login name and triggers login
         * (done in a different thread)
         * 
         * @param loginName the new session login name
         * @param password optional. If blank one will be created.
         */
		void loginSession(const std::string& loginName, const std::string& password);

		/**
		* Logout the user
		*/
		void doLogoutSession();
		void logoutSession();
		SessionReference getValidSessionRef();
		SessionReference doDetachSession();
		void detachSession();

		void overwriteSessionStatus( SessionState state);

        bool isAttached() const;
        bool isInitialised() const;
        bool isLoggedIn() const;

		void updateRadioStatusSummary();

		void answerCall(CallID callId, std::string sessionId, bool isAutoAnswer = false);
		//TD 10234
        ta_int32 makeCall(const std::string & destTSI, ECallType callType, bool isFullDuplex, ECallPriority priority, bool hook, std::string sessionId, bool isInvisibleToGUIApps, ta_int32 locationKey); // TD14696
		void releaseCall(CallID callId, std::string sessionId);
        // client calls - already paged
				// client calls - already paged
		bool sendTextMessage(const std::string& destTSI, const TA_IRS_App::MessageListType& messages, ESdsServiceSelection serviceSelection, const std::string& sessionId, std::string& status, bool logHistory = false, bool encodeSDS = true);

		// internal calls, require paging
		bool sendTextMessage(const std::string& destTSI, const std::string& message, ESdsServiceSelection serviceSelection, const std::string& sessionId, std::string& status);

		// internal send
		//bool sendTextDataMessage(const std::string& destTSI, const TA_IRS_App::MessageTextType& message, ESdsServiceSelection serviceSelection, std::string& status);
		bool sendTextDataMessage(const std::string& destTSI, const TA_IRS_App::MessageTextType& message, ESdsServiceSelection serviceSelection, std::string& status, bool encodeSDS = true);

		//++Added to support userdefined message
		bool sendUserDefinedSDS(const std::string& destTSI, const TA_IRS_App::MessageListType& messages, const std::string& sessionId, std::string & status, bool logHistory=false);
		/**
		* Send the method to the radio and get the reply event.  This method simply calls the parent (m_radioTcpServer) sendMethod.
		* @param    method
		*/
		RadioEvent* sendMethod(RadioMethod& method, std::string destTSI="");
		void holdCall(CallID callId, std::string sessionId);
		void resumeCall(CallID callId, std::string sessionId);
		void demandTX(short priority,std::string sessionId, ta_uint32 & queueID);
		void ceaseTX(std::string sessionId);
		void selectCall(CallID callId, std::string sessionId);
		void deselectCall(CallID callId, std::string sessionId);
		void adjustCallVolume(CallID callId, bool increaseVol, std::string sessionId);

		//std::string makeDynamicGroup(const char* dgnaTSI, const char* dgnaName, std::vector<std::string> destTSIs, std::string sessionId);
		std::string makeDynamicGroup(std::vector<std::string> destTSIs, std::string sessionId);
		//void updateDynamicGroup(const char* dgnaTSI, const char* dgnaName, std::vector<std::string> destTSIs, std::string sessionId);
		void deleteDynamicGroup(const char* dgnaTSI, const char* sessionID);
		void updateDynamicGroup(std::vector<std::string> destTSIs, std::string sessionId);

		void createPatch(std::vector<std::string> list,std::string patchName,std::string sessionId);
		void deletePatch(std::string patchName,std::string sessionId);
		void setCallForwarding(const CallForwardingDetails& details, std::string sessionId);
		void getCallForwarding(CallForwardingDetails& details);
 		std::string getPatchOwnerITSI();


        /**
         * Sets up a circuit mode data call
         */
        RadioReference setupDataCall(const std::string& destinationTsi, const std::string& destIPAddress);

        /**
         * Sends a packet in a circuit mode transfer
         */
        void sendCircuitDataFrame( RadioReference callReference,
                                   const RadioCircuitTransfer::Data& frame );

        /**
         * Ends a circuit mode transfer call
         */
        void endDataCall( RadioReference callReference );

        /**
         * Deletes a reference to an already ended call (ie disconnected)
         */
        void clearDataCallReference( RadioReference callReference );

        // //////////////////////////////////////
        // Monitoring Functionality
        // //////////////////////////////////////

        /**
         **/
        ta_uint32 startMonitoring(const char * tsi);

        /**
         **/
        void stopMonitoring(const char * tsi);

        /**
         **/
        ta_uint32 oneShotMonitoring(const char * tsi);

		TA_Base_Bus::IRadioSessionCorbaDef::MonitoredSubscriberList* getMonitoredSubscribers(SessionReference sessionRef);
		TA_Base_Bus::IRadioSessionCorbaDef::MonitoredGroupList* getMonitoredGroup(SessionReference sessionRef);

        /**
         **/
        CallID startListening(CallID callId);

        /**
         **/
        void stopListening(CallID callId);

        /**
         **/
		CallID joinCall(CallID callId);

        /**
         **/
        CallID includeSubscriber(CallID callId, const std::string & tsi);

        /**
         **/
		void terminateCall(CallID callId);

		void getAuthorisationList(AuthorisationStack& authorisationList);
		void authoriseCall(ta_uint32 callID, bool accept, const char* sessionID);

        // //////////////////////////////////////
		/// Called by the background thread to perform the initialisation.
		bool doAttachSession(std::pair<SessionReference,SessionReference>& sessionreferences, long attachTimer);
		bool doInitialiseSession();
		void doLoginSession(SessionReference previousSessionRef);

        /**
         * releaseSDSReference
         *
         * Performs a DeleteReference specifically for SDS references.
         *
         * @param sdsReference The reference to delete
         *
         * @exception 
         */
        void releaseSDSReference(const ta_uint32 sdsReference);


		/**
		* Called by the Radio object when we the connection to the TCPServer
        * is restored.
        *
        * @param 
		*/
        void onConnectionEstablish();

		void onConnectionLost();
		
		void onSwitchConnection();

        /**
         * Checks if the radio session should be logged in/should attempt to log in
         *
         * @return true if the connection is active, and the radio is also active
         */
        bool shouldLogIn();
		
		/**
         * Farnarcles around searching subscribers and querying to determine
         * the name of the subscriber with the given TSI.
         */
        std::string getSubscriberName(const std::string & tsi);


        /**
         * Accessor for the ITSI of this session. First usage for current
         * login performs QueryReference.
         * 
         * @return the TSI of this session
         */
		std::string getSessionTSI();

		void updateRadioSession(const RadioSessionType& radioSessionData);
		virtual void clearFullState();
		virtual void applyFullState(const RadioSessionType& state);
		virtual void getFullState(RadioSessionType& state);

        void setSwitchNotReachable(bool isNotReachable);
        bool getSwitchNotReachable() const;
        void setGwldLinkLost(bool isLinkLost);
        bool isGwldLinkLost() const;
        RadioTcpServer & getTcpServer();
		bool getIsISCSSession();

		ta_uint32 getRefID();
		
		std::string getSessionDGNAITSI();

		/**
		 * This function will return a search result reference for a specified search
		 *
		 * Remember to free the new search reference when you have finished with it!
		 */
        ta_uint32 performSubscriberSearch(std::string searchCriteria,
            RadioMethodSearchSubscribers::EView view = RadioMethodSearchSubscribers::NORMAL);        
        
        std::vector<std::string> queryResultsAsList(ta_uint32 resultRef, RadioMethodQueryReference::EKeys key);
		/**
		 * Query the details from a reference.
		 */
		std::string queryResults(ta_uint32 resultRef, RadioMethodQueryReference::EKeys key);

        /**
		 * Get a new reference for use with the radio commands
		 */
		RadioReference getNewReference(RadioMethodNewReference::ReferenceType referenceType);

        /**
         * deleteReference
         *
         * Deletes the reference passed to it. Cannot be used by subscriber references.
         *
         * @param reference The reference to delete
         * @param refType   The type of the reference
         */
        void deleteReference(RadioReference reference, RadioMethodDeleteReference::ReferenceType refType);

		/**
		 * This function will return a subscriber reference which can be used for direct
		 * manipulation of the associated record.
		 *
		 * Remember to free the new subscriber reference when you have finished with it!
		 */
		ta_uint32 convertTextToSubscriberReference(std::string textReference);

		void onSessionStatusChange( GxUpdateType state );

        void onAuthorisationChange(const TA_IRS_App::EAction action,const TA_IRS_App::AuthorisationRequestType& details);
		
		ConsoleID getConsoleID() { return m_consoleID;}
		
		void notifyLoginComplete();

		void addCallToHistory(std::string sessionId, const TA_IRS_App::CallDetailsType &details);
		void addCallToHistory(std::string sessionId,
			const time_t& timestamp,
			TA_Base_Bus::IRadioCorbaDef::EOriginType originType,
			TA_Base_Bus::IRadioCorbaDef::EStackCallType callType,
			const std::string& identifier,
			const std::string& itsi,
			const std::string& location,
			bool isEmergency);
		
		std::string getProfileFromSessionId(std::string sessionId);
		void updateTASession(const std::string& sessionID);

		void setLatestAttachDGNAITSI(const std::string& dgnaITSI);
		std::string getLatestAttachDGNAITSI();
		void setIncludeCallFlag(bool enabled);
		bool isIncludeCallITSI(const std::string& dgnaITSI);

		// for group call monitoring
		ta_uint32 startGroupMonitoring(const char * tsi);
		void stopGroupMonitoring(const char * tsi);
		bool isGroupMonitored(const std::string& groupTSI);
		ta_int32 testGroupCall(const std::string & groupTSI);

		
	private:
		std::string formatString(std::string& raData);
		bool is_little_endian() const;
		//Store session information
		TA_Base_Core::ReEntrantThreadLockable m_iscsSessionInfolock;
		std::string m_taSessionProfileName;
		/**
		* Parent radio - used to send out the radio messages
		*/
		RadioTcpServer & m_radioTcpServer;


		/**
		* Hardware audio link (0=none, 1..n link associated with session
		*/
		unsigned int m_audioLink;
		

		/**
		* Thread used for background initialisation
		*/
		RadioSessionInitialisationThread* m_radioSessionInitialisationThread;

		/**
		 * Radio API session reference for this session
		 */
		SessionReference m_sessionRef;			
		
		/**
		 * Entity name for radio session.
		 */
		std::string   m_sessionEntityName;

		
		/**
		* Reference to parent class interface, used to raise alarms.
		*/
		IRadioSessionServant& m_radioSessionServant;

		/**
		 * Name to be used for auto login -ISCS session
         * RvH  TD9386 PISF/TST/350 WP630027
         *      Also used for re-login.
		 */
		std::string m_loginName;
        std::string m_loginPassword;

		/**
		  * Needed for TD19666, while switch user, logout of the last user may 
		  * be performed after the new user tried to login.
		  **/
		ta_uint32 m_switchUserWaitPeriod;


		/**
		 * Subscriber text reference (for this session) persisted by getForwarding
		 * and used by setForwarding
		 */
        std::string m_subscriberTextRef;
		std::string m_IPAddressGWLD;
		bool        m_isEnableAttachSessEx;


		/*
		 * DGNA management
		 */
		std::string			m_sessionDGNAITSI;
		bool				m_sessionDGNAInUse;

        /*
         *TD 10234, is invisible to user.
         */
        bool m_isInvisibleToGUIApps;

		SessionState        m_sessionStatus;

		//To pervent DetachSession unsolicited event->doResetSession->DetachSession->InitialisationThread::DetachSession->doDetachSession->DetachSession unsolicited event loop
		DetachExecutionStatus     m_detachExecutionStatus;

		//Successfully attached session times
		ta_int32					m_attachedSessionTimes;

        //the m_attachedSessionTimes thread lock
        TA_Base_Core::ReEntrantThreadLockable m_attachSessionGuard;

        ///
        /// The TSI assigned to this radio session
        std::string         m_sessionITSI;

        bool                m_switchNotReachable;

        ///
        /// used by the RadioTcpServer class for managing GWLD_LINK_LOST errors
        bool                m_gwldLinkLost;

        ///Entity key of the Console this session
        ConsoleID           m_consoleID;

        ///
        ///Indicator to determine if this session is the SDS Session
        bool	            m_isSDSSession;
		bool				m_isDirSyncSession;

        void queryAllCallDetails(ta_uint32 callRef, QueryKeyValueMap & callValues);

		//return the attached session times
		int getAttachedSessionTimes();

		bool sendUserDefinedSDSInternal(const std::string& destTSI, const TA_IRS_App::MessageTextType& message, std::string & status);
        
        /**
         * Attaches to all groups that this session subscriber is in the group of.
         * Generally run during loginSession()
         * @return the number of successfully attached groups
         */
        int attachToGroups();

       
        /**
         * Requests the RCS to remove all the current members of the DGNA to
         * be removed.
         */
       
		void deassignDynamicGroup();

        /**
         * Resets data members and attempts initialiseSession. Does NOT perform
         * detach/logout first. This is for when a connection is reestablished.
         */
        void relogin();
		void reset();

        /**
         * Cute utility function to throw a RadioFallbackException
         * if m_radio.inFallback() returns true
         */
        void checkRadioFallback();

		void getRadioSessionData(RadioSessionType& radioSessionData);

		void sendStateUpdate();
        // Stores the global default emergency call priority
        TA_IRS_App::ECallPriority m_DefaultEmergencyCallPriority;

        // Stores the global default normal call priority
        TA_IRS_App::ECallPriority m_DefaultNormalCallPriority;

        TA_IRS_Bus::MultiPageSdsUtils& m_sdsUtils;
        // local flag for connection state
        volatile bool m_connectionEstablished;		

		TA_Base_Core::Condition m_condition;

		GxUpdateType m_currentGXType;

		std::string m_sessionId; ////store session id for retrieving session information once
		time_t m_lastUpdateTime;

		static const std::string M_TYPE_RETURN;
		static const std::string AC_COMPLETED;

		// Latest Attach DGNA Group - usefull for include call notification
		std::string			m_latestDGNAITSI;
		bool m_bIncludeCallFlag;
		
		struct MonitoredGroup
		{
			CallID callID;
			MonitorReference monitorID;
			std::string groupTSI;
		};

		typedef std::map<std::string, MonitoredGroup> T_MonitoredGroup;
		T_MonitoredGroup m_monitoredGroups;
		ta_uint32 m_locationKey;
	public:
		std::string getCurrentSession();
		DetachExecutionStatus getDetachExecutionStatus() { return m_detachExecutionStatus; }
	};

    inline RadioTcpServer & RadioSession::getTcpServer()
    {
        return m_radioTcpServer;
    }

	inline bool RadioSession::getIsISCSSession()
	{
		return m_isSDSSession;
	}

	inline ta_uint32 RadioSession::getRefID()
	{
		return m_sessionRef;
	}
}

#endif // !defined(RadioSession_B832D217_3758_4203_AB7C_56A473240AAF__INCLUDED_)
