/**
  * The source code in this file is the property of
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File$
  * @author:  Andy Parker
  * @version: $Revision$
  *
  * Last modification: $DateTime$
  * Last modified by:  $Author$
  *
  * This class is used to manage radio resources.
  * We need to know what audio channels are available to use for calls and
  * which need releasing when voice calls complete.  The Radio class
  * and radio session will need to use this manager.
  *
  * Also SDS resources must be released.
  *
  * We need this to be a thread as we cannot use the incoming radio event (TCP thread)
  * to send synchronous messages to the train as it will block stopping further TCP
  * receipt, i.e. it will never get its reply!
  */

///////////////////////////////////////////////////////////
//
//  RadioConnectionManager.cpp
//  Implementation of the Class RadioResourceManager
//  Generated by Enterprise Architect
//  Created on:      29-Oct-2003 17:43:57
//  Original author: Andy Parker
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////
#ifdef __WIN32__
#pragma warning(disable:4786)
#endif

#include "core/types/src/ta_types.h"
#include "core/synchronisation/src/ThreadGuard.h"
#include "core/utilities/src/TAAssert.h"
#include "core/utilities/src/DebugUtil.h"
#include "core/data_access_interface/entity_access/src/IRadioEntityData.h"
#include "app/radio/RadioTetraAgent/RadioProtocolLibrary/src/RadioProtocolLibrary.h"
#include "app/radio/RadioTetraAgent/src/RadioResourceManager.h"
#include "app/radio/RadioTetraAgent/src/RadioTcpServer.h"
#include "app/radio/RadioTetraAgent/src/RadioSessionHelper.h"
#include "app/radio/RadioTetraAgent/src/RadioStateUpdateBroadcaster.h"
#include "app/radio/RadioTetraAgent/src/RadioSynchronisationTypes.h"



/**
* This class will be used to manage the audio references
* @author Andy Parker
* @version 1.0
* @generator Enterprise Architect
* @created 29-Oct-2003 17:43:57
*/

using namespace TA_IRS_App;

/*
* Constructor
*
* This function adds an audio reference to the list of managed audio connections.
* @param   radio   Need to access the sendCommand method by the run method.
*/
RadioResourceManager::RadioResourceManager(RadioTcpServer& radio) 
					 : m_workQueueSemaphore(0),
					   m_terminate(false),
					   m_radio(radio)
{
    FUNCTION_ENTRY("Constructor");
	m_currentAudioVolume = m_DefaultVolume = m_radio.getRadio().getDefaultVolume();
	// Start the background thread to process the requests
	start();
    FUNCTION_EXIT;
}


RadioResourceManager::~RadioResourceManager()
{
    FUNCTION_ENTRY("Destructor");
	// Stop the background thread
	terminate();

	// Release the audio maps
	SessionAudioMap::iterator sessionIT = m_sessionAudioMap.begin();
	while (sessionIT != m_sessionAudioMap.end())
	{
		delete sessionIT->second;
		sessionIT->second = NULL;
		sessionIT++;
	}
    m_sessionAudioMap.clear();
    m_sessionVolume.clear();

    FUNCTION_EXIT;
}


/**
* This function adds the audio references associated with a session.
* @param   SessionRef    indicates the owner session
*/
void RadioResourceManager::addAudioReferences(SessionReference SessionRef)
{
    FUNCTION_ENTRY("addAudioReferences");

	// Remove any existing ones
	deleteAudioReferences(SessionRef);

    // The reply should have the list of audio references as text
    RadioSessionHelper helper(SessionRef, m_radio);
	std::vector<std::string> resultList = helper.queryReferenceAsList(SessionRef,RadioMethodQueryReference::K_CHANNELS,char(0xA));

    bool audio_session_added=false;
	// Now get a reference for each of the text audio references
	for ( std::vector<std::string>::iterator  it = resultList.begin();
	      it != resultList.end();
          it++)
	{
		if (!((*it).empty())) // (strlen(it->c_str())>0)
		{
			// Get audio reference from radio system
			RadioMethodTextToReference textToRef(SessionRef,*it);
			RadioEvent* reply = m_radio.sendMethod(textToRef);

			// The reply will contain the subscriber reference
			TextToReferenceEventReader textToRefReader(*reply);
			AudioReference audioRef = textToRefReader.getReference();

			// Delete the reply
			delete reply;
			reply = NULL;

			// Add to manager
			addAudioReference(SessionRef,audioRef);

            audio_session_added=true;
		}
	}

    if (audio_session_added)
    {
        m_sessionVolume[SessionRef] = 8;
    }
}



/**
* This function removes all audio references for a session.
* @param   SessionRef    indicates the owner session
*/
void RadioResourceManager::deleteAudioReferences(SessionReference sessionRef)
{
    FUNCTION_ENTRY("deleteAudioReferences");
	
    AudioEntryMap * audioMap=NULL;

    { // ThreadGuard scope restriction
        TA_Base_Core::ThreadGuard  guard(m_audioMapLock);

        // Find the audio map for the session
        SessionAudioMap::iterator sessionIT = m_sessionAudioMap.find(sessionRef);
        if (sessionIT!=m_sessionAudioMap.end())
        {
            audioMap = sessionIT->second;
            m_sessionAudioMap.erase(sessionIT);
            m_sessionVolume.erase(sessionRef);
            sendRemoveSessionFromAudioMap(sessionRef);

            LOG_GENERIC(SourceInfo, TA_Base_Core::DebugUtil::DebugInfo,
                        "RadioTcpServer %d (CRS%d) Session %lu removed from Audio map",
                        m_radio.getServerIndex(), m_radio.getCRSNumber(), sessionRef);
        }
        else
        {
            LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugInfo, "Audio map not defined for session %lu, could not remove", sessionRef);
        }
    } // ThreadGuard scope restriction


    if (0 != audioMap)
    {
        std::ostringstream in_use_str;
        int in_use_cnt=0;

        // log existing entries if still inUse
        // NOTE that this is performed outside of the ThreadGuard scope to
        // minimise impact of blocking other threads
        for (AudioEntryMap::iterator entryIt = audioMap->begin() ;
                entryIt != audioMap->end(); entryIt++ )
        {
            const AudioEntry & entry = (*entryIt).second;
            if (entry.inUse)
            {
                in_use_str << "[" << entry.callRef << "," << entry.volume << "," << ((entry.isMonitor)?"Normal":"Monitor") << "] ";
            }
        }

        if ( in_use_cnt > 0)
        {
            LOG_GENERIC(SourceInfo, TA_Base_Core::DebugUtil::DebugWarn,
                        "RadioTcpServer %d (CRS%d) Session %lu Audio map still contained active references [CallRef,volume,monitor] %s",
                        m_radio.getServerIndex(), m_radio.getCRSNumber(), sessionRef, in_use_str.str().c_str());
        }

        delete audioMap;
    }
    FUNCTION_EXIT;
}



/**
* This function attaches an audio reference to a call.
* @param   SessionRef    indicates the owner session
* @param   CallRef       call reference to be assoicated with the audio reference
*/
void RadioResourceManager::attachAudio(SessionReference sessionRef, CallReference callRef)
{
    FUNCTION_ENTRY("attachAudio");

	  AudioReference audioRef;
    bool audio_ok = useAudioEntry(sessionRef, callRef, audioRef);

    if (audio_ok)
    {
        RadioEvent * reply = NULL;
        try
        {
            // Attach the audio at the radio
            RadioMethodAttachAudio attachAudioMethod(sessionRef,callRef,audioRef);
            reply = m_radio.sendMethod(attachAudioMethod);
            delete reply;
            reply = NULL;
        }
        catch (...)
        {
            //
            // Silently handle cleanups and re-throw to higher level
            freeAudioEntry(sessionRef, audioRef);
            delete reply;
            reply = NULL;
            throw;
        }

        delete reply;
        reply = NULL;
    }
    else
    {
        // No available audio resource - throw an exception
        LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugError,"Audio resource not available for Call %lu Session %lu",callRef, sessionRef);

        FUNCTION_EXIT;
        return;
    }

    FUNCTION_EXIT;
}


/**
* This function releases the use of the audio reference.
*
* It may not do it directly but place it onto a separate thread to be processed
* as it might be necessary to make radio method calls
* 
* @param   SessionRef    indicates the owner session
* @param   CallRef       call reference to be assoicated with the audio reference
* @param   direct        indicates if action should be done on the calling thread (direct) or indirect by the manager thread
*/
void RadioResourceManager::releaseAudioReference(SessionReference sessionRef, CallReference callRef, bool direct, bool isMonitored)
{
    FUNCTION_ENTRY("releaseAudioReference");

	if (direct)
	{
		// Call direct as it is not necessary to  send the detachAudio message to
		// radio according to their docs.
        if (!isMonitored)
        {
            detachAudio(sessionRef,callRef,direct);
        }
        else
        {
            detachMonitorAudio(sessionRef,callRef,direct);
        }
	}
	else
	{
		// Place request on queue
		WorkRequestEntry   job;
		job.request    = (isMonitored) ? DETACH_MONITOR_AUDIO : DETACH_AUDIO;
		job.sessionRef = sessionRef;
		job.callRef    = callRef;
		job.sdsRef     = 0;

		{ // Nest for small scope of lock
			// Add job to queue
			TA_Base_Core::ThreadGuard  guard(m_workQueueLock);
			m_workQueue.push_back(job);
		}

		// Tell background thread to do it
		m_workQueueSemaphore.post();
	}

    FUNCTION_EXIT;
}


/**
* This function directs the audio to the specified speaker.
* Generally, selected calls are heard on the right speaker, whilst deselected calls are 
* heard on the left speaker.
* 
* @param   SessionRef    indicates the owner session
* @param   CallRef       call reference to be assoicated with the audio reference
* @param   rightSpeaker  indicates if right speaker should be used for call (false=left speaker)
*/
void RadioResourceManager::setAudioSpeaker(SessionReference sessionRef, CallReference callRef, AudioSpeaker audioSpeaker, int volumeDelta, RadioMethodChangeReference::MicrophoneState micState)
{
    FUNCTION_ENTRY("setAudioSpeaker");

	// Lock the store
	TA_Base_Core::ThreadGuard  guard(m_audioMapLock);

	
    AudioEntry audioEntry;
    AudioReference audioRef;
    bool found = findAudioEntry(sessionRef, callRef, audioRef, audioEntry);

	if (!found)
	{
		// No audio associated with this call. How is this possible ?
        LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugWarn, "No Call %lu Session %lu to adjust volume", callRef, sessionRef);
	}
	else
	{
        ta_int32 newCallVolume = audioEntry.volume + volumeDelta;
		if (newCallVolume >= 0 && newCallVolume <= 19)
		{	
			// Set speaker volumes
			ta_int32 lVolume = (LeftSpeaker==audioSpeaker) ? newCallVolume : 0;
			ta_int32 rVolume = (RightSpeaker==audioSpeaker) ? newCallVolume : 0;

			// Set the speaker volumes
			RadioMethodChangeReference changeReference(sessionRef,audioRef);
			changeReference.setAudioVolume(lVolume, rVolume, micState);
			RadioEvent * reply = m_radio.sendMethod(changeReference);
			delete reply;
			reply = NULL;

			// if we got this far then the volume change was successful
			audioEntry.volume = newCallVolume;
			storeAudioEntry(sessionRef, audioRef, audioEntry);
			sendUpdateAudioEntry(sessionRef, audioRef, audioEntry);
			LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugInfo,
					"Volume for Call %lu Session %lu changed to %d on %s speaker",
					callRef, sessionRef, audioEntry.volume, ((RightSpeaker==audioSpeaker)?"right":"left"));
		}
		else
		{
			LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugInfo,
				"Volume for Call %lu Session %lu volume reach limitation.",
				callRef, sessionRef );
		}
	}


	
	FUNCTION_EXIT;

}

/**
* This function adjusts the audio volume.  The new volume level will be used for subsequent calls.
* 
* @param   SessionRef    indicates the owner session
* @param   CallRef       call reference to be assoicated with the audio reference
* @param   increaseVolume  indicates if volume should increase (true) or decrease (false)
*/
void RadioResourceManager::adjustAudioVolume(SessionReference sessionRef,CallReference callRef,bool increaseVolume)
{
    FUNCTION_ENTRY("adjustAudioVolume");

    ta_int32 delta = 0;
	// Adjust the current volume setting
	if (increaseVolume)
	{
		m_currentAudioVolume++;
		delta=+1;
	}
	else
	{
		m_currentAudioVolume--;
		delta=-1;
	}

	ta_int32 new_session_volume = (m_sessionVolume[sessionRef] + delta);
	if (new_session_volume >= 0 && new_session_volume <= 19)
	{
	    // Adjust the call - it will be a selected call!
	    setAudioSpeaker(sessionRef,callRef,RightSpeaker,delta, RadioMethodChangeReference::MicNoChange);

		m_currentAudioVolume = new_session_volume;
		m_sessionVolume[sessionRef] = new_session_volume;
		sendUpdateAudioVolume(sessionRef,callRef,new_session_volume);
	}
}


//******************
// Private Methods *
//******************

/*
 * Method performing the background work
 */
void RadioResourceManager::run()
{
    FUNCTION_ENTRY("run");
	while (!m_terminate)
	{
		// Wait for some work to do
		m_workQueueSemaphore.wait();

		if (!m_terminate)
		{
			// Get job from queue - nest for scope of lock
			WorkRequestEntry  job;
			{
				TA_Base_Core::ThreadGuard  guard(m_workQueueLock);
				TA_ASSERT(m_workQueue.size()>0,"No work in resource manager queue");
				job = m_workQueue.at(0);
				m_workQueue.erase(m_workQueue.begin());
			}

			try
			{
				switch (job.request)
				{
					case DETACH_AUDIO:
						detachAudio(job.sessionRef,job.callRef,false);
						break;

					case DETACH_MONITOR_AUDIO:
						detachMonitorAudio(job.sessionRef,job.callRef,false);
						break;

					/*case DELETE_SDS:
						deleteSDS(job.sessionRef,job.sdsRef);*/
						break;

					default:
						TA_ASSERT(false,"Invalid job request type");
				}
			}
			catch (...)
			{
				// Don't want anything to kill our thread - e.g. timeout talking to RCS
				LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugWarn,"RadioResourceManager - Exception received when processing job");
			}
		}
	}

	m_terminate = false;
    FUNCTION_EXIT;
}

/*
 * Stop backgroung processing
 */
void RadioResourceManager::terminate()
{
    FUNCTION_ENTRY("terminate");
	m_terminate = true;

	// wake up queue
	m_workQueueSemaphore.post();
    FUNCTION_EXIT;
}


/**
* This function adds an audio reference to the list of managed audio connections.
* @param   SessionRef    indicates the owner session
* @param   AudioRef      audio reference
*/
void RadioResourceManager::addAudioReference(SessionReference SessionRef,AudioReference AudioRef)
{
    FUNCTION_ENTRY("addAudioReference");

	// Lock the store
	TA_Base_Core::ThreadGuard  guard(m_audioMapLock);

	// Find the audio map for the session
	AudioEntryMap* audioMap;
	{
		SessionAudioMap::iterator sessionIT = m_sessionAudioMap.find(SessionRef);
		if (sessionIT!=m_sessionAudioMap.end())
		{
			audioMap = sessionIT->second;
		}
		else
		{
			// New session
			audioMap = new AudioEntryMap();
			TA_ASSERT(audioMap!=NULL,"Unable to create session audio map");
			m_sessionAudioMap[SessionRef] = audioMap;
		}
	}

	// Check audio not already in map
	AudioEntryMap::iterator audioIT  = audioMap->find(AudioRef);
	TA_ASSERT(audioIT==audioMap->end(),"Audio entry already in map");

	// Add new audio to the map
	AudioEntry  entry;
	entry.inUse   = false;
    entry.isMonitor = false;
	entry.callRef = 0;
	(*audioMap)[AudioRef] = entry;
	sendUpdateAudioEntry(SessionRef, AudioRef, entry);

    FUNCTION_EXIT;
}


/*
 * This function performs the release of the audio from a call.  When called from a disconnect it cannot be done 
 * directly as calls must go to the radio which would then block the thread (which gets messages from the radio)
 */
void RadioResourceManager::detachAudio(SessionReference sessionRef, CallReference callRef,bool direct)
{
    FUNCTION_ENTRY("detachAudio");

    AudioEntry audioEntry;
    AudioReference audioRef;
    bool found = findAudioEntry(sessionRef, callRef, audioRef, audioEntry);

    if (found)
    {
        RadioEvent * reply = NULL;
        try
        {
            // Detach the audio at the radio
            RadioMethodDetachAudio detachAudioMethod(sessionRef,callRef,audioRef);
            reply = m_radio.sendMethod(detachAudioMethod);
            delete reply;
            reply = NULL;
            freeAudioEntry(sessionRef, audioRef);
        }
        catch (...)
        {
            delete reply;
            reply = NULL;
            freeAudioEntry(sessionRef, audioRef);
            throw;
        }
    }
    else
    {
        // No audio associated with this call. If an MFT is configured with no
        // audio links due to it having no DAC, there will be no entry for it
        // in the SessionAudioMap?
        LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugWarn,
                "No audio reference found for Call %lu Session %lu", callRef, sessionRef);
    }


	FUNCTION_EXIT;
}

ta_int32 RadioResourceManager::releaseAudioResources(SessionReference sessRef, CallReference callRef)
{
    FUNCTION_ENTRY("releaseAudioResources(sessRef, callRef)");

	// Find and release the audio reference 
    ta_int32 num_released = 0;

    { // ThreadGuard scope restriction
        // Lock the map
        TA_Base_Core::ThreadGuard guard(m_audioMapLock);

        SessionAudioMap::iterator sessionIter = m_sessionAudioMap.find(sessRef);
        if (sessionIter!=m_sessionAudioMap.end())
        {

            AudioEntryMap * audioEntryMap = sessionIter->second;
            for (AudioEntryMap::iterator audioIter = audioEntryMap->begin();
                 audioIter != audioEntryMap->end(); audioIter++)
            {
                if (audioIter->second.callRef==callRef)
                {
                    // Found call
                    audioIter->second.inUse = false;
                    audioIter->second.isMonitor = false;
                    audioIter->second.callRef = 0;
                    audioIter->second.volume = 0;
                    num_released++;
                    //broadcast the change in AudioEntry
                    sendUpdateAudioEntry(sessRef, audioIter->first, audioIter->second);
                }
            }
        }
    } // ThreadGuard scope restriction

    LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugInfo, "Released %d audio resources for Call %lu Session %lu", num_released, callRef, sessRef);
	FUNCTION_EXIT;
    return num_released;

}

void RadioResourceManager::attachMonitorAudio(SessionReference sessionRef, CallReference callRef, bool full)
{
    FUNCTION_ENTRY("attachMonitorAudio");

    ta_uint32 audioRef[2]= {0, 0};

    int foundnum = 0;
    int required = (full) ? 2 : 1;
    { // ThreadGuard scope

        // Lock the store
        TA_Base_Core::ThreadGuard guard(m_audioMapLock);

        // Find the audio map for the session
        SessionAudioMap::iterator sessionIT = m_sessionAudioMap.find(sessionRef);
        //TA_ASSERT((sessionIT!=m_sessionAudioMap.end()),"Audio map not defined for this session");
        if (sessionIT==m_sessionAudioMap.end())
        {
            LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugWarn,
                        "Audio map not defined for session %lu",
                        sessionRef);
            return;
        }

        // Find unused entry in map
        AudioEntryMap::iterator audioIter  = sessionIT->second->begin();
        while ((audioIter != sessionIT->second->end()) && (foundnum < required))
        {
            if (!audioIter->second.inUse)
            {
                // Found one
                audioIter->second.inUse   = true;
                audioIter->second.isMonitor = true;
                audioIter->second.callRef = callRef;
				// RvH 20050202 Radio iFAT
				// Set per-call volume to the default.
				//TD10963 marc_bugfix
				
				//TD10963 marc_bugfix get the default volume from the configuration 
				//audioIter->second.volume = m_currentAudioVolume = 8;
				audioIter->second.volume = m_currentAudioVolume = m_sessionVolume[sessionRef];


                audioRef[foundnum] = audioIter->first; 

                foundnum++;

				//broadcast the change in AudioEntry
				sendUpdateAudioEntry(sessionRef, audioIter->first, audioIter->second);
				LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugDebug,
							"attachMonitorAudio() - Looking for %d audio resources, found %d", required, foundnum);

                if (foundnum>=required)
                {
                    break;
                }
            }

            audioIter++;
        }

    }

    if (foundnum<required)
    {
        // insufficient audio resources - throw an exception

        LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugWarn,
                    "attachMonitorAudio() - Required %d audio resources, found %d", required, foundnum);

        // TA_THROW();
        return;
    }
    else
    {
        RadioEvent * reply = NULL;
        try
        {
            LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugWarn,
                        "attachMonitorAudio() - Attaching %d audio resources for callRef %lu, audioRef[%lu,%lu]", required, callRef, audioRef[0], audioRef[1]);
            // Arrange for the RCS to attach audio for us
            RadioMethodAttachMonitorAudio attachMonAudioMethod(sessionRef,callRef,audioRef[0],audioRef[1]);
            reply = m_radio.sendMethod(attachMonAudioMethod);
        }
        catch (...)
        {
            // silently handle this failure and throw further and beyond
            //freeAudioEntries(sessionRef,audioRefs);
            releaseAudioResources(sessionRef,callRef);
            delete reply;
            reply = NULL;
            throw;
        }
            
        delete reply;
        reply = NULL;
    }

    FUNCTION_EXIT;
}


void RadioResourceManager::detachMonitorAudio(SessionReference sessionRef, CallReference callRef, bool direct)
{
    FUNCTION_ENTRY("detachMonitorAudio");

    if (direct)
    {
        // Get current audio settings and delete them
        int numfound = 0;
        ta_uint32 audioRef[2] = {0, 0};

        // Lock the store
        TA_Base_Core::ThreadGuard  guard(m_audioMapLock);

        // Find the audio map for the session
        SessionAudioMap::iterator sessionIter = m_sessionAudioMap.find(sessionRef);
        // TA_ASSERT((sessionIter!=m_sessionAudioMap.end()),"Audio map not defined for this session");
        if (sessionIter==m_sessionAudioMap.end())
        {
            LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugWarn, "Audio map not defined for session 0x%X", sessionRef);
            return;
        }

        // Find the audio reference 
        for ( AudioEntryMap::iterator audioIter = sessionIter->second->begin();
              audioIter != sessionIter->second->end() ;
              audioIter++
            )
        {
            if (audioIter->second.callRef == callRef)
            {
                // Found call
                audioRef[numfound] = audioIter->first;
                numfound++;
            }
        }

        if (numfound>0)
        {
            // Request the radio to detach the monitor audio
            RadioMethodDetachMonitorAudio detachMonitorAudioMethod(sessionRef,callRef);
            RadioEvent* reply = m_radio.sendMethod(detachMonitorAudioMethod);
            delete reply;
        }
        else
        {
            // No audio associated with this call
            // TODO - is this possible or is it an error?
            //TA_THROW();
            LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugWarn,
                    "No audio reference found for call 0x%X (session 0x%X)", callRef, sessionRef);
        }
    }

    /* int released = */ releaseAudioResources(sessionRef, callRef);

    FUNCTION_EXIT;
}

bool RadioResourceManager::isAudioAttached(SessionReference sessionRef, CallReference callRef)
{
	FUNCTION_ENTRY("isAudioAttached");
	bool bFound = false;
	// Find the audio map for the session
	SessionAudioMap::iterator sessionFnd = m_sessionAudioMap.find(sessionRef);
	if (sessionFnd!=m_sessionAudioMap.end())
	{
		AudioEntryMap * audioMap = (*sessionFnd).second;

		for (AudioEntryMap::iterator iter = audioMap->begin();
			iter != audioMap->end() ; iter++ )
		{
			if ( (*iter).second.callRef == callRef )
			{
				bFound = true;
				break;
			}
		}
	}

	FUNCTION_EXIT;
	return bFound;
}

void RadioResourceManager::applyFullState(const RadioResourceManagerType& state)
{
	
	FUNCTION_ENTRY("applyFullState");
	
	clearFullState();
	
	this->m_currentAudioVolume = state.currentAudioVolume;
	
	SessionAudioMapType::const_iterator sourceSessionIT =state.sessionAudioMap.begin();
	
	while (sourceSessionIT != state.sessionAudioMap.end())
	{
		SessionReference sessionRef = sourceSessionIT->first.sessionRef;
		AudioEntryMapType::const_iterator sourceAudioMapIT = (sourceSessionIT->second).begin();
		//Allocate space for the Destination audioEntryMap
		AudioEntryMap *pAudioEntryMap = new AudioEntryMap();
		while(sourceAudioMapIT != (sourceSessionIT->second).end())
		{
			//copy the source AudioEntry struct to the Destination AudioEntry struct
			AudioReference audioRef = sourceAudioMapIT->first;
			AudioEntry audioEntry;
			audioEntry.callRef = (sourceAudioMapIT->second).callRef;
			audioEntry.inUse =	(sourceAudioMapIT->second).inUse ;
			audioEntry.volume = (sourceAudioMapIT->second).volume;
			//Build the audioEntryMap
			(*pAudioEntryMap).insert(std::pair<AudioReference, AudioEntry>(audioRef,audioEntry));
			++sourceAudioMapIT;
		}
		//Build the sessionAudioMap
		m_sessionAudioMap.insert(std::pair<SessionReference, AudioEntryMap*>(sessionRef,pAudioEntryMap));
        m_sessionVolume[sessionRef] = state.currentAudioVolume;
		
		++sourceSessionIT;
		
	}
	
	FUNCTION_EXIT;
}

void RadioResourceManager::clearFullState()
{
	FUNCTION_ENTRY("clearFullState");
	
	//m_currentAudioVolume = 8;//default value
	//TD10963 marc_bugfix support for default volume
	m_currentAudioVolume = (int)m_DefaultVolume;

	// Releases the audio maps
	SessionAudioMap::iterator sessionIT = m_sessionAudioMap.begin();
	while (sessionIT != m_sessionAudioMap.end())
	{
		delete sessionIT->second;
		sessionIT->second = NULL;
		sessionIT++;
	}
	m_sessionAudioMap.clear();
    m_sessionVolume.clear();
	
	FUNCTION_EXIT;
}

void RadioResourceManager::getFullState(RadioResourceManagerType& state,
							  const std::map<SessionReference,ConsoleID>& sessions)
{
	FUNCTION_ENTRY("getFullState");

	state.currentAudioVolume = this->m_currentAudioVolume;
	
	state.sessionAudioMap.clear();

	SessionAudioMapType::iterator destSessionIT = state.sessionAudioMap.begin();
	
	// copy from m_sessionAudioMap
	SessionAudioMap::iterator sourceSessionIT = m_sessionAudioMap.begin();
	
	LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugDebug,
		"RadioAudioResourceManager::getFullState SessionAudioMap size =%d",m_sessionAudioMap.size());

	while(sourceSessionIT != m_sessionAudioMap.end())
	{
		TA_IRS_App::SessionID sessionRef = sourceSessionIT->first;

		ConsoleID consoleKey = 0;
		std::map<SessionReference,ConsoleID>::const_iterator sMap = sessions.find(sessionRef);
		if (sMap != sessions.end())
		{
			consoleKey = sMap->second;
		}

		AudioEntryMap::iterator sourceAudioMapIT = sourceSessionIT->second->begin();
		TA_IRS_App::AudioEntryMapType audioEntryMap;
		//Iterate over the source m_sessionAudioMap to be inserted into destination sessionAudioMap

		while( sourceAudioMapIT != sourceSessionIT->second->end())
		{
			TA_IRS_App::AudioReference audioRef = sourceAudioMapIT->first;
			TA_IRS_App::AudioEntryType audioEntry;
			audioEntry.callRef = sourceAudioMapIT->second.callRef; 
			audioEntry.inUse = sourceAudioMapIT->second.inUse;
			audioEntry.volume = sourceAudioMapIT->second.volume;

			//Build the audioEntry Map
			audioEntryMap.insert(std::pair<TA_IRS_App::AudioReference, TA_IRS_App::AudioEntryType>(audioRef,audioEntry));
			++sourceAudioMapIT;
		
		}

		ConsoleSessionRef csRef;
		csRef.consoleKey = consoleKey;
		csRef.sessionRef = sessionRef;
		LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugDebug,
			"RadioAudioResourceManager::getFullState insert(Console %d, Session %d on TcpServer %d (CRS%d))",consoleKey,sessionRef,m_radio.getServerIndex(), m_radio.getCRSNumber());
		
		//sessionAudioMap
		state.sessionAudioMap.insert(std::pair<ConsoleSessionRef, TA_IRS_App::AudioEntryMapType>(csRef,audioEntryMap));
		++sourceSessionIT;
		
	}
		
	FUNCTION_EXIT;
}


void RadioResourceManager::sendRemoveSessionFromAudioMap(SessionReference sessionReference)
{
	FUNCTION_ENTRY("sendRemoveSessionFromAudioMap");

	RadioRemoveSessionFromAudioMap message;
	message.sessionReference = sessionReference;
	message.serverIndex = m_radio.getServerIndex();
	RadioStateUpdateBroadcaster::getInstance()->sendRadioRemoveSessionFromAudioMap(message);

	FUNCTION_EXIT;
}


void RadioResourceManager::sendUpdateAudioVolume(SessionReference sessionReference,
												 CallReference callReference, int currentVolume )
{
	FUNCTION_ENTRY("sendUpdateAudioVolume");

	RadioUpdateRadioResourceManagerVars message;
	message.sessionReference = sessionReference;
	message.callReference = callReference;
	message.currrentVolume = currentVolume;
	message.serverIndex = m_radio.getServerIndex();
	RadioStateUpdateBroadcaster::getInstance()->sendRadioUpdateRadioResourceManagerVars(message);

	FUNCTION_EXIT;
}

void RadioResourceManager::updateAudioEntryInSessionMap(SessionID sessionReference, 
														AudioReference audioReference,
														const TA_IRS_App::AudioEntryType& audioEntry)
{
	FUNCTION_ENTRY("updateAudioEntryInSessionMap");
	
	SessionAudioMap::iterator sessionIT = m_sessionAudioMap.find(sessionReference);
	
	//if the sessionReference is found
	if(sessionIT != m_sessionAudioMap.end())
	{
		AudioEntryMap::iterator audioMapIT = (*sessionIT->second).find(audioReference);

		//if the audioReference is found
		if(audioMapIT != sessionIT->second->end())
		{
			audioMapIT->second.callRef = audioEntry.callRef;
			audioMapIT->second.inUse = audioEntry.inUse;
			audioMapIT->second.volume = audioEntry.volume;
		}
		// If audioReference not found - create a audioEntry struct and insert into AudioEntryMap
		else
		{
			AudioEntry localAudioEntry;
			localAudioEntry.callRef = audioEntry.callRef;
			localAudioEntry.inUse = audioEntry.inUse;
			localAudioEntry.volume = audioEntry.volume;
			(*sessionIT->second).insert(std::pair<AudioReference, AudioEntry>(audioReference,localAudioEntry));
		}
	}
	//if the SessionReference not found - create a audioEntryMap and insert into the sessionAudioMap
	else
	{
		AudioEntryMap *pAudioEntryMap = new AudioEntryMap();
		AudioEntry localAudioEntry;
		localAudioEntry.callRef = audioEntry.callRef;
		localAudioEntry.inUse = audioEntry.inUse;
		localAudioEntry.volume = audioEntry.volume;
		(*pAudioEntryMap).insert(std::pair<AudioReference, AudioEntry>(audioReference,localAudioEntry));
		m_sessionAudioMap.insert(std::pair<SessionReference, AudioEntryMap*>(sessionReference,pAudioEntryMap));
	}



	
	FUNCTION_EXIT;
	
}

bool RadioResourceManager::findAudioEntry(SessionReference sessionRef, CallReference callRef, AudioReference & audioRef, AudioEntry & audioEntry)
{
    TA_Base_Core::ThreadGuard  guard(m_audioMapLock);

    // Find the audio map for the session
    SessionAudioMap::iterator sessionFnd = m_sessionAudioMap.find(sessionRef);
    if (sessionFnd!=m_sessionAudioMap.end())
    {
        AudioEntryMap * audioMap = (*sessionFnd).second;

        for (AudioEntryMap::iterator iter = audioMap->begin();
                iter != audioMap->end() ; iter++ )
        {
            if ( (*iter).second.callRef == callRef )
            {
                audioRef = (*iter).first;
                audioEntry = (*iter).second;
                return true;
            }
        }
    }

    LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugWarn, "AudioEntry NOT found for SessionReference %lu CallReference %lu", sessionRef, callRef);
    return false;
}

bool RadioResourceManager::useAudioEntry(SessionReference sessionRef, CallReference callRef, AudioReference & audioRef)
{
    TA_Base_Core::ThreadGuard  guard(m_audioMapLock);

    // Find the audio map for the session
    SessionAudioMap::iterator sessionFnd = m_sessionAudioMap.find(sessionRef);
    if (sessionFnd!=m_sessionAudioMap.end())
    {
        AudioEntryMap * audioMap = (*sessionFnd).second;

        for (AudioEntryMap::iterator iter = audioMap->begin();
                iter != audioMap->end() ; iter++ )
        {
            if ( !((*iter).second.inUse) )
            {
                (*iter).second.callRef = callRef;
                (*iter).second.inUse = true;
                (*iter).second.isMonitor = false;
                (*iter).second.volume = m_sessionVolume[sessionRef];

                audioRef = (*iter).first;

                return true;
            }
        }
    }

    LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugWarn, "AudioEntry NOT found for SessionReference %lu CallReference %lu", sessionRef, callRef);
    return false;
}

void RadioResourceManager::freeAudioEntry(SessionReference sessionRef, AudioReference audioRef)
{
    TA_Base_Core::ThreadGuard  guard(m_audioMapLock);

    // Find the audio map for the session
    SessionAudioMap::iterator sessionFnd = m_sessionAudioMap.find(sessionRef);
    if (sessionFnd!=m_sessionAudioMap.end())
    {
        AudioEntryMap * audioMap = (*sessionFnd).second;
        AudioEntryMap::iterator audioFnd = audioMap->find(audioRef);

        if (audioFnd != audioMap->end())
        {
            if ( ((*audioFnd).second.inUse) )
            {
                (*audioFnd).second.callRef = 0;
                (*audioFnd).second.inUse = false;
                (*audioFnd).second.isMonitor = false;
                (*audioFnd).second.volume = 0;
                return;
            }
            else
            {
                LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugWarn, "AudioEntry for SessionReference %lu AudioReference %lu was already NOT in use", sessionRef, audioRef);
            }
        }
    }

}

ta_int32 RadioResourceManager::useAudioEntries(SessionReference sessionRef, CallReference callRef, std::vector<AudioReference> & audioRefs, bool isMonitor, ta_int32 numEntriesRequired)
{
    TA_Base_Core::ThreadGuard  guard(m_audioMapLock);

    std::vector<AudioEntry *> entries_found;
    audioRefs.clear();

    // Find the audio map for the session
    SessionAudioMap::iterator sessionFnd = m_sessionAudioMap.find(sessionRef);
    if (sessionFnd!=m_sessionAudioMap.end())
    {
        AudioEntryMap * audioMap = (*sessionFnd).second;

        for (AudioEntryMap::iterator iter = audioMap->begin();
                iter != audioMap->end() && audioRefs.size()<numEntriesRequired ; iter++ )
        {
            if ( !((*iter).second.inUse) )
            {
                (*iter).second.callRef = callRef;
                (*iter).second.inUse = true;
                (*iter).second.isMonitor = isMonitor;
                (*iter).second.volume = m_sessionVolume[sessionRef];

                audioRefs.push_back( (*iter).first );
                entries_found.push_back( &((*iter).second) );
            }
        }
    }

    if (entries_found.size() < numEntriesRequired)
    {
        audioRefs.clear();
        for (std::vector<AudioEntry*>::iterator iter=entries_found.begin() ;
                iter!=entries_found.end(); iter++)
        {
            (*iter)->inUse = false;
        }
    }

    return audioRefs.size();
}


void RadioResourceManager::storeAudioEntry(SessionReference sessionRef, AudioReference audioRef, const AudioEntry & audioEntry)
{
    TA_Base_Core::ThreadGuard  guard(m_audioMapLock);

    // Find the audio map for the session
    SessionAudioMap::iterator sessionFnd = m_sessionAudioMap.find(sessionRef);
    if (sessionFnd!=m_sessionAudioMap.end())
    {
        AudioEntryMap * audioMap = (*sessionFnd).second;

        for (AudioEntryMap::iterator iter = audioMap->begin();
                iter != audioMap->end() ; iter++ )
        {
            if ( (*iter).first == audioRef )
            {
                (*iter).second = audioEntry;
                return;
            }
        }
    }

    LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugWarn, "AudioEntry NOT found for SessionReference %lu AudioReference %lu", sessionRef, audioRef);
}
//
// Big WTF here.
// 1. this should be called "updateCallVolume"
// 2. the outer for loop and if conditional should just be a m_sessionAudioMap.find()
// two other simple pieces of logic now fixed:
void RadioResourceManager::updateCallVolume(SessionID sessionReference, 
                                                 TA_IRS_App::CallReference callReference,
                                                 int currentVolume)
{
	FUNCTION_ENTRY("updateRadioAudioResourceManagerVars");
	
	
	//check for sesssionReference in m_sessionAudioMap;
	
    // iterate over the SessionAudioMap
	SessionAudioMap::iterator sessionIT = m_sessionAudioMap.begin();
	for ( ; sessionIT != m_sessionAudioMap.end(); sessionIT++)
	{
		// if this session matches the given one,
		if(sessionIT->first == sessionReference)
		{
			// iterate over the calls within the AudioEntryMap of that session
			AudioEntryMap::iterator audioMapIT = sessionIT->second->begin();
			for ( ; audioMapIT != sessionIT->second->end() ; audioMapIT++ )
			{
                // if the CallID matches the call in the audioentry,
				ta_uint32 destCallRef = audioMapIT->second.callRef;
				if(destCallRef == callReference)
				{
                    // update the volume
					audioMapIT->second.volume = currentVolume;
					break;
				}
			}
		}
	}

	FUNCTION_EXIT;
}


void RadioResourceManager::removeSessionFromAudioMap(SessionID sessionReference)
{
	FUNCTION_ENTRY("removeSessionFromAudioMap");

	TA_Base_Core::ThreadGuard  guard(m_audioMapLock);

	// Find the audio map for the session
	SessionAudioMap::iterator sessionIT = m_sessionAudioMap.find(sessionReference);
	if (sessionIT!=m_sessionAudioMap.end())
	{
		LOG3(SourceInfo, TA_Base_Core::DebugUtil::DebugInfo, "RadioTcpServer %d (CRS%d) Removing Audio Entry for session %d", m_radio.getServerIndex(), m_radio.getCRSNumber(), sessionReference);
		
		AudioEntryMap* audioMap;
		audioMap = sessionIT->second;
		m_sessionAudioMap.erase(sessionIT);
		delete audioMap;
	}
	else
	{
		LOG_GENERIC(SourceInfo,TA_Base_Core::DebugUtil::DebugWarn,
                    "Audio Resources for SessionReference %d were not found to remove",sessionReference);
	}

	FUNCTION_EXIT;
}


void RadioResourceManager::sendUpdateAudioEntry(SessionReference sessionReference, 
												AudioReference audioReference, const AudioEntry& audioEntry)
{
	FUNCTION_ENTRY("sendUpdateAudioEntry");

	RadioUpdateAudioEntryInSessionAudioMap message;
	message.sessionReference = sessionReference;
	message.audioReference = audioReference;
	message.audio.callRef = audioEntry.callRef;
	message.audio.inUse = audioEntry.inUse;
	message.audio.volume = audioEntry.volume;
	RadioStateUpdateBroadcaster::getInstance()->sendRadioUpdateAudioEntryInSessionAudioMap(message);

	FUNCTION_EXIT;
}



