/**
  * The source code in this file is the property of
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/4669_Review_Branch/4669/transactive/app/radio/RadioTetraAgent/src/RadioSessionInitialisationThread.cpp $
  * @author:  Andy Parker
  * @version: $Revision: #10 $
  *
  * Last modification: $DateTime: 2011/05/30 11:41:41 $
  * Last modified by:  $Author: bihui.luo $
  *
  * This class is used to initialise a session in the 
  * background.
  *
  */
///////////////////////////////////////////////////////////
//
//  RadioSessionInitialisationThread.cpp
//  Implementation of the Class RadioSessionInitialisationThread
//  Generated by Enterprise Architect
//  Created on:      06-Nov-2003 15:17:11
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////
#ifdef __WIN32__
#pragma warning(disable:4786)
#endif

#include "core/types/src/ta_types.h"
#include "app/radio/RadioTetraAgent/src/RadioSessionInitialisationThread.h"
#include "core/synchronisation/src/ThreadGuard.h"
#include "core/utilities/src/DebugUtil.h"
#include "core/utilities/src/RunParams.h"

using namespace TA_IRS_App;

using TA_Base_Core::DebugUtil;

RadioSessionInitialisationThread::RadioSessionInitialisationThread(RadioSession& radioSession)
: m_radioSession(radioSession),
  m_terminateThread(false),
  m_initialiseRetryDelay(15),
  m_semaphore(0),
  m_hasTriedLogin(true)
{
	FUNCTION_ENTRY("Constructor");
	m_destinationState=InitialiseSession;

    // retrieve from runtime parameters if possible
    std::string initialiseRetryDelayStr = TA_Base_Core::RunParams::getInstance().get("InitialiseRetryDelay");
    if ( !initialiseRetryDelayStr.empty() )
    {
        ta_int32 temp = atol(initialiseRetryDelayStr.c_str());

        if (temp > 0)
        {
            m_initialiseRetryDelay = temp;
        }
    }
    LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugDebug, "initialiseRetryDelay set to %d", m_initialiseRetryDelay );

	FUNCTION_EXIT;
}

RadioSessionInitialisationThread::~RadioSessionInitialisationThread()
{
	FUNCTION_ENTRY("Destructor");
    terminateAndWait();
	FUNCTION_EXIT;
}

void RadioSessionInitialisationThread::run()
{
	FUNCTION_ENTRY("run");

    m_terminateThread = false;
    requestedOperation tempDestinationState = InitialiseSession;
	if(!m_radioSession.isInitialised())//Queue Session Initialization... If the radio session is not yet initialized.
		processSessionInit(InitialiseSession);
    LOG_GENERIC(SourceInfo, DebugUtil::DebugDebug,
        "RadioSessionInitialisationThread for session %s started",
        m_radioSession.getSessionEntityName().c_str() );

    // this is the running loop, oly exited on shutdown
	std::pair<SessionReference,SessionReference> sessionRef;

    while (false == m_terminateThread)
    {
		{
//			TA_Base_Core::ThreadGuard guard(m_requestStateLock);

			while (shouldAttemptProcess())
			{
				m_semaphore.timedWait(m_initialiseRetryDelay * 1000);
				try
				{
                    {   //limin++ CL-21770
                        TA_THREADGUARD( m_destinationStateQueueLock );
                        
                        if ( false == m_destinationStateQueue.empty() )
                        {
                            m_destinationState = m_destinationStateQueue.front();
                            m_destinationStateQueue.pop();
                            LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugInfo,
                                "[run()][m_destinationState=%d][m_destinationStateQueue.size=%d]", m_destinationState, m_destinationStateQueue.size() );
                        }
						else	
						{
							if((m_destinationState==DetachSession || m_destinationState==LogoutSession) || m_radioSession.isLoggedIn())
							continue; //[Raghu] CL-21460 -- We have to continue waiting as we dont have a request to change our state.
						}
                        
                        tempDestinationState = m_destinationState;
                    }   //++limin CL-21770

					switch( tempDestinationState )
					{
						case InitialiseSession:
						case LoginSession:
							if ( !m_radioSession.isAttached() || !m_radioSession.isInitialised() )
							{
								if (m_radioSession.doAttachSession(sessionRef,m_initialiseRetryDelay) && m_radioSession.doInitialiseSession())
								{
									LOG_GENERIC(SourceInfo, DebugUtil::DebugInfo,
										"[run()] RadioSessionInitialisationThread, session: %s, ref: %d attached and initialized", 
										m_radioSession.getSessionEntityName().c_str(), sessionRef.second);
								}
								else if (shouldAttemptProcess())
								{
									LOG_GENERIC(SourceInfo, DebugUtil::DebugInfo,
										"[run()] RadioSessionInitialisationThread for session: %s, ref: %d waiting for retry %d seconds",
										m_radioSession.getSessionEntityName().c_str(),
										sessionRef.second,
										m_initialiseRetryDelay );
									m_semaphore.timedWait(m_initialiseRetryDelay * 1000);
									continue;
								}
							}
							else
							{
								LOG_GENERIC(SourceInfo, DebugUtil::DebugDebug, "[run()] RadioSession %s Attach: Intialised = %s.", 
									m_radioSession.getSessionEntityName().c_str(), m_radioSession.isAttached()?"true":"false" );
							}
							
							if (m_radioSession.isInitialised() && !m_radioSession.isLoggedIn())
							{
								m_radioSession.doLoginSession(sessionRef.first);
								
								if (shouldAttemptProcess() && !m_radioSession.isLoggedIn())
								{
									LOG_GENERIC(SourceInfo, DebugUtil::DebugInfo,
										"[run()] RadioSessionInitialisationThread for session: %s, ref: %d waiting for retry %d seconds",
										m_radioSession.getSessionEntityName().c_str(),
										sessionRef.second,
										m_initialiseRetryDelay );
									
									if ( m_radioSession.getIsISCSSession() || m_destinationState == LoginSession )
									{
										m_semaphore.timedWait(m_initialiseRetryDelay * 1000);
										continue;
									}
								}
							} 
							else
							{
								if (m_radioSession.isLoggedIn())
									m_radioSession.notifyLoginComplete();
									
								LOG_GENERIC(SourceInfo, DebugUtil::DebugDebug,"[run()] RadioSession %s Login: IsLoggedIn = %s",
									m_radioSession.getSessionEntityName().c_str(), m_radioSession.isLoggedIn()?"true":"false" );
							}
							break;

						case LogoutSession:
							if (m_radioSession.isLoggedIn())
							{
								m_radioSession.doLogoutSession();
								LOG_GENERIC(SourceInfo, DebugUtil::DebugInfo,
									"[run()] Request to logout RadioSession %s ",
									m_radioSession.getSessionEntityName().c_str() );
							}
							else
							{
								LOG_GENERIC(SourceInfo, DebugUtil::DebugWarn,
									"[run()] Request to logout RadioSession %s while it is not logged in",
									m_radioSession.getSessionEntityName().c_str() );
							}

							break;

						case DetachSession:
							if (m_radioSession.isAttached())
							{
								m_radioSession.doDetachSession();

								LOG_GENERIC(SourceInfo, DebugUtil::DebugInfo,
									"[run()] Request to detach RadioSession %s ",
									m_radioSession.getSessionEntityName().c_str() );
							} 
							else
							{
								LOG_GENERIC(SourceInfo, DebugUtil::DebugWarn,
									"[run()] Request to detach RadioSession %s while it is not attached",
									m_radioSession.getSessionEntityName().c_str() );
							}
							break;

						default:
							LOG_GENERIC(SourceInfo, DebugUtil::DebugWarn,
								"[run()] Not a valid request for RadioSessionInitialisationThread");
							break;
						}

						LOG_GENERIC(SourceInfo, DebugUtil::DebugWarn,
							"[run()] Process completed for RadioSessionInitialisationThread");
					break;
				}
				catch ( ... )
				{
					LOG_GENERIC(SourceInfo, DebugUtil::DebugWarn, "[run()] RadioSessionInitialisationThread: Got unknown error of session: %s", m_radioSession.getSessionEntityName().c_str() );
				}
			}
			if (!m_terminateThread) TA_Base_Core::Thread::sleep(100); //for reduce cpu usage
		}
	}

	FUNCTION_EXIT;
}


void RadioSessionInitialisationThread::processSessionInit(requestedOperation destinationState)
{
	LOG_GENERIC(SourceInfo, DebugUtil::DebugInfo, "RadioSessionInitialisationThread, requested state: %d, entity:%s, m_destinationStateQueue size=%d",
		destinationState, m_radioSession.getSessionEntityName().c_str(),m_destinationStateQueue.size()); 

	if ( destinationState >= m_destinationState )
	{
		//Just overwrite here.
		LOG_GENERIC(SourceInfo, DebugUtil::DebugDebug, 
			"RadioSessionInitialisationThread, session: %s, requested state replaced by %d, Original: %d", 
			m_radioSession.getSessionEntityName().c_str(), destinationState, m_destinationState );
	} 
	else
	{
	//	TA_Base_Core::ThreadGuard guard(m_requestStateLock);

		LOG_GENERIC(SourceInfo, DebugUtil::DebugDebug, 
			"RadioSessionInitialisationThread, session: %s, requested state change to %d, Original: %d", 
			m_radioSession.getSessionEntityName().c_str(), destinationState, m_destinationState );
	}

	{   // limin++ CL-21170
		TA_THREADGUARD( m_destinationStateQueueLock );
		if (m_destinationStateQueue.empty() || m_destinationStateQueue.back() != destinationState)
		{			
			if (destinationState==InitialiseSession)
			{					
				//In order to protect too many queue item
				//only keep one DetachSession or one LogoutSession, and remove another queued status	
				std::queue< requestedOperation > tempStateQueue;  //keep old status(DetachSession,LogoutSession)
				requestedOperation queuedState;			 
			    while (!m_destinationStateQueue.empty())		 
				{
					queuedState=m_destinationStateQueue.front();
					m_destinationStateQueue.pop();					
					if (queuedState==DetachSession ||  queuedState==LogoutSession )
					{
						tempStateQueue.push(queuedState);
						LOG_GENERIC(SourceInfo, DebugUtil::DebugInfo, "RadioSessionInitialisationThread pop up unnecessary request  state: %d",queuedState);
					}						 			
				} 
				bool isHasDetach=false;
				bool isHasLogout=false;
				while (!tempStateQueue.empty())		 
				{
					queuedState=tempStateQueue.front();
					tempStateQueue.pop();
					if (isHasDetach==false && queuedState==DetachSession )  //only keep one DetachSession or one LogoutSession,
					{
						m_destinationStateQueue.push(queuedState);
						isHasDetach=true;
					}
					else if (isHasLogout==false && queuedState==LogoutSession )  //only keep one DetachSession or one LogoutSession,
					{
						m_destinationStateQueue.push(queuedState);
						isHasLogout=true;
					}
				}				 
			}			
			m_destinationStateQueue.push( destinationState );
			//m_destinationState = destinationState;
			LOG_GENERIC(SourceInfo, DebugUtil::DebugInfo, "RadioSessionInitialisationThread, current requested state: %d, Entity:%s m_destinationStateQueue size=%d", 
				destinationState, m_radioSession.getSessionEntityName().c_str(),m_destinationStateQueue.size()); 
		}
		else
		{
			LOG_GENERIC(SourceInfo, DebugUtil::DebugInfo, "Last state in queue and current requested state are the same: %d. Skiping the requested state. Entity:%s", destinationState, m_radioSession.getSessionEntityName().c_str()); 

		}

	}   //++limin CL-21170


	// just give it a poke...
	m_semaphore.post();
}


void RadioSessionInitialisationThread::terminate()
{
	FUNCTION_ENTRY("terminate");

    // set the flag
    m_terminateThread = true;

    // unblock the thread
    m_semaphore.post();

	FUNCTION_EXIT;
}


bool RadioSessionInitialisationThread::shouldAttemptProcess()
{

	LOG_GENERIC (SourceInfo, TA_Base_Core::DebugUtil::DebugInfo, 
		"[shouldAttemptLogin]  Entity = %s, m_terminateThread = %d, request Detach = %s.", 
		m_radioSession.getSessionEntityName().c_str(), m_terminateThread, (m_destinationState == DetachSession)?"true":"false");

	m_radioSession.updateRadioStatusSummary();

    return ( !m_terminateThread &&
             m_radioSession.shouldLogIn() );
}