//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 STISManager.rc 使用
//
#define IDD_STISMANAGER_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_LED_ATTRIBUTES              129
#define IDD_PLASMA_ATTRIBUTES           130
#define IDR_MENU1                       131
#define IDD_PREDEFINED                  132
#define IDD_FREE_TEXT                   133
#define IDD_RATIS_APPROVAL              134
#define IDD_RATIS                       135
#define IDD_DISPLAY_PAGE                136
#define IDD_VERSION_PAGE                137
#define IDD_PREDEFINED2                 138
#define IDD_DIALOG1                     139
#define IDD_PID_GROUP_NAME              140
#define IDD_DLG_INITPROGRESS            141
#define IDD_TEMPLATE                    142
#define IDD_CURRENT_DISPLAY_MESSAGES    146
#define IDD_PID_CONTROL                 147
#define IDR_MENU2                       148
#define IDC_PID_CONTROL_BUTTON          730
#define IDC_RADIO_CONTROL_ALL_OFF       731
#define IDC_RADIO_CONTROL_MON1_ON       732
#define IDC_RADIO_CONTROL_MON2_ON       740
#define IDC_RADIO_CONTROL_ALL_ON        741
#define IDC_CHECK_SCHEDULE              733
#define IDC_EDIT_MONITOR_OFF_TIME       734
#define IDC_EDIT_MONITOR_ON_TIME        735
#define IDC_PID_CONTROL_SEND            736
#define IDC_PID_CONTROL_CANCEL          737
#define IDC_STATIC_MONITOR_OFF          738
#define IDC_STATIC_MONITOR_ON           739
#define IDC_RADIO_NORMAL_TEMPLATE       194
#define IDC_RADIO_EMERGENCY_TEMPLATE    195
#define IDC_DEFAULT_SETTING             196
#define IDC_LCD_DEFAULT_SETTING         196
#define IDC_DEFAULT_SETTING2            197
#define IDC_LED_DEFAULT_SETTING         197
#define IDC_LCD_TEMPLATE                198
#define IDC_LED_TEMPLATE                199
#define IDC_SEARCH_LCD                  200
#define IDC_SEARCH_LED                  201
#define IDC_MESSAGE_CONTENT_LABEL       202
#define IDC_MESSAGE_TITLE               203
#define IDC_EDIT                        204
#define IDC_LIST1                       205
#define IDC_FREETEXT_LIST_2             205
#define IDC_CDM_MESSAGES                206
#define IDC_CDM_STATION                 207
#define IDC_CDM_PID                     208
#define IDC_CDM_TEMPLATE_TYPE           209
#define IDC_CDM_TEMPLATE_ID             210
#define IDC_CDM_TEMPLATE_START_TIME     211
#define IDC_CDM_TEMPLATE_END_TIME       212
#define IDC_CDM_MESSAGE_STATUS          213
#define IDC_CDM_CLEAR                   214
#define IDC_CDM_MESSATE_TEXT            215
#define IDC_CDM_MESSAGE_TEXT            215
#define IDC_TREE1                       216
#define IDC_PID_TREE                    216
#define IDC_PID_LOCATION_FILTER_TREE    217
#define IDC_SPLIT_LOCATION              218
#define IDC_SPLIT_AREA                  219
#define IDC_PID_AREA_FILTER_TREE        220
#define IDC_RADIO_PREDEFINED            300
#define IDC_RADIO_FREE_TEXT             301
#define IDC_NORMAL_PREDEFINED           302
#define IDC_EMERGENCY_PREDEFINED        303
#define IDC_PREDEFINED_CONTENT          304
#define IDC_SEARCH                      305
#define IDC_SEARCH_NORMAL               306
#define IDC_STATION_MESSAGE_VERSION_LIST 307
#define IDC_STATION_FREE_TEXT           308
#define IDC_VERSION_LIST_MAIN_HEADER1   309
#define IDC_PID_ATTRIBUTES              310
#define IDC_STATION_FREE_TEXT2          311
#define IDC_STATION_TEMPLATE_VERSION_LIST 312
#define IDC_SPELL_CHECK                 313
#define IDC_VERSION_LIST_MAIN_HEADER2   314
#define IDC_RADIO_NORMAL                315
#define IDC_RADIO_EMERGENCY             316
#define IDC_PRIORITY                    317
#define IDC_DISPLAY_MODE                318
#define IDC_VERSION_LIST_SUBHEADER1     319
#define IDC_SCROLL_SPEED                320
#define IDC_VERSION_LIST_SUBHEADER2     321
#define IDC_JUSTIFICATION               322
#define IDC_START_TIME1                 325
#define IDC_END_TIME1                   326
#define IDC_START_TIME2                 327
#define IDC_DISPLAY_TIME                328
#define IDC_START_DATE1                 329
#define IDC_END_DATE1                   330
#define IDC_DISPLAY_TIME_ADJUST         400
#define IDC_LED_FONT_SIZE               401
#define IDC_END_TIME2                   402
#define IDC_SEARCH_EMERGENCY            403
#define IDC_DISPLAY_TIME_SPIN           404
#define IDC_LED_FONT_COLOR              405
#define IDC_START_DATE2                 406
#define IDC_END_DATE2                   407
#define IDC_PLASMA_FONT_SIZE            408
#define IDC_PLASMA_FOREGROUND_COLOUR    409
#define IDC_PLASMA_BACKGROUND_COLOUR    410
#define IDC_LABEL1                      411
#define IDC_LABEL2                      412
#define IDC_LABEL5                      413
#define IDC_END_TIME_LABEL              414
#define IDC_LABEL8                      415
#define IDC_LABEL6                      416
#define IDC_LABEL10                     417
#define IDC_END_TIME_LABEL2             418
#define IDC_LABEL17                     419
#define IDC_DISPLAYTIME_LABEL           420
#define IDC_LABEL7                      421
#define IDC_LABEL11                     422
#define IDC_END_TIME_LABEL3             423
#define IDC_LABEL12                     424
#define IDC_LABEL13                     425
#define IDC_SCROLLSPEED_LABEL           426
#define IDC_LABEL14                     427
#define IDC_JUSTIFICATION_LABEL         428
#define IDC_LABEL9                      429
#define IDC_LABEL16                     430
#define IDC_MINS_LABEL                  500
#define IDC_NORMAL_LABEL                501
#define IDC_EMERGENCY_LABEL             502
#define IDC_CONTENT_LABEL               503
#define IDC_ISCS__MESSAGE_CURRENT_VERSION 504
#define IDC_ISCS_MESSAGE_CURRENT_VERSION 504
#define IDC_ISCS__MESSAGE_NEXT_VERSION  505
#define IDC_LABEL_SEARCH1               506
#define IDC_ISCS_TEMPLATE_CURRENT_VERSION 507
#define IDC_LABEL_SEARCH2               508
#define IDC_ISCS_TEMPLATE_NEXT_VERSION  509
#define IDC_COMBO1                      510
#define IDC_RATIS_TAG                   511
#define IDC_DISPLAY                     512
#define IDC_DISPLAY_MESSAGE             512
#define IDC_COMBO2                      513
#define IDC_RATIS_DEST                  514
#define IDC_LABEL15                     515
#define IDC_LABEL3                      516
#define IDC_DISPLAY2                    517
#define IDC_DISPLAY_TEMPLATE            517
#define IDC_LABEL4                      518
#define IDC_MESSAGE_TYPE_TAB            519
#define IDC_PID_LIST                    520
#define IDC_LANGUAGES                   521
#define IDC_BUTTON1                     522
#define IDC_CLEAR_CURRENT_MESSAGES      522
#define IDC_ALL_MESSAGE_VIEWER_BUTTON   522
#define IDC_BUTTON2                     523
#define IDC_BUTTON3                     524
#define IDC_ALL_MESSAGE_VIEWER_BUTTON2  524
#define IDC_ALL_TEMPLATE_VIEWER_BUTTON  524
#define IDC_MESSAGE_CONTENT             525
#define IDC_CLEAR_NORMAL_MESSAGE        526
#define IDC_TYPE                        527
#define IDC_TAG                         528
#define IDC_CLEAR_ALL                   529
#define IDC_CLEAR_NORMAL_TEMPLATE       530
#define IDC_CLEAR_EMERGENCY_TEMPLATE    600
#define IDC_CLEAR_EMERGENCY_MESSAGE_AND_TEMPLATE 601
#define IDC_DISPLAY_ALL                 602
#define IDC_CLEAR_RATIS                 603
#define IDC_FREETEXT_LIST               604
#define IDC_RECENT_MESSAGES             605
#define IDC_MESSAGE_TITLE_LABEL         605
#define IDC_SAVE                        606
#define IDC_RATIS_CONTENT               607
#define IDC_EDIT2                       608
#define IDC_EDIT3                       609
#define IDC_UPGRADE_ISCS_MESSAGE        610
#define IDC_EDIT4                       611
#define IDC_UPGRADE_ISCS_TEMPLATE       612
#define IDC_EDIT5                       613
#define IDC_RADIO2                      614
#define IDC_RADIO3                      615
#define IDC_RADIO4                      616
#define IDC_LANGUAGES_LABEL             617
#define IDC_MESSAGE_CONTENT_FRAME       618
#define IDC_DISPLAY_ATTRIBUTES_FRAME    619
#define IDC_PLASMA_FRAME                620
#define IDC_LED_FRAME                   621
#define IDC_MESSAGE_TYPE_FRAME          622
#define IDC_RATIS_TAG_FRAME             623
#define IDC_DESTINATION_FRAME           624
#define IDC_RATIS_CONTENT_FRAME         625
#define IDC_MAINPAGE_TAB                626
#define ID_CLOSE                        627
#define IDC_START_TIME_LABEL            628
#define IDC_START_TIME_LABEL2           629
#define IDC_LCD_STATIC_LABEL            629
#define IDC_RADIO_NEW                   630
#define IDC_START_TIME_LABEL3           700
#define IDC_LCD_LABEL                   700
#define IDC_RADIO_CLEAR                 701
#define IDC_START_TIME_LABEL4           702
#define IDC_LED_STATIC_LABEL            702
#define IDC_PROGRESS_CTRL               703
#define IDC_START_TIME_LABEL5           704
#define IDC_LED_LABEL                   704
#define IDC_STATIC_TEXT1                705
#define IDC_START_TIME_LABEL6           706
#define IDC_STATIC_TEXT2                707
#define IDC_START_TIME_LABEL7           708
#define IDC_SELECTED_MESSAGE            708
#define IDC_STATIC_TEXT3                709
#define IDC_CLOSE                       710
#define IDC_HELP_BUTTON                 711
#define IDC_SAVE_GROUP                  712
#define IDC_DELETE_GROUP                713
#define IDC_SAVE_GROUP2                 714
#define IDC_LCD_PREVIEW                 714
#define IDC_SAVE_GROUP3                 715
#define IDC_LED_PREVIEW                 715
#define IDC_STN_PID_GROUP_COMBO         716
#define IDC_EDITNAME                    717
#define IDC_STATICTEXT                  718
#define IDC_CHB_OVERRIDE                719
#define IDC_CHB_VETTING                 720
#define ID_FILE_EXIT                    32771
#define ID_HELP_ABOUTSTISMANAGER        32772
#define ID_HELP_STISMANAGERHELP         32773
#define ID_SELECTED_REMOVE              32774
#define ID_SELECTEDPID_REMOVE           32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         220
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
