///////////////////////////////////////////////////////////
//
//  AttachSessionExtEventReader.cpp
//  Implementation of the Class AttachSessionExtEventReader
//  Generated by Enterprise Architect
//  Created on:      10-Nov-2003 16:38:14
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "AttachSessionExtEventReader.h"
#include "core/utilities/src/TAAssert.h"
#define ATTACH_SESSION_EXT_PARAM 0

namespace TA_IRS_App
{
    AttachSessionExtEventReader::AttachSessionExtEventReader(RadioEvent& event)
		   : RadioEventReader(event,EVENT_ATTACH_SESSION_EXT,ATTACH_SESSION_EXT_PARAM)
    {
    }

    AttachSessionExtEventReader::~AttachSessionExtEventReader()
    {
    }

}


