/**
  * The source code in this file is the property of
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/4669_T01271350/4669/transactive/app/radio/RadioTetraAgent/RadioProtocolLibrary/src/RadioMethodCallReference.cpp $
  * @author:  Ripple
  * @version: $Revision: #1 $
  *
  * Last modification: $DateTime: 2008/11/28 16:26:01 $
  * Last modified by:  $Author: builder $
  *
  */
///////////////////////////////////////////////////////////
//
//  RadioMethodCallReference.cpp
//  Implementation of the Class RadioMethodCallReference
//  Generated by Enterprise Architect
//  Created on:      06-Nov-2003 08:37:06
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "core/types/src/ta_types.h"
#include "RadioMethodCallReference.h"
#include "core/utilities/src/DebugUtil.h"

using namespace TA_IRS_App;

#define CALL_REFERENCE_START_POSITION   0

/**
* Constructor
* @param    messageSize
* @param    messageType
* @param    sessionRef
* @param    callRef
*/
RadioMethodCallReference::RadioMethodCallReference(ta_uint32 messageSize, ta_uint32 messageType, 
												   RadioSessionReference sessionRef, RadioCallReference callRef) 
						 :RadioMethod(messageSize,messageType,sessionRef)
{
    // limin++ CALL REFERENCE
    if ( callRef > 100 )
	{
	    callRef /= 100;
	}
	
    LOG_GENERIC( SourceInfo, TA_Base_Core::DebugUtil::DebugInfo, "LIMINTEST CALL REFERENCE: [callRef=%d]", callRef );
    // ++limin CALL REFERENCE

    setParameterLong(CALL_REFERENCE_START_POSITION,callRef ); 
}


RadioMethodCallReference::~RadioMethodCallReference()
{

}


void RadioMethodCallReference::setCharacterEncoding(ECodePage codePage)
{

}

void RadioMethodCallReference::setDefaultCharacterEncoding(ECodePage codePage)
{

}


