/**
  * The source code in this file is the property of
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/4669_T01271350/4669/transactive/app/radio/RadioTetraAgent/RadioProtocolLibrary/src/RadioMethodLogin.cpp $
  * @author:  Andy Parker
  * @version: $Revision: #1 $
  *
  * Last modification: $DateTime: 2008/11/28 16:26:01 $
  * Last modified by:  $Author: builder $
  *
  *
  */
  ///////////////////////////////////////////////////////////
  //
  //  RadioMethodLogin.cpp
  //  Implementation of the Class RadioMethodLogin
  //  Generated by Enterprise Architect
  //  Created on:      07-Nov-2003 11:04:01
  //  Original author: 
  //  
  ///////////////////////////////////////////////////////////
  //  Modification history:
  //  
  //
  ///////////////////////////////////////////////////////////

#include "core/types/src/ta_types.h"
#include "RadioMethodChangePassword.h"
#include "RadioProtocol.h"

using namespace TA_IRS_App;

#define CHANGE_PASSWORD_METHOD_LENGTH		64
#define OLD_PASSWORD_START					0
#define NEW_PASSWORD_START					32


/**
* Constructor
* @param    sessionRef
*/
RadioMethodChangePassword::RadioMethodChangePassword(ta_uint32 sessionRef, std::string oldPassword, std::string newPassword)
	:RadioMethod(CHANGE_PASSWORD_METHOD_LENGTH, METHOD_CHANGE_PASSWORD, sessionRef)
{
	setParameterShortString(OLD_PASSWORD_START, oldPassword);
	setParameterShortString(NEW_PASSWORD_START, newPassword);
}


/**
  * RadioMethodInitialise::~RadioMethodInitialise
  *
  * Descructor
  *
  */
RadioMethodChangePassword::~RadioMethodChangePassword()
{

}



