///////////////////////////////////////////////////////////
//
//  RadioProtocolException.h
//  Implementation of the Class RadioProtocolException
//  Generated by Enterprise Architect
//  Created on:      06-Nov-2003 15:03:54
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(RadioProtocolException_0D279184_D225_4c31_9777_59AC3A1EFFAB__INCLUDED_)
#define RadioProtocolException_0D279184_D225_4c31_9777_59AC3A1EFFAB__INCLUDED_

#include "core/exceptions/src/TransactiveException.h"
/**
* This exception is thrown when a radio session method is called and the session
* has not been or completed initialisation.
* @version 1.0
* @generator Enterprise Architect
* @created 06-Nov-2003 15:03:54
*/

namespace TA_IRS_App
{
	class RadioProtocolException : public TA_Base_Core::TransactiveException
	{
		public:
			RadioProtocolException(const std::string& errorText) throw();
			virtual ~RadioProtocolException() throw();
	};
};

#endif // !defined(RadioProtocolException_0D279184_D225_4c31_9777_59AC3A1EFFAB__INCLUDED_)
