#if !defined(RadioSDSTLTypes_H)
#define RadioSDSTLTypes_H

namespace TA_IRS_App
{

	enum ECodePage //Represents the possible codepages an SDS can be in
	{
		 Ascii = 1,    //Initial Value: 1; 
		 Ucs2 = 26 	   //Initial Value: 26;  bin: 00011010
	};

	enum EAckRequest
	{
		SDSTL_ACK_REQ = 1,  
		SDSTL_ACK_NOT_REQ = 2 	
	};
	/*Connections 
		"	Trace link to artifact RadioProtocol.h
		"	Dependency link from class IncomingSDSTLReportEventReader
		"	Dependency link from class RadioMethodTLSDSReport
	//*/	
	enum ESDSTL_Ack_DeliveryStatus
	{
		SDSTL_STOK_ACK_REPORT_MSG_RECEIVED = 1,
		SDSTL_STOK_ACK_REPORT_MSG_CONSUMED = 2	
	};
	
	enum ESDSTL_Report_DeliveryStatus
	{
		SDSTL_STOK_MSG_RECEIVED = 1,
		SDSTL_STOK_MSG_CONSUMED,
		SDSTL_STOK_FWD_TO_EXT_NETWORK,
		SDSTL_STKO_SDS_TL_NOT_SUPPORTED,
		SDSTL_STKO_PROTOCOL_NOT_SUPPORTED,
		SDSTL_STKO_DATA_CODING_SCHEME_NOT_SUPPORTED,
		SDSTL_STKO_DEST_MEM_FULL_MSG_DISCARDED,
		SDSTL_STKO_HOST_NOT_CONNECTED,
		SDSTL_STOK_RECEIPT_REP_ACK,
		SDSTL_STOK_CONSUMED_REP_ACK,
		SDSTL_STOK_TO_GROUP_ACK_PREVENTED,
		SDSTL_STKO_CONGESTION_MSG_STORED,
		SDSTL_STKO_DEST_NOT_REACH_MSG_STORED,
		SDSTL_STKO_NETWORK_OVERLOAD,
		SDSTL_STKO_SERVICE_NOT_AVAILABLE_PERMANENTLY,
		SDSTL_STKO_SERVICE_NOT_AVAILABLE_TEMPORARLY,
		SDSTL_STKO_SOURCE_NOT_AUTH_TO_TL,
		SDSTL_STKO_DEST_NOT_AUTH_TO_TL,
		SDSTL_STKO_UNKNOWN_DESTINATION,
		SDSTL_STKO_UNKNOWN_FORWARD_ADDRESS,
		SDSTL_STKO_GROUP_ADDR_WITH_INDIVIDUAL_SRV,
		SDSTL_STKO_PERIOD_EXPIRED_NOT_RECEIVED,
		SDSTL_STKO_PERIOD_EXPIRED_NOT_CONSUMED,
		SDSTL_STKO_DELIVERY_FAILED,
		SDSTL_STKO_DEST_NOT_REGISTERED,
		SDSTL_STKO_DEST_QUEUE_FULL,
		SDSTL_STKO_MSG_TOO_LONG_FOR_DEST,	
		SDSTL_STKO_DEST_NOT_ACCEPT_SDS_MSG,
		SDSTL_STKO_DEST_ADDR_ADMIN_PROHIBITED,
		SDSTL_STKO_CANNOT_ROUTE_TO_EXT_NETWORK,
		SDSTL_STKO_UNKNOWN_EXT_NUMBER,
		SDSTL_STKO_NEGATIVE_REPORT_ACK,
		SDSTL_STKO_DEST_NOT_REACH_DELIVERY_FAILED,
		SDSTL_STKO_DEST_MEMORY_FULL,
		SDSTL_STKO_DEST_MEMORY_AVAILABLE,
		SDSTL_STKO_START_PENDING_MESSAGE,
		SDSTL_STKO_NO_PENDING_MESSAGE,
		SDSTL_STKO_STOP_SENDING,				
		SDSTL_STKO_START_SENDING
	};

	enum ESDSTLProtocol 
	{
		SDSTL_PROT_TEXT_MESSAGING = 0x82,
		SDSTL_PROT_GPS            = 0x83,
		SDSTL_PROT_WAP            = 0x84,
		SDSTL_PROT_WCMP           = 0x85,
		SDSTL_PROT_USER_1         = 0xC0,	
		SDSTL_PROT_USER_2,
		SDSTL_PROT_USER_3,
		SDSTL_PROT_USER_4,
		SDSTL_PROT_USER_5,
		SDSTL_PROT_USER_6,
		SDSTL_PROT_USER_7,
		SDSTL_PROT_USER_8,
		SDSTL_PROT_USER_9,
		SDSTL_PROT_USER_10,
		SDSTL_PROT_USER_11,
		SDSTL_PROT_USER_12,	
		SDSTL_PROT_USER_13,
		SDSTL_PROT_USER_14,
		SDSTL_PROT_USER_15,
		SDSTL_PROT_USER_16,
		SDSTL_PROT_USER_17,
		SDSTL_PROT_USER_18,
		SDSTL_PROT_USER_19,
		SDSTL_PROT_USER_21,
		SDSTL_PROT_USER_22,
		SDSTL_PROT_USER_23,
		SDSTL_PROT_USER_24,
		SDSTL_PROT_USER_25,
		SDSTL_PROT_USER_26,
		SDSTL_PROT_USER_27,
		SDSTL_PROT_USER_28,
		SDSTL_PROT_USER_29,
		SDSTL_PROT_USER_30,
		SDSTL_PROT_USER_31,
		SDSTL_PROT_USER_32,
		SDSTL_PROT_USER_33,
		SDSTL_PROT_USER_34,
		SDSTL_PROT_USER_35,
		SDSTL_PROT_USER_36,
		SDSTL_PROT_USER_37,
		SDSTL_PROT_USER_38,
		SDSTL_PROT_USER_39,
		SDSTL_PROT_USER_40,
		SDSTL_PROT_USER_41,
		SDSTL_PROT_USER_42,
		SDSTL_PROT_USER_43,
		SDSTL_PROT_USER_44,
		SDSTL_PROT_USER_45,
		SDSTL_PROT_USER_46,
		SDSTL_PROT_USER_47,
		SDSTL_PROT_USER_48,
		SDSTL_PROT_USER_49,
		SDSTL_PROT_USER_50,
		SDSTL_PROT_USER_51,	
		SDSTL_PROT_USER_52,
		SDSTL_PROT_USER_53,
		SDSTL_PROT_USER_54,
		SDSTL_PROT_USER_55,
		SDSTL_PROT_USER_56,
		SDSTL_PROT_USER_57,
		SDSTL_PROT_USER_58,
		SDSTL_PROT_USER_59,
		SDSTL_PROT_USER_60,
		SDSTL_PROT_USER_61,	
		SDSTL_PROT_USER_62,
		SDSTL_PROT_USER_63,
		SDSTL_PROT_USER_64
	};

	enum ESDSTLReportType
	{
		SDSTL_NORMAL_REPORT = 1,
		SDSTL_SHORTMODE_REPORT = 2 
	};

	enum ESDSTLServiceSelection
	{
		SDSTL_GROUP = 1,
		SDSTL_INDIVIDUAL = 2 
	};

	enum ESDSTLResponseRequested
	{
		SDSTL_REPREQ_NONE = 1,
		SDSTL_REPREQ_ONRECEIVE = 2,
		SDSTL_REPREQ_ONCONSUME = 3,
		SDSTL_REPREQ_ONRECEIVE_ONCONSUME = 4
	};
}	


#endif
