///////////////////////////////////////////////////////////
//
//  RadioMethodAttachSessionExt.cpp
//  Implementation of the Class RadioMethodAttachSession
//  Generated by Enterprise Architect
//  Created on:      06-Nov-2003 09:58:38
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "RadioMethodAttachSessionExt.h"
#include "RadioProtocol.h"

using namespace TA_IRS_App;

#define FIXEDSTRING_LENGTH  260
#define FIXEDSTRING_POS       0

/**
* Constructor
* @param    sessionRef
*/
RadioMethodAttachSessionExt::RadioMethodAttachSessionExt(const std::string& ipAddressGWLD)
						 :RadioMethod(FIXEDSTRING_LENGTH,METHOD_ATTACH_SESSION_EXT,0)
{
	setParameterLongString(FIXEDSTRING_POS,ipAddressGWLD);
}

RadioMethodAttachSessionExt::~RadioMethodAttachSessionExt()
{

}