///////////////////////////////////////////////////////////
//
//  RadioMethodAttachSessionExt.h
//  Implementation of the Class RadioMethodAttachSession
//  Generated by Enterprise Architect
//  Created on:      06-Nov-2003 09:58:38
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(RadioMethodAttachSessionExt_2DDF887C_7234_4da4_ABB6_32EBD1F3FFD9__INCLUDED_)
#define RadioMethodAttachSessionExt_2DDF887C_7234_4da4_ABB6_32EBD1F3FFD9__INCLUDED_

#include "RadioMethod.h"

/**
* Create a new session with the radio hardware
* @version 1.0
* @generator Enterprise Architect
* @created 06-Nov-2003 09:58:38
*/

namespace TA_IRS_App
{
	class RadioMethodAttachSessionExt : public RadioMethod
	{

		public:
			/**
			* Constructor
			* @param    sessionRef
			*/
			RadioMethodAttachSessionExt(const std::string& ipAddressGWLD);
			virtual ~RadioMethodAttachSessionExt();

	};
};

#endif // !defined(RadioMethodAttachSessionExt_2DDF887C_7234_4da4_ABB6_32EBD1F3FFD9__INCLUDED_)
