///////////////////////////////////////////////////////////
//
//  RadioProtocolException.cpp
//  Implementation of the Class RadioProtocolException
//  Generated by Enterprise Architect
//  Created on:      06-Nov-2003 15:03:54
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "RadioProtocolException.h"


using namespace TA_IRS_App;


RadioProtocolException::RadioProtocolException(const std::string& errorText) throw()
					  : TA_Base_Core::TransactiveException(errorText)
{
}


RadioProtocolException::~RadioProtocolException() throw()
{
}


